"""Generates `stdlib/std.fasteners/records/*.toml` from the committed
ISO dimension table `tools/stdlib/data/iso_fasteners.toml` (WO-66,
D174 sourcing law rule 3: standard-table families are GENERATED, not
hand-typed). Deterministic: same input table -> byte-identical output
(no wall-clock, no randomness, sorted rows).
"""

from __future__ import annotations

import tomllib
from pathlib import Path

from tools.stdlib.render import render_records_file

# frob:doc docs/modules/tools.md#stdlib-gen-fasteners
REPO_ROOT = Path(__file__).resolve().parents[2]
# frob:doc docs/modules/tools.md#stdlib-gen-fasteners
DATA_FILE = REPO_ROOT / "tools" / "stdlib" / "data" / "iso_fasteners.toml"
# frob:doc docs/modules/tools.md#stdlib-gen-fasteners
OUT_DIR = REPO_ROOT / "stdlib" / "std.fasteners" / "records"

_LENGTH_NOTE = (
    "generated by tools/stdlib/gen_fasteners.py from a representative "
    "common-stock length subset (8-50mm), NOT the standard's full "
    "per-diameter min/max length range (that per-diameter table was "
    "not independently re-verified this session and is omitted "
    "rather than guessed)"
)


def _class_suffix(cls: str) -> str:
    return cls.replace(".", "_")


# frob:waive PERF004 reason="one-shot sort of a small set, never re-sorted"
def _socket_head_cap_screws(data: dict) -> list[dict]:
    rows = []
    for entry in data["iso_4762"]:
        d = entry["d"]
        for length in data["standard_length_series_mm"]:
            if length < d * 1.5:
                continue  # shorter than the head diameter reads as not-real stock
            for cls, props in data["property_class"].items():
                key = f"shcs_iso4762_m{d:g}x{length:g}_{_class_suffix(cls)}"
                rows.append(
                    {
                        "key": key,
                        "standard": "ISO 4762",
                        "nominal_dia_mm": d,
                        "pitch_mm": entry["pitch"],
                        "length_mm": float(length),
                        "head_dia_mm": entry["dk"],
                        "head_height_mm": entry["k"],
                        "socket_size_mm": entry["s"],
                        "property_class": cls.replace("_", "."),
                        "proof_stress_mpa": props["proof_stress_mpa"],
                        "yield_mpa": props["yield_mpa"],
                        "tensile_min_mpa": props["tensile_min_mpa"],
                        "evidence": {
                            "method": "catalog",
                            "trust_tier": "community",
                            "reference": (
                                "ISO 4762:2004 (hexagon socket head cap "
                                "screws) dimension table + ISO 898-1:2013 "
                                f"property class {cls.replace('_', '.')} "
                                f"mechanical properties; {_LENGTH_NOTE}"
                            ),
                        },
                    }
                )
    return sorted(rows, key=lambda r: r["key"])


# frob:waive PERF004 reason="one-shot sort of a small set, never re-sorted"
def _hex_bolts(data: dict) -> list[dict]:
    rows = []
    for entry in data["iso_4014"]:
        d = entry["d"]
        for length in data["standard_length_series_mm"]:
            if length < d * 1.5:
                continue
            for cls, props in data["property_class"].items():
                key = f"hexbolt_iso4014_m{d:g}x{length:g}_{_class_suffix(cls)}"
                rows.append(
                    {
                        "key": key,
                        "standard": "ISO 4014",
                        "nominal_dia_mm": d,
                        "pitch_mm": entry["pitch"],
                        "length_mm": float(length),
                        "across_flats_mm": entry["s"],
                        "head_height_mm": entry["k"],
                        "property_class": cls.replace("_", "."),
                        "proof_stress_mpa": props["proof_stress_mpa"],
                        "yield_mpa": props["yield_mpa"],
                        "tensile_min_mpa": props["tensile_min_mpa"],
                        "evidence": {
                            "method": "catalog",
                            "trust_tier": "community",
                            "reference": (
                                "ISO 4014:2011 (hexagon head bolts, product "
                                "grade A/B) dimension table + ISO 898-1:2013 "
                                f"property class {cls.replace('_', '.')} "
                                f"mechanical properties; {_LENGTH_NOTE}"
                            ),
                        },
                    }
                )
    return sorted(rows, key=lambda r: r["key"])


# frob:waive PERF004 reason="one-shot sort of a small set, never re-sorted"
def _hex_nuts(data: dict) -> list[dict]:
    rows = []
    for entry in data["iso_4032"]:
        d = entry["d"]
        for cls in data["property_class"]:
            # Nuts pair to a bolt property class per ISO 898-2; the
            # simplest, well-established nut-class label is used (no
            # separate nut proof-load table transcribed here -- that
            # per-nut-class table was not independently re-verified
            # this session and is omitted rather than guessed).
            key = f"hexnut_iso4032_m{d:g}_{_class_suffix(cls)}"
            rows.append(
                {
                    "key": key,
                    "standard": "ISO 4032",
                    "nominal_dia_mm": d,
                    "pitch_mm": entry["pitch"],
                    "across_flats_mm": entry["s"],
                    "height_mm": entry["m"],
                    "bolt_property_class": cls.replace("_", "."),
                    "evidence": {
                        "method": "catalog",
                        "trust_tier": "community",
                        "reference": (
                            "ISO 4032:2012 (hexagon nuts, style 1) "
                            "dimension table; paired bolt property class "
                            "per ISO 898-2 nut/bolt pairing convention "
                            "(nut proof-load table itself not "
                            "independently re-verified and omitted)"
                        ),
                    },
                }
            )
    return sorted(rows, key=lambda r: r["key"])


# frob:waive PERF004 reason="one-shot sort of a small set, never re-sorted"
def _plain_washers(data: dict) -> list[dict]:
    rows = []
    for entry in data["iso_7089"]:
        d = entry["d"]
        key = f"washer_iso7089_m{d:g}"
        rows.append(
            {
                "key": key,
                "standard": "ISO 7089",
                "nominal_dia_mm": d,
                "inner_dia_mm": entry["id"],
                "outer_dia_mm": entry["od"],
                "thickness_mm": entry["t"],
                "evidence": {
                    "method": "catalog",
                    "trust_tier": "community",
                    "reference": (
                        "ISO 7089:2000 (plain washers, normal series, "
                        "product grade A) dimension table"
                    ),
                },
            }
        )
    return sorted(rows, key=lambda r: r["key"])


# frob:doc docs/modules/tools.md#stdlib-gen-fasteners
def generate() -> dict[str, str]:
    """Returns {relative_output_path: rendered_content} for every
    std.fasteners records file this generator owns (in-memory; the
    caller decides whether to write to disk or diff against committed
    content -- shared by `make stdlib-gen` and the drift-check test).
    """
    with DATA_FILE.open("rb") as f:
        data = tomllib.load(f)

    families = {
        "socket_head_cap_screws.toml": (
            "component",
            _socket_head_cap_screws(data),
            "ISO 4762 socket head cap screws, generated per-size x "
            "per-length x per-property-class grid.",
        ),
        "hex_bolts.toml": (
            "component",
            _hex_bolts(data),
            "ISO 4014 hexagon head bolts, generated per-size x "
            "per-length x per-property-class grid.",
        ),
        "hex_nuts.toml": (
            "component",
            _hex_nuts(data),
            "ISO 4032 hexagon nuts, generated per-size x per-bolt-property-class grid.",
        ),
        "plain_washers.toml": (
            "component",
            _plain_washers(data),
            "ISO 7089 plain washers, generated per-size grid.",
        ),
    }

    out: dict[str, str] = {}
    for filename, (kind, rows, comment) in families.items():
        content = render_records_file(
            script="tools/stdlib/gen_fasteners.py",
            source="tools/stdlib/data/iso_fasteners.toml",
            header_comment=f"# {comment}",
            kind=kind,
            rows=rows,
        )
        out[str(OUT_DIR / filename)] = content
    return out


# frob:doc docs/modules/tools.md#stdlib-gen-fasteners
# frob:waive TEST001 reason="CLI entry point; see tests/tools/test_stdlib_gen_drift.py"
# frob:waive TEST005 reason="measured 16.7% branch on 2026-07-19; backfill T-0036"
# frob:waive PERF002 reason="one-shot index/count over a small per-call set"
def main() -> None:
    for path_str, content in generate().items():
        path = Path(path_str)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="ascii")
        print(f"wrote {path.relative_to(REPO_ROOT)} ({content.count(chr(10))} lines)")


if __name__ == "__main__":
    main()
