"""Deterministic TOML record rendering shared by every WO-66 generator
script (D174 sourcing law rule 2: same input tables -> byte-identical
output). One rendering home so every generator writes the exact same
`[[kind]]` shape `regolith.magnetite.stdlib_records.load_toml_records`
expects (a `key` field, an `evidence` table, everything else opaque
data) -- no per-script re-implementation of TOML quoting/float
formatting to drift out of sync.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence

_GENERATED_HEADER = (
    "# GENERATED by `make stdlib-gen` ({script}) -- DO NOT HAND-EDIT.\n"
    "# Source: {source}\n"
)


def _fmt_scalar(value: object) -> str:
    """Render one TOML scalar with a fixed, deterministic formatting rule."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, float):
        # Fixed repr: trims to the shortest round-trippable form Python's
        # own float repr already gives us, which is deterministic across
        # runs (no locale/precision dependence).
        return repr(value)
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(value, Sequence):
        return "[" + ", ".join(_fmt_scalar(v) for v in value) + "]"
    raise TypeError(f"unsupported TOML scalar type: {type(value)!r}")


def render_row(row: Mapping[str, object]) -> str:
    """Render one `[[kind]]` row's key = value lines in sorted-key order
    (determinism: dict insertion order is not a stable generation
    contract, sorted keys are). `evidence` is rendered as an inline
    table last, matching the hand-authored records' own style.
    """
    lines: list[str] = []
    evidence = row.get("evidence")
    for key in sorted(k for k in row if k != "evidence"):
        lines.append(f"{key} = {_fmt_scalar(row[key])}")
    if evidence is not None:
        assert isinstance(evidence, Mapping)
        parts = ", ".join(f"{k} = {_fmt_scalar(v)}" for k, v in evidence.items())
        lines.append(f"evidence = {{ {parts} }}")
    return "\n".join(lines)


def render_records_file(
    *,
    script: str,
    source: str,
    header_comment: str,
    kind: str,
    rows: Sequence[Mapping[str, object]],
) -> str:
    """Render a full committed records file: the generated-file banner,
    a family-level header comment (citation prose), then one `[[kind]]`
    block per row, in the SAME order `rows` is given (callers sort their
    own rows deterministically, e.g. by nominal size, before calling).
    """
    parts = [_GENERATED_HEADER.format(script=script, source=source)]
    if header_comment:
        parts.append(header_comment.rstrip() + "\n")
    for row in rows:
        parts.append(f"[[{kind}]]\n{render_row(row)}\n")
    return "\n".join(parts).rstrip() + "\n"
