# The DX interface (AD-13). `make check` is the single gate; targets
# wrap uv/cargo/maturin so contributors never memorize the underneath.
.DEFAULT_GOAL := help
.PHONY: help install dev check fmt-check test test-rs test-py snapshots \
        schema schema-check fmt lint typecheck coverage bench fuzz build clean guard-core ls kicad-link \
        install-graphite test-graphite

UV ?= uv
CARGO ?= cargo

help: ## List targets
	@grep -E '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) | \
		awk 'BEGIN{FS=":.*?## "}{printf "  %-12s %s\n", $$1, $$2}'

install: ## uv sync + build the extension into the venv (debug) + link system pcbnew
	$(UV) sync
	$(UV) run maturin develop --uv
	@$(MAKE) --no-print-directory kicad-link

# pcbnew is a SWIG binding shipped by the SYSTEM KiCad install (apt),
# never on PyPI, so a plain venv cannot import it. Symlink exactly the
# two files it consists of into the venv (never all of dist-packages --
# that would shadow venv packages). Degrades to a note when KiCad is
# absent; the real-KiCad test tier skips itself via the
# real_kicad_available() gate either way.
kicad-link: ## Link the system KiCad pcbnew module into the venv (no-op if absent)
	@site=$$($(UV) run python -c 'import site; print(site.getsitepackages()[0])'); \
	src=""; \
	for d in /usr/lib/python3/dist-packages /usr/lib/python3*/dist-packages /usr/local/lib/python3*/dist-packages; do \
		if [ -f "$$d/pcbnew.py" ]; then src="$$d"; break; fi; \
	done; \
	if [ -z "$$src" ]; then \
		echo "kicad-link: no system pcbnew found (install KiCad to enable the real-KiCad tier)"; \
	else \
		ln -sf "$$src/pcbnew.py" "$$site/pcbnew.py"; \
		ln -sf "$$src/_pcbnew.so" "$$site/_pcbnew.so"; \
		if $(UV) run python -c 'import pcbnew' >/dev/null 2>&1; then \
			echo "kicad-link: pcbnew linked into the venv from $$src"; \
		else \
			rm -f "$$site/pcbnew.py" "$$site/_pcbnew.so"; \
			echo "kicad-link: system pcbnew at $$src is not importable under the venv python (ABI mismatch); links removed, real-KiCad tier stays gated"; \
		fi; \
	fi

dev: ## Rebuild the extension into the venv on Rust change
	$(UV) run watchexec -e rs -- $(UV) run maturin develop --uv

check: fmt-check lint typecheck guard-core schema-check test-rs test-py test-graphite ## Full gate, cheapest first

fmt-check:
	$(CARGO) fmt --all --check
	$(UV) run ruff format --check .

fmt: ## Format Rust + Python
	$(CARGO) fmt --all
	$(UV) run ruff format .

lint: ## clippy (-D warnings) + ruff lint
	$(CARGO) clippy --workspace --all-targets -- -D warnings
	$(UV) run ruff check .

typecheck: ## astral ty type-check on the Python package
	$(UV) run ty check python/regolith

guard-core: ## Enforce: only compiler.py may import regolith._core (AD-4)
	@bad=$$(grep -rElE '^[[:space:]]*(from[[:space:]]+regolith[[:space:]]+import[[:space:]]+_core|from[[:space:]]+regolith\._core[[:space:]]+import|import[[:space:]]+regolith\._core)' \
		python/regolith --include='*.py' | \
		grep -vE 'python/regolith/compiler\.py$$' || true); \
	if [ -n "$$bad" ]; then \
		echo "AD-4 violation: regolith._core imported outside compiler.py:"; \
		echo "$$bad"; exit 1; \
	fi

test: test-rs test-py ## All tests

test-rs: ## cargo test (workspace)
	$(CARGO) test --workspace

test-py: ## pytest through the real wheel
	$(UV) run pytest

snapshots: ## Review insta snapshots + regenerate the doc-golden (WO-41)
	$(CARGO) insta review
	REGOLITH_UPDATE_GOLDEN=1 $(UV) run pytest tests/golden/test_doc_snapshot.py -q

schema: ## Regenerate _schema/ models from the Rust schemars export (AD-5)
	@tmp=$$(mktemp); \
	$(CARGO) run --quiet -p regolith-api --bin regolith-export-schema > $$tmp; \
	version=$$($(UV) run python -c "import json,sys; print(json.load(open(sys.argv[1]))['schema_version'])" $$tmp); \
	$(UV) run datamodel-codegen \
		--input $$tmp \
		--input-file-type jsonschema \
		--output python/regolith/_schema/models.py \
		--output-model-type pydantic_v2.BaseModel \
		--base-class regolith._schema_base.FrozenModel \
		--target-python-version 3.12 \
		--use-schema-description \
		--field-constraints \
		--use-annotated \
		--disable-timestamp \
		--custom-file-header '# GENERATED by `make schema` (AD-5) -- never hand-edit.' \
		--collapse-root-models; \
	rm -f $$tmp; \
	printf '%s\n' \
		'"""GENERATED by make schema (AD-5) -- never hand-edit."""' \
		'' \
		'from __future__ import annotations' \
		'' \
		'from regolith._schema.models import *  # noqa: F401,F403' \
		'' \
		"SCHEMA_VERSION = $$version" \
		> python/regolith/_schema/__init__.py; \
	$(UV) run ruff check --fix --quiet python/regolith/_schema; \
	$(UV) run ruff format --quiet python/regolith/_schema

schema-check: schema ## CI drift job: regenerate, fail on any diff
	git diff --exit-code python/regolith/_schema/

stdlib-gen: ## Regenerate GENERATED stdlib/ records from tools/stdlib/data (WO-66, D174)
	$(UV) run python -m tools.stdlib.generate_all

# Per-target fuzz time budget (seconds). CI uses ~60s; override for long
# ad-hoc runs, e.g. `FUZZ_TIME=3600 make fuzz`.
FUZZ_TIME ?= 60

coverage: ## Rust + Python coverage (llvm-cov degrades if not installed)
	@if $(CARGO) llvm-cov --version >/dev/null 2>&1; then \
		$(CARGO) llvm-cov --workspace; \
	else \
		echo "SKIP cargo-llvm-cov not installed (cargo install cargo-llvm-cov); Python coverage only"; \
	fi
	$(UV) run coverage run -m pytest && $(UV) run coverage report

bench: ## Criterion benchmarks over the Kestrel corpus (AD-11)
	$(CARGO) bench --workspace

fuzz: ## Fuzz lexer/parser/CBOR ~60s each (needs nightly cargo-fuzz; AD-3)
	@if ! rustup toolchain list 2>/dev/null | grep -q nightly; then \
		echo "SKIP cargo-fuzz needs a nightly toolchain (rustup toolchain install nightly); see fuzz/README.md"; \
		exit 0; \
	fi; \
	if ! cargo +nightly fuzz --version >/dev/null 2>&1; then \
		echo "SKIP cargo-fuzz not installed (cargo install cargo-fuzz); see fuzz/README.md"; \
		exit 0; \
	fi; \
	for t in fuzz_lexer fuzz_parser fuzz_cbor_decode; do \
		echo "== fuzzing $$t for $(FUZZ_TIME)s =="; \
		mkdir -p fuzz/corpus/$$t; \
		case $$t in \
			fuzz_lexer|fuzz_parser) find examples -name '*.hema' -o -name '*.cupr' | \
				xargs -I{} cp -f {} fuzz/corpus/$$t/ 2>/dev/null || true ;; \
		esac; \
		cargo +nightly fuzz run $$t -- -max_total_time=$(FUZZ_TIME) || exit 1; \
	done

build: ## Release wheel
	$(UV) run maturin build --release

install-graphite: ## uv sync apps/graphite (own distribution, editable path dep on this wheel)
	cd apps/graphite && $(UV) sync

test-graphite: ## graphite's own pytest suite (WO-59; wired into `make check`)
	cd apps/graphite && $(UV) run pytest

ls: ## Build the language server binary (release; AD-24, WO-38)
	$(CARGO) build --release -p regolith-ls

editor-check: ## Editor extension: grammar/schema drift + tests (WO-39; own CI job, not in `check`)
	cd editors/vscode && npm ci && npm run check:grammar && npm run check:magnetite-schema && npx tsc -p ./tsconfig.test.json --noEmit && npm test

clean: ## Scrub build artifacts
	$(CARGO) clean
	rm -rf .venv target .pytest_cache .ruff_cache .mypy_cache
