# GENERATED by `make schema` (AD-5) -- never hand-edit.

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import ConfigDict, Field, RootModel

from rockhead._schema_base import FrozenModel


class Model(RootModel[Any]):
    root: Any


class Assumption(FrozenModel):
    """
    An `assume!(expr, basis=)` assumption: an un-discharged claim that `--release` refuses (recorded in the todo/assume/waive ledger).
    """

    basis: Annotated[str, Field(description="The stated basis for the assumption.")]
    expr: Annotated[str, Field(description="The assumed expression, as text.")]


class Cause2(StrEnum):
    dfm = "dfm"


class Cause1(FrozenModel):
    """
    A DFM rule pinned it (`dfm(sheet.min_bend_radius)`).
    """

    cause: Cause2
    ref: str


class Cause4(StrEnum):
    drc = "drc"


class Cause3(FrozenModel):
    """
    A DRC rule pinned it (`drc(jlc_2l.current_capacity)`).
    """

    cause: Cause4
    ref: str


class Cause6(StrEnum):
    obligation = "obligation"


class Cause5(FrozenModel):
    """
    An obligation determined it (`obligation(vdd_core.droop)`).
    """

    cause: Cause6
    ref: str


class Cause8(StrEnum):
    budget = "budget"


class Cause7(FrozenModel):
    """
    A budget allocation set it (`budget(mesh_alignment)`).
    """

    cause: Cause8
    ref: str


class Cause10(StrEnum):
    topology = "topology"


class Cause9(FrozenModel):
    """
    A topology/structure boundary pinned it.
    """

    cause: Cause10
    ref: str


class Cause12(StrEnum):
    planner = "planner"


class Cause11(FrozenModel):
    """
    A planner produced it.
    """

    cause: Cause12
    ref: str


class Form(StrEnum):
    comparison = "comparison"


class ClaimForm1(FrozenModel):
    """
    A scalar comparison (`stress < limit`, `k within [lo, hi]`).
    """

    form: Form
    lhs: Annotated[
        str,
        Field(description="The quantity expression (kept as text; parsed in WO-05)."),
    ]
    op: Annotated[
        str, Field(description="The comparator/containment (`<`, `within`, ...).")
    ]
    rhs: Annotated[str, Field(description="The bound expression.")]


class Form1(StrEnum):
    peak = "peak"


class Form2(StrEnum):
    settles = "settles"


class Form3(StrEnum):
    overshoot = "overshoot"


class ClaimForm4(FrozenModel):
    """
    `overshoot(x, after e)`.
    """

    event: Annotated[str, Field(description="The anchoring event.")]
    form: Form3
    signal: Annotated[str, Field(description="The signal expression.")]


class Form4(StrEnum):
    rms = "rms"


class ClaimForm5(FrozenModel):
    """
    `rms(x, band=[f1, f2])`.
    """

    band: Annotated[str, Field(description="The frequency band, as text.")]
    form: Form4
    signal: Annotated[str, Field(description="The signal expression.")]


class Form5(StrEnum):
    stays_within = "stays_within"


class ClaimForm6(FrozenModel):
    """
    `stays_within(x, mask)`.
    """

    form: Form5
    mask: Annotated[str, Field(description="The hash-pinned mask reference.")]
    signal: Annotated[str, Field(description="The signal expression.")]


class Material(RootModel[list[str]]):
    root: Annotated[list[str], Field(max_length=2, min_length=2)]


class Given(FrozenModel):
    """
    The `given:` context an obligation is evaluated under: the pinned facts (materials, loads, backing evidence) the discharge assumes.
    """

    backing: Annotated[
        list[str], Field(description="Backing evidence references the given relies on.")
    ]
    loads: Annotated[
        list[str], Field(description="Applied loads/environment, as text expressions.")
    ]
    materials: Annotated[
        list[Material],
        Field(description="Pinned material/component records (name -> content hash)."),
    ]


class ImplRecord(FrozenModel):
    """
    A harness impl record for a signature (data only; the code lives in the Python harness).
    """

    cost: Annotated[int, Field(description="Relative cost hint for scheduling.", ge=0)]
    domain: Annotated[
        list[str], Field(description="The validity domain this impl covers.")
    ]
    error_model: Annotated[
        str, Field(description="The error-model tag (how `eps` is derived).")
    ]
    name: Annotated[str, Field(description="The impl's name (the discharge model id).")]
    signature: Annotated[str, Field(description="The signature this implements.")]


class LedgerEntry1(FrozenModel):
    """
    A `todo!` placeholder.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    todo: str


class LedgerEntry2(FrozenModel):
    """
    An `assume!` assumption.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    assume: str


class LedgerEntry3(FrozenModel):
    """
    An unwaived indeterminate discharge.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    indeterminate: str


class Input(RootModel[list[str]]):
    root: Annotated[list[str], Field(max_length=2, min_length=2)]


class Output(RootModel[list[str]]):
    root: Annotated[list[str], Field(max_length=2, min_length=2)]


class Signature(FrozenModel):
    """
    A physics-model signature: a typed input/output contract.
    """

    domain: Annotated[
        list[str], Field(description="Validity domain tags (`clamped`, `linear`).")
    ]
    inputs: Annotated[
        list[Input],
        Field(description="Input port names -> their quantity type (as text)."),
    ]
    name: Annotated[str, Field(description="Signature name (`bolted_joint_state`).")]
    outputs: Annotated[
        list[Output], Field(description="Output port names -> their quantity type.")
    ]


class SignatureRegistry(FrozenModel):
    """
    The signature + impl registry the orchestrator matches discharge against.
    """

    impls: list[ImplRecord]
    signatures: dict[str, Signature]


class SnapshotRecord(FrozenModel):
    """
    One committed `EntityDb` scope's content-addressed snapshot, keyed by its scope name -- the WO-19 lowering pipeline emits one of these per scope (`docs/design-log/2026-07-04-cycle-11.md`).
    """

    hash: Annotated[
        str,
        Field(description="The scope's `EntityDb::snapshot_hash()` content address."),
    ]
    scope: Annotated[
        str,
        Field(description="The scope this snapshot belongs to (a declaration name)."),
    ]


class Status1(StrEnum):
    """
    The claim holds with margin after the model's error.
    """

    discharged = "discharged"


class Status2(StrEnum):
    """
    The claim provably fails at its worst corner.
    """

    violated = "violated"


class Status3(StrEnum):
    """
    No adequate model, coverage, or trust; neither proven nor disproven (distinct from violated).
    """

    indeterminate = "indeterminate"


class SweepDomain(FrozenModel):
    """
    A sweep domain an obligation is instantiated over (one obligation per domain point; the obligation carries its own domain).
    """

    axis: Annotated[str, Field(description="The swept axis name.")]
    domain: Annotated[
        str,
        Field(
            description="The domain description (interval or discrete set, as text)."
        ),
    ]


class Unit(FrozenModel):
    pass


class Waiver(FrozenModel):
    """
    A source-declared waiver: it matches some set of claims/rules and carries a basis (and optionally evidence, making it a deviation).
    """

    basis: Annotated[str, Field(description="The stated basis.")]
    evidence: Annotated[
        str | None,
        Field(
            description="Backing evidence reference, if this is a deviation (vs a bare waiver)."
        ),
    ] = None
    expires: Annotated[str | None, Field(description="Expiry marker, if any.")] = None
    scope: Annotated[
        str,
        Field(
            description="The scope pattern the waiver matches (claim/rule selector text)."
        ),
    ]


class Window1(FrozenModel):
    """
    `during <event-or-config-domain>`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    during: str


class WithinAfter(FrozenModel):
    duration: Annotated[
        str, Field(description="The bounding duration (source text; typed in qty).")
    ]
    event: Annotated[str, Field(description="The anchoring event.")]


class Window2(FrozenModel):
    """
    `within <duration> after <event>`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    within_after: WithinAfter


class Window3(FrozenModel):
    """
    `until <event>`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    until: str


class ClaimForm2(FrozenModel):
    """
    `peak(x, during w)`.
    """

    form: Form1
    signal: Annotated[str, Field(description="The signal expression.")]
    window: Annotated[
        Window1 | Window2 | Window3, Field(description="The evaluation window.")
    ]


class ClaimForm3(FrozenModel):
    """
    `settles(x, to=tol, within d after e)`.
    """

    form: Form2
    signal: Annotated[str, Field(description="The signal expression.")]
    tol: Annotated[str, Field(description="Settling tolerance text.")]
    window: Annotated[
        Window1 | Window2 | Window3, Field(description="The bounding window.")
    ]


class Evidence(FrozenModel):
    """
    The evidence produced by discharging one obligation.
    """

    cost: Annotated[int, Field(description="Relative cost incurred.", ge=0)]
    coverage_bits: Annotated[
        int,
        Field(
            description="Coverage fraction for swept obligations (`1.0` = full), bits.",
            ge=0,
        ),
    ]
    eps_bits: Annotated[int, Field(description="The model error `eps`'s bits.", ge=0)]
    hash: Annotated[
        str, Field(description="Content hash of this evidence (cache key component).")
    ]
    margin_bits: Annotated[
        int,
        Field(
            description="The margin after error (`limit - (value + eps)`)'s bits.", ge=0
        ),
    ]
    model_id: Annotated[
        str, Field(description="The discharge model id that produced this.")
    ]
    status: Annotated[
        Status1 | Status2 | Status3, Field(description="The discharge status.")
    ]
    value_bits: Annotated[
        int,
        Field(
            description="The computed value's bits (f64 as bits for exact serialization).",
            ge=0,
        ),
    ]


class EvidenceCache(FrozenModel):
    """
    A cache of evidence keyed on (subject, contract, registry versions), so a second run is a hit.
    """

    entries: dict[str, Evidence]


class LedgerEntry4(FrozenModel):
    """
    A waiver that matched and shadowed a claim/rule.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    waived: Waiver


class Qty(FrozenModel):
    magnitude: float
    unit: Unit


class Resolution(FrozenModel):
    """
    A resolved value with its cause: one lockfile row. There is no way to build one without a `Cause` (INV-21).
    """

    cause: Annotated[
        Cause1 | Cause3 | Cause5 | Cause7 | Cause9 | Cause11,
        Field(
            description="Why a value resolved to what it did. Mandatory on every resolution (INV-21). The variants mirror the resolving mechanisms."
        ),
    ]
    value: Qty


class WaiveLedger(FrozenModel):
    """
    The build's todo/assume/waive ledger.
    """

    entries: list[LedgerEntry1 | LedgerEntry2 | LedgerEntry3 | LedgerEntry4]


class Claim(FrozenModel):
    """
    A single named claim inside a `require` group.
    """

    forall: Annotated[
        list[str],
        Field(description="`forall <cfg>` config axes the claim quantifies over."),
    ]
    form: Annotated[
        ClaimForm1 | ClaimForm2 | ClaimForm3 | ClaimForm4 | ClaimForm5 | ClaimForm6,
        Field(description="The claim form."),
    ]
    hints: Annotated[list[str], Field(description="Discharge-model hints (`@hint`).")]
    model_pin: Annotated[
        str | None, Field(description="A `model=` pin selecting the discharge model.")
    ] = None
    name: Annotated[str | None, Field(description="Optional claim name.")] = None
    scatter_factor: Annotated[
        float | None, Field(description="Scatter factor (`scatter_factor=`), if any.")
    ] = None
    sf: Annotated[float | None, Field(description="Safety factor (`sf=`), if any.")] = (
        None
    )
    trust_floor: Annotated[
        str | None,
        Field(description="Minimum required evidence trust tier (`trust: >= tier`)."),
    ] = None


class Obligation(FrozenModel):
    """
    A self-contained verification obligation.
    """

    claim: Annotated[Claim, Field(description="The claim being discharged.")]
    given: Annotated[Given, Field(description="The pinned evaluation context.")]
    hints: Annotated[
        list[str], Field(description="Discharge hints carried from the claim/symmetry.")
    ]
    subject_ref: Annotated[
        str,
        Field(
            description="Content-addressed reference to the subject (entity/snapshot hash)."
        ),
    ]
    sweep: Annotated[
        SweepDomain | None,
        Field(description="The sweep domain this obligation instance carries, if any."),
    ] = None
