//! Typed AST: zero-cost view structs over the CST (rust-analyzer
//! pattern, AD-3). In the built system these are GENERATED by an xtask
//! from an ungrammar file; the hand-written views below are the
//! scaffold seed and document the shape the codegen must produce.
//!
//! Substrate reference: `docs/mech/02`, `docs/elec/07`. Each view wraps
//! a [`SyntaxNode`] of a specific [`SyntaxKind`] and exposes typed
//! child accessors; trivia is skipped at this layer.

use crate::cst::SyntaxNode;
use crate::syntax_kind::SyntaxKind;

/// A typed view over a CST node of a known kind. Cheap: holds one
/// `SyntaxNode` (an `Rc`-backed handle).
pub trait AstNode {
    /// True if a node of this `kind` can be viewed as `Self`.
    fn can_cast(kind: SyntaxKind) -> bool
    where
        Self: Sized;
    /// Wrap `node` if its kind matches, else `None`.
    fn cast(node: SyntaxNode) -> Option<Self>
    where
        Self: Sized;
    /// The underlying CST node.
    fn syntax(&self) -> &SyntaxNode;
}

/// Declare a typed AST view struct over a single [`SyntaxKind`]. Keeps
/// the boilerplate identical across views (the codegen target).
macro_rules! ast_node {
    ($(#[$m:meta])* $name:ident => $kind:ident) => {
        $(#[$m])*
        #[derive(Debug, Clone)]
        pub struct $name {
            syntax: SyntaxNode,
        }
        impl AstNode for $name {
            fn can_cast(kind: SyntaxKind) -> bool {
                kind == SyntaxKind::$kind
            }
            fn cast(node: SyntaxNode) -> Option<Self> {
                if node.kind() == SyntaxKind::$kind {
                    Some($name { syntax: node })
                } else {
                    None
                }
            }
            fn syntax(&self) -> &SyntaxNode {
                &self.syntax
            }
        }
    };
}

ast_node!(
    /// The file root: imports followed by top-level declarations.
    File => File
);
ast_node!(
    /// An `import` statement.
    ImportStmt => ImportStmt
);
ast_node!(
    /// A top-level declaration (`part`, `interface`, `system`, ...).
    Decl => Decl
);
ast_node!(
    /// A `key: value` field.
    Field => Field
);
ast_node!(
    /// A `name = Ctor(args)` construction statement.
    CtorStmt => CtorStmt
);
ast_node!(
    /// A `require <Group>:` claim group.
    RequireClaim => RequireClaim
);

impl File {
    /// The import statements at the head of the file.
    #[must_use]
    pub fn imports(&self) -> Vec<ImportStmt> {
        todo!("STUB WO-05: filter children by ImportStmt kind, in source order")
    }

    /// The top-level declarations of the file.
    #[must_use]
    pub fn decls(&self) -> Vec<Decl> {
        todo!("STUB WO-05: filter children by Decl kind, in source order")
    }
}

#[cfg(test)]
mod tests {
    use super::{AstNode, Decl, File};
    use crate::syntax_kind::SyntaxKind;

    #[test]
    fn can_cast_matches_kind() {
        assert!(File::can_cast(SyntaxKind::File));
        assert!(!File::can_cast(SyntaxKind::Decl));
        assert!(Decl::can_cast(SyntaxKind::Decl));
    }
}
