"""`make codes` driver (WO-131/D247): regenerate the GENERATED Python
diagnostic-code module from the Rust ``regolith-export-codes`` export.

Mirrors ``make schema``'s single-sourcing precedent exactly: Rust
(``crates/regolith-diag/src/code.rs`` + ``explain.rs``) is the ONE home;
this script only turns its JSON export into a Python data module. Never
hand-edit the output -- ``make codes-check`` diffs it in CI.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

# frob:doc docs/modules/tools.md#codegen-generate-codes
REPO_ROOT = Path(__file__).resolve().parents[2]
# frob:doc docs/modules/tools.md#codegen-generate-codes
OUT_DIR = REPO_ROOT / "python" / "regolith" / "_codes"
# frob:doc docs/modules/tools.md#codegen-generate-codes
OUT_FILE = OUT_DIR / "__init__.py"

# frob:doc docs/modules/tools.md#codegen-generate-codes
HEADER = '''"""GENERATED by `make codes` (D247/WO-131) -- never hand-edit.

Single-sourced from `crates/regolith-diag/src/code.rs` + `explain.rs`
(the ONE registry, D247.1) via `regolith-export-codes`. A Python
failure kind that does not name one of these constants is a build
error, not a bare string (D247.1) -- see `tools/health/diag_codes.py`
for the sweep that enforces it.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class CodeEntry(BaseModel):
    """One diagnostic code's rendered form + explain content."""

    model_config = ConfigDict(frozen=True)

    code: str
    symbol: str
    family: str
    meaning: str
    why: str
    fix: str
    example: str | None
    authored: bool
'''


def _py_repr(value: object) -> str:
    """A stable, ASCII-safe Python literal for a generated constant."""
    return repr(value)


# frob:doc docs/modules/tools.md#codegen-generate-codes
def generate(rows: list[dict]) -> str:
    """Render the generated module body from the export rows."""
    lines = [HEADER, ""]
    lines.append("# One CodeEntry per registered code, in registry order.")
    lines.append("ALL: tuple[CodeEntry, ...] = (")
    for row in rows:
        lines.append(
            "    CodeEntry("
            f"code={_py_repr(row['code'])}, "
            f"symbol={_py_repr(row['symbol'])}, "
            f"family={_py_repr(row['family'])}, "
            f"meaning={_py_repr(row['meaning'])}, "
            f"why={_py_repr(row['why'])}, "
            f"fix={_py_repr(row['fix'])}, "
            f"example={_py_repr(row['example'])}, "
            f"authored={_py_repr(row['authored'])}"
            "),"
        )
    lines.append(")")
    lines.append("")
    lines.append('# name -> "E0901"-style code string, one constant per symbol')
    lines.append("# (the Python-side raise sites import THESE, never a literal).")
    for row in rows:
        lines.append(f"{row['symbol']} = {_py_repr(row['code'])}")
    lines.append("")
    lines.append("BY_CODE: dict[str, CodeEntry] = {e.code: e for e in ALL}")
    lines.append("BY_SYMBOL: dict[str, CodeEntry] = {e.symbol: e for e in ALL}")
    lines.append("")
    return "\n".join(lines) + "\n"


# frob:doc docs/modules/tools.md#codegen-generate-codes
# frob:waive TEST001 reason="CLI entry pt; see make codes / generate() test"
def main() -> int:
    """Regenerate `python/regolith/_codes/__init__.py`; return exit code."""
    proc = subprocess.run(
        [
            "cargo",
            "run",
            "--quiet",
            "-p",
            "regolith-api",
            "--bin",
            "regolith-export-codes",
        ],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr)
        return proc.returncode
    rows = json.loads(proc.stdout)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(generate(rows))
    return 0


if __name__ == "__main__":
    sys.exit(main())
