//! Typed AST: zero-cost view structs over the CST (rust-analyzer
//! pattern, AD-3). In the built system these are GENERATED by an xtask
//! from an ungrammar file; the hand-written views below are the
//! scaffold seed and document the shape the codegen must produce.
//!
//! Regolith reference: `docs/spec/hematite/02`, `docs/spec/cuprite/07`. Each view wraps
//! a [`SyntaxNode`] of a specific [`SyntaxKind`] and exposes typed
//! child accessors; trivia is skipped at this layer.

use crate::cst::SyntaxNode;
use crate::syntax_kind::SyntaxKind;

/// A typed view over a CST node of a known kind. Cheap: holds one
/// `SyntaxNode` (an `Rc`-backed handle).
// frob:doc docs/modules/regolith-syntax.md#ast
pub trait AstNode {
    /// True if a node of this `kind` can be viewed as `Self`.
    fn can_cast(kind: SyntaxKind) -> bool
    where
        Self: Sized;
    /// Wrap `node` if its kind matches, else `None`.
    fn cast(node: SyntaxNode) -> Option<Self>
    where
        Self: Sized;
    /// The underlying CST node.
    fn syntax(&self) -> &SyntaxNode;
}

/// Declare a typed AST view struct over a single [`SyntaxKind`]. Keeps
/// the boilerplate identical across views (the codegen target).
macro_rules! ast_node {
    ($(#[$m:meta])* $name:ident => $kind:ident) => {
        $(#[$m])*
        #[derive(Debug, Clone)]
        pub struct $name {
            syntax: SyntaxNode,
        }
        impl AstNode for $name {
            fn can_cast(kind: SyntaxKind) -> bool {
                kind == SyntaxKind::$kind
            }
            fn cast(node: SyntaxNode) -> Option<Self> {
                if node.kind() == SyntaxKind::$kind {
                    Some($name { syntax: node })
                } else {
                    None
                }
            }
            fn syntax(&self) -> &SyntaxNode {
                &self.syntax
            }
        }
    };
}

ast_node!(
    /// The file root: imports followed by top-level declarations.
    File => File
);
ast_node!(
    /// An `import` statement.
    ImportStmt => ImportStmt
);
ast_node!(
    /// A top-level declaration (`part`, `interface`, `system`, ...).
    Decl => Decl
);
ast_node!(
    /// A `key: value` field.
    Field => Field
);
ast_node!(
    /// A `name = Ctor(args)` construction statement.
    CtorStmt => CtorStmt
);
ast_node!(
    /// A `require <Group>:` claim group.
    RequireClaim => RequireClaim
);
ast_node!(
    /// A `compute <name>: <quantity kind> over <index domain>` claim
    /// line (WO-33 D98).
    ComputeField => ComputeField
);
ast_node!(
    /// A `then [label] [on <region>]:` scope.
    ThenScope => ThenScope
);
ast_node!(
    /// A `budget ...:` statement.
    BudgetStmt => BudgetStmt
);
ast_node!(
    /// A `waive ...:` block.
    WaiveBlock => WaiveBlock
);
ast_node!(
    /// A `policy:` block.
    PolicyBlock => PolicyBlock
);
ast_node!(
    /// A `locked:` block.
    LockedBlock => LockedBlock
);
ast_node!(
    /// A binary expression (comparison, `+ - * /`).
    BinExpr => BinExpr
);
ast_node!(
    /// A unary expression: `-x`, or a bound-only claim comparator
    /// (`>= certified`) with an implicit subject.
    UnaryExpr => UnaryExpr
);
ast_node!(
    /// A parenthesized expression.
    ParenExpr => ParenExpr
);
ast_node!(
    /// A call expression: callee (`NameRef`/`Path`) plus an `ArgList`.
    CallExpr => CallExpr
);
ast_node!(
    /// A call's argument list.
    ArgList => ArgList
);
ast_node!(
    /// A number literal with an adjacent unit (`5 mm`, `1 V`).
    QuantityLit => QuantityLit
);
ast_node!(
    /// A single dotted-path-free name reference.
    NameRef => NameRef
);
ast_node!(
    /// A dotted path reference (`a.b.c`).
    Path => Path
);
ast_node!(
    /// A `[a, b]` closed real interval.
    IntervalExpr => IntervalExpr
);
ast_node!(
    /// A `[i .. j]` half-open index range.
    RangeExpr => RangeExpr
);
ast_node!(
    /// A value source wrapper (`default`/`derived`/`free`/`allocated`,
    /// or `in [...]`).
    ValueSource => ValueSource
);
ast_node!(
    /// A bare cause keyword leaf (`default`, `derived`, `free`,
    /// `allocated`).
    CauseValue => CauseValue
);
ast_node!(
    /// A `+- N %` tolerance suffix on a value.
    ToleranceExpr => ToleranceExpr
);
ast_node!(
    /// A `during <expr>` clause.
    DuringClause => DuringClause
);
ast_node!(
    /// A use-site generic instantiation (`TappedHole<M3>`): a head
    /// name plus a [`GenericArgs`] list (INV-11 use site).
    InstExpr => InstExpr
);
ast_node!(
    /// A use-site generic-argument list (`<M3>`, `<3, 8>`).
    GenericArgs => GenericArgs
);
ast_node!(
    /// A declaration-header generic-parameter list (`<screw: thread,
    /// n: int>`).
    GenericParams => GenericParams
);

ast_node!(
    /// A single-line ownership statement (`bind`/`modify <entity>`).
    OwnershipStmt => OwnershipStmt
);
ast_node!(
    /// A single-line region statement (`region`/`keepout`/`route ...`).
    RegionStmt => RegionStmt
);
ast_node!(
    /// A single-line symmetry statement (`pattern`/`break`/`any`/
    /// `symmetric`/`mirror`/`flip ...`).
    SymmetryStmt => SymmetryStmt
);
ast_node!(
    /// A single-line query statement (`feature <name>` / `refer <name>`).
    QueryStmt => QueryStmt
);
ast_node!(
    /// A clocked `on <event>:` behavioral body (cuprite/03 sec. 1): the
    /// header names the event whose clock is the body's domain; the
    /// nested stmt-block holds `<=` register deltas and `=` combinational
    /// relations (INV-16 converter graph).
    OnBlock => OnBlock
);
ast_node!(
    /// A non-blocking register assignment `<lhs> <= <expr>` (cuprite/03
    /// sec. 1a): a ZOH delta committing at instant end.
    RegAssign => RegAssign
);
ast_node!(
    /// A `workloads:` block (cuprite/05 sec. 1): the computer's declared
    /// boundary demand, one [`WorkloadStmt`] per line.
    WorkloadsBlock => WorkloadsBlock
);
ast_node!(
    /// One `<name>: <kind>(<params>) [realizes <intent>...]` workload
    /// line (cuprite/05 sec. 1), `<kind>` in `{loop, stream, event,
    /// batch}`.
    WorkloadStmt => WorkloadStmt
);
ast_node!(
    /// A `realizes <intent>[, <intent>...]` statement (cuprite/05 sec.
    /// 1a; EOPEN-15): ties a workload to the compute intents it serves.
    RealizesStmt => RealizesStmt
);
ast_node!(
    /// A `capability:` block in a `process` decl body (hematite/02
    /// sec. 10): the provider-envelope table, one [`Field`] per line.
    CapabilityBlock => CapabilityBlock
);
ast_node!(
    /// A `dfm:`/`drc:`/`erc:` rule-pack block in a `process` decl body
    /// (WO-28): the family word leads; the body is [`RuleDecl`]s.
    RulePackBlock => RulePackBlock
);
ast_node!(
    /// One `rule <name>:` declaration (hematite/04 sec. I5): the
    /// citable rule identity plus its body fields.
    RuleDecl => RuleDecl
);
ast_node!(
    /// A `forall <var> in <query>` rule match domain (the settled
    /// claim quantifier over an entity query).
    ForallClause => ForallClause
);
ast_node!(
    /// A `forall <var> in <domain>:` BLOCK claim inside a `require`
    /// group (WO-68): header (var + domain) plus a nested body of
    /// ordinary named claim [`Field`]s.
    ForallSweepClaim => ForallSweepClaim
);
ast_node!(
    /// A `resolves: <field> from free` eager-resolver marker
    /// (regolith/03: cause `dfm(<pack>.<rule>)`/`drc(<pack>.<rule>)`).
    ResolvesClause => ResolvesClause
);
ast_node!(
    /// An `expect:` in-pack fixture block, one [`ExpectCase`] per line.
    ExpectBlock => ExpectBlock
);
ast_node!(
    /// One `pass:`/`fail:` fixture line inside an [`ExpectBlock`].
    ExpectCase => ExpectCase
);

ast_node!(
    /// A top-level `medium <name>: <phase>` declaration (fluorite/02
    /// sec. 1): a fluid identity + its `props: registry(...)` records.
    MediumDecl => MediumDecl
);
ast_node!(
    /// A top-level `flownet <name>(medium=<ref>):` declaration
    /// (fluorite/02 sec. 4): the relational join over the AD-23 net core.
    FlownetDecl => FlownetDecl
);
ast_node!(
    /// A top-level `require <Group>:` claim group in a `.fluo` file
    /// (fluorite/02 sec. 6).
    RequireDecl => RequireDecl
);
ast_node!(
    /// A flownet `edges:` block (fluorite/02 sec. 4), one
    /// [`EdgeStmt`] per declared edge.
    EdgesBlock => EdgesBlock
);
ast_node!(
    /// One `<name>: <constructor>(...) (<a> -> <b>)` edge line
    /// (fluorite/02 sec. 4).
    EdgeStmt => EdgeStmt
);
ast_node!(
    /// A flownet `states:` block (fluorite/02 sec. 4), one
    /// [`StateStmt`] per line.
    StatesBlock => StatesBlock
);
ast_node!(
    /// One `states:` member line (fluorite/02 sec. 4/5): an
    /// edge-parameter domain, a net-level `state <name> in {...}`
    /// declaration, or a commanded `event` line.
    StateStmt => StateStmt
);
ast_node!(
    /// The arrow-shaped positive-sense naming pair trailing an
    /// [`EdgeStmt`]'s constructor call: `(<a> -> <b>)` (fluorite/02
    /// sec. 4; a NAMING convention, not a flow-direction assertion).
    SensePair => SensePair
);
ast_node!(
    /// A claim's trailing `, model=<ident>` rung-5 pin (`regolith/12`
    /// sec. 2 rung 5; WO-80 deliverable 1): forces the discharge model,
    /// margin math unchanged -- "a forced model that cannot close the
    /// margin yields indeterminate, not a pass."
    ModelPin => ModelPin
);
ast_node!(
    /// A brace-delimited discrete domain set: `{a, b, c}` (fluorite/02
    /// sec. 4/5).
    DomainSet => DomainSet
);

ast_node!(
    /// A top-level `harness <name>:` declaration (D99, WO-34 deliverable
    /// 1): the wiring harness, body holds [`RunStmt`]/[`EnvironmentStmt`]
    /// lines.
    HarnessDecl => HarnessDecl
);
ast_node!(
    /// One `run <name>: from <ep> to <ep>` line (D99): the header is
    /// recorded whole (endpoints not decomposed at this layer); the body
    /// holds [`AlongClause`]/[`BundleClause`] lines.
    RunStmt => RunStmt
);
ast_node!(
    /// A run's routed-PATH line: `along <structural refs>` or the
    /// planner-routed marker (`along route: free` / bare `route: free`),
    /// recorded whole -- see the [`SyntaxKind::AlongClause`] doc comment
    /// for the documented D99 example-vs-prose ambiguity this resolves.
    AlongClause => AlongClause
);
ast_node!(
    /// A run's `bundle <group>` co-routing line (D99).
    BundleClause => BundleClause
);
ast_node!(
    /// A top-level `environment <name>: [<lo>, <hi>]` connector
    /// environment-class declaration inside a [`HarnessDecl`] body (D99).
    EnvironmentStmt => EnvironmentStmt
);

ast_node!(
    /// A top-level `site <name>:` declaration (calcite/02 sec. 1):
    /// declared civil boundary truth + soil records.
    SiteDecl => SiteDecl
);
ast_node!(
    /// A top-level `grid <name>: <idents> spacing <qty>` declaration
    /// (calcite/02 sec. 1): a datum family.
    GridDecl => GridDecl
);
ast_node!(
    /// A top-level `level <name>: <qty>` declaration (calcite/02
    /// sec. 1): a datum.
    LevelDecl => LevelDecl
);
ast_node!(
    /// A top-level `space <name>:` declaration (calcite/02 sec. 2):
    /// the architectural program unit.
    SpaceDecl => SpaceDecl
);
ast_node!(
    /// A top-level `adjacent <a>, <b>: <predicate>` declaration
    /// (calcite/02 sec. 2): an adjacency contract between spaces.
    AdjacentDecl => AdjacentDecl
);
ast_node!(
    /// A top-level `access:` block (calcite/02 sec. 2): opening
    /// declarations, whose lines are typed [`EdgeStmt`]s (same shape as
    /// a flownet `edges:` block, hoisted directly to decl-body
    /// position -- NO DUPLICATION).
    AccessDecl => AccessDecl
);
ast_node!(
    /// A top-level `circulation <name>:` declaration (calcite/02
    /// sec. 3): the egress net (AD-23 discipline #3, D139).
    CirculationDecl => CirculationDecl
);
ast_node!(
    /// A top-level `member <name>: <role>` declaration (calcite/02
    /// sec. 4): a structural element.
    MemberDecl => MemberDecl
);
ast_node!(
    /// A top-level `structure <name>:` declaration (calcite/02 sec. 6):
    /// the load-path net (AD-23 discipline #4, D139), body holds
    /// `support:`/`members:` fields plus the typed [`EdgesBlock`]
    /// under `transfers:`.
    StructureDecl => StructureDecl
);
ast_node!(
    /// A top-level `loads:` block (calcite/02 sec. 7): load case
    /// magnitudes.
    LoadsDecl => LoadsDecl
);
// NOTE: no `AssemblyDecl` type here -- `assembly` is a settled
// cross-track homonym with hematite's system artifact and stays the
// generic `Decl` for both tracks (see the parser dispatch's comment).

ast_node!(
    /// A top-level `power <name>:` declaration (charter
    /// toolchain/43-power-distribution.md sec. 1, WO-132, D248/AD-42):
    /// the facility power net over the AD-23 net core. Body holds
    /// `sources:`/`buses:`/`ties:`/`loads:` fields plus the typed
    /// [`EdgesBlock`] under `feeders:`.
    PowerDecl => PowerDecl
);

ast_node!(
    /// A top-level `test <name>:` declaration (WO-83; charter
    /// toolchain/37-design-testing.md, D190): an author-written design
    /// test. Body holds a [`ScenarioBlock`] and a [`TestExpectBlock`].
    TestDecl => TestDecl
);
ast_node!(
    /// The `scenario:` block of a [`TestDecl`]: config-axis selections,
    /// rung-1/2 bindings, seed/budget, realized-input refs -- all the
    /// shared generic statement grammar (the expert ladder IS the
    /// scenario vocabulary, regolith/12).
    ScenarioBlock => ScenarioBlock
);
ast_node!(
    /// The `expect:` block of a [`TestDecl`]: one [`TestExpectCase`]
    /// per line, the five design-test expectation forms (charter 37
    /// sec. 1).
    TestExpectBlock => TestExpectBlock
);
ast_node!(
    /// One expectation line inside a [`TestExpectBlock`]: `diagnostic`/
    /// `verdict`/`value`/`count`/`winner`, header-rest recorded whole
    /// (mirrors [`AlongClause`]) and split by the typed accessors below.
    TestExpectCase => TestExpectCase
);

/// The leading verb token text of a single-line statement node (the
/// first non-trivia `Ident`): `bind`, `route`, `pattern`, ... . The one
/// accessor the three statement views share for verb dispatch.
fn verb_text(node: &SyntaxNode) -> Option<String> {
    node.children_with_tokens()
        .filter_map(rowan::NodeOrToken::into_token)
        .find(|t| t.kind() == SyntaxKind::Ident)
        .map(|t| t.text().to_string())
}

/// Every `Ident` token text on a single-line statement node, in source
/// order (verb first, then argument names/keywords like `into`, `join`,
/// `circular`). Lowering reads positional arguments off this list.
fn ident_texts(node: &SyntaxNode) -> Vec<String> {
    node.children_with_tokens()
        .filter_map(rowan::NodeOrToken::into_token)
        .filter(|t| t.kind() == SyntaxKind::Ident)
        .map(|t| t.text().to_string())
        .collect()
}

/// The first `Number` token text on a single-line statement node, if any
/// (`pattern ring circular 4` -> `"4"`).
fn first_number_text(node: &SyntaxNode) -> Option<String> {
    node.children_with_tokens()
        .filter_map(rowan::NodeOrToken::into_token)
        .find(|t| t.kind() == SyntaxKind::Number)
        .map(|t| t.text().to_string())
}

impl OwnershipStmt {
    /// The leading verb (`bind` or `modify`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn verb(&self) -> Option<String> {
        verb_text(&self.syntax)
    }

    /// Every identifier on the line (verb first, then the entity name(s)).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn idents(&self) -> Vec<String> {
        ident_texts(&self.syntax)
    }
}

impl RegionStmt {
    /// The leading verb (`region`, `keepout`, or `route`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn verb(&self) -> Option<String> {
        verb_text(&self.syntax)
    }

    /// Every identifier on the line (verb first, then name / `into` /
    /// `join` / policy word / target region).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn idents(&self) -> Vec<String> {
        ident_texts(&self.syntax)
    }
}

impl SymmetryStmt {
    /// The leading verb (`pattern`, `break`, `any`, `symmetric`,
    /// `mirror`, `flip`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn verb(&self) -> Option<String> {
        verb_text(&self.syntax)
    }

    /// Every identifier on the line (verb first, then name / kind word).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn idents(&self) -> Vec<String> {
        ident_texts(&self.syntax)
    }

    /// The first numeric argument (`pattern ring circular 4` -> `Some(4)`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn order(&self) -> Option<u32> {
        first_number_text(&self.syntax).and_then(|t| t.parse().ok())
    }
}

impl QueryStmt {
    /// The leading verb (`feature` declares a scope entity; `refer`
    /// resolves a query against the scope snapshot).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn verb(&self) -> Option<String> {
        verb_text(&self.syntax)
    }

    /// Every identifier on the line (verb first, then the entity/query
    /// name). Lowering reads the target name off index 1.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn idents(&self) -> Vec<String> {
        ident_texts(&self.syntax)
    }
}

impl OnBlock {
    /// The clock domain the body fires in: the root identifier of the
    /// event on the header line (`on ctrl_clk.rise:` -> `ctrl_clk`). The
    /// first `Ident` after the leading `on` keyword.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn clock(&self) -> Option<String> {
        self.syntax
            .children_with_tokens()
            .filter_map(rowan::NodeOrToken::into_token)
            .skip_while(|t| t.kind() != SyntaxKind::OnKw)
            .find(|t| t.kind() == SyntaxKind::Ident)
            .map(|t| t.text().to_string())
    }
}

impl RegAssign {
    /// The assignment's target signal name (dotted paths joined with `.`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn name(&self) -> String {
        name_path_text(&self.syntax)
    }

    /// The assignment's right-hand value node (see [`Field::value`]).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn value(&self) -> Option<SyntaxNode> {
        first_value_child(&self.syntax)
    }
}

impl WorkloadsBlock {
    /// Every declared workload in this block, in source order.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn workloads(&self) -> Vec<WorkloadStmt> {
        self.syntax
            .children()
            .filter_map(WorkloadStmt::cast)
            .collect()
    }
}

impl WorkloadStmt {
    /// The workload's name (dotted paths joined with `.`; in practice a
    /// single identifier, e.g. `control`, `att`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn name(&self) -> String {
        name_path_text(&self.syntax)
    }

    /// The workload kind word (`loop`, `stream`, `event`, or `batch`):
    /// the second `Ident` token on the line (the first is the name).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn kind_word(&self) -> Option<String> {
        ident_texts(&self.syntax).into_iter().nth(1)
    }

    /// The workload's raw, non-decomposed parameter group node, if
    /// present (see [`SyntaxKind::WorkloadParams`]).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn params(&self) -> Option<SyntaxNode> {
        self.syntax
            .children()
            .find(|c| c.kind() == SyntaxKind::WorkloadParams)
    }

    /// The workload's trailing `realizes <intent>...` clause, if any
    /// (cuprite/05 sec. 1a).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn realizes(&self) -> Option<RealizesStmt> {
        self.syntax.children().find_map(RealizesStmt::cast)
    }
}

impl RealizesStmt {
    /// The compute intent names this workload realizes, in source
    /// order (the `realizes` verb itself is excluded).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn intents(&self) -> Vec<String> {
        ident_texts(&self.syntax).into_iter().skip(1).collect()
    }
}

impl CapabilityBlock {
    /// The capability table's entries (one `Field` per limit), in
    /// source order.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn entries(&self) -> Vec<Field> {
        self.syntax.children().filter_map(Field::cast).collect()
    }
}

impl RulePackBlock {
    /// The pack family word (`dfm`, `drc`, or `erc`): the block's
    /// leading ident token.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn family(&self) -> Option<String> {
        verb_text(&self.syntax)
    }

    /// The pack's rule declarations, in source order.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn rules(&self) -> Vec<RuleDecl> {
        self.syntax.children().filter_map(RuleDecl::cast).collect()
    }
}

impl RuleDecl {
    /// The rule's citable name (`waive dfm(<pack>.<name>)` cites it):
    /// the header ident after the `rule` word.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn name(&self) -> Option<String> {
        ident_texts(&self.syntax).into_iter().nth(1)
    }

    /// The rule's `forall <var> in <query>` match domain, if declared.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn forall(&self) -> Option<ForallClause> {
        self.syntax.children().find_map(ForallClause::cast)
    }

    /// The rule's `demand:` field (error severity), if present.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn demand(&self) -> Option<Field> {
        self.named_field("demand")
    }

    /// The rule's `advise:` field (warning severity), if present.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn advise(&self) -> Option<Field> {
        self.named_field("advise")
    }

    /// The rule's `per:` citation text (quotes stripped), if present.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn per(&self) -> Option<String> {
        self.named_field("per").and_then(|f| field_value_text(&f))
    }

    /// The rule's `why:` explanation text (quotes stripped), if present.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn why(&self) -> Option<String> {
        self.named_field("why").and_then(|f| field_value_text(&f))
    }

    /// The rule's `resolves: <field> from free` marker, if present.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn resolves(&self) -> Option<ResolvesClause> {
        self.syntax.children().find_map(ResolvesClause::cast)
    }

    /// The rule's `expect:` fixture block, if present.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn expect(&self) -> Option<ExpectBlock> {
        self.syntax.children().find_map(ExpectBlock::cast)
    }

    /// The first direct-child `Field` named `name` (`demand`, `per`,
    /// ...); direct children only, so expect-fixture internals are
    /// never mistaken for rule fields.
    fn named_field(&self, name: &str) -> Option<Field> {
        self.syntax
            .children()
            .filter_map(Field::cast)
            .find(|f| f.name() == name)
    }
}

impl ForallClause {
    /// The bound variable name (`forall h in holes` -> `h`): the ident
    /// after the `forall` word.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn var(&self) -> Option<String> {
        self.syntax
            .children_with_tokens()
            .filter_map(rowan::NodeOrToken::into_token)
            .filter(|t| t.kind() == SyntaxKind::Ident)
            .nth(1)
            .map(|t| t.text().to_string())
    }

    /// The query's source text, verbatim (everything after `in`,
    /// trimmed): the engine wave resolves it as a WO-08 query; any
    /// unmodeled filter tail is included (cycle 18 F95).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn query_text(&self) -> String {
        let mut seen_in = false;
        let mut out = String::new();
        for el in self.syntax.children_with_tokens() {
            match &el {
                rowan::NodeOrToken::Token(t) => match t.kind() {
                    SyntaxKind::InKw => seen_in = true,
                    SyntaxKind::Newline => break,
                    _ if seen_in => out.push_str(t.text()),
                    _ => {}
                },
                rowan::NodeOrToken::Node(n) if seen_in => {
                    out.push_str(&n.text().to_string());
                }
                rowan::NodeOrToken::Node(_) => {}
            }
        }
        out.trim().to_string()
    }
}

impl ForallSweepClaim {
    /// The bound variable/axis text (`forall combo in ...` -> `combo`;
    /// `forall i(out) in ...` -> `i(out)`, D105a's parenthesized-axis
    /// form): the header's raw text between `forall` and ` in `,
    /// trimmed. Read back by whole-node-text + split (the
    /// `full_predicate_text`/`combo_ref` pattern this codebase already
    /// uses for loosely-shaped header lines, AD-3 -- a multi-axis
    /// comma-joined header degrades to its first axis honestly rather
    /// than inventing structure the D105a grammar itself does not
    /// have).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn var(&self) -> Option<String> {
        let full = self.syntax.text().to_string();
        let after_forall = full.trim_start().strip_prefix("forall")?.trim_start();
        let idx = after_forall.find(" in ")?;
        let var = after_forall[..idx].trim();
        if var.is_empty() {
            None
        } else {
            Some(var.to_string())
        }
    }

    /// The domain's source text, verbatim (everything between the
    /// FIRST ` in ` and the header line's closing `:`, trimmed) -- the
    /// same textual-scan approach as [`ForallSweepClaim::var`].
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn domain_text(&self) -> String {
        let full = self.syntax.text().to_string();
        let Some(after_forall) = full.trim_start().strip_prefix("forall") else {
            return String::new();
        };
        let Some(idx) = after_forall.find(" in ") else {
            return String::new();
        };
        let after_in = &after_forall[idx + " in ".len()..];
        // The header line ends at the first newline; its own trailing
        // `:` (this node's body opener) is the last `:` on that line.
        let header_line = after_in.split(['\n', '\r']).next().unwrap_or(after_in);
        match header_line.rfind(':') {
            Some(colon_idx) => header_line[..colon_idx].trim().to_string(),
            None => header_line.trim().to_string(),
        }
    }

    /// The nested named claims in this sweep's body, each an ordinary
    /// [`Field`] (`<name>: <predicate>`) -- the WO-68 fix: these are
    /// real structured children now, not text swallowed into an
    /// `OpaqueIsland`.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn claims(&self) -> Vec<Field> {
        self.syntax.children().filter_map(Field::cast).collect()
    }
}

impl ResolvesClause {
    /// The resolved field's name path (`resolves: b.radius from free`
    /// -> `b.radius`): the path tokens after the colon.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn target(&self) -> String {
        let mut seen_colon = false;
        let mut out = String::new();
        for tok in self
            .syntax
            .children_with_tokens()
            .filter_map(rowan::NodeOrToken::into_token)
        {
            match tok.kind() {
                SyntaxKind::Colon => seen_colon = true,
                SyntaxKind::Ident | SyntaxKind::Dot if seen_colon => {
                    if tok.kind() == SyntaxKind::Ident && tok.text() == "from" {
                        break;
                    }
                    out.push_str(tok.text());
                }
                _ => {}
            }
        }
        out
    }

    /// True when the clause names `free` as the resolved source (the
    /// only source specced; anything else is the engine wave's E060x).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn from_free(&self) -> bool {
        let toks: Vec<_> = self
            .syntax
            .children_with_tokens()
            .filter_map(rowan::NodeOrToken::into_token)
            .filter(|t| !t.kind().is_trivia())
            .collect();
        toks.iter()
            .any(|t| t.kind() == SyntaxKind::Ident && t.text() == "from")
            && toks.iter().any(|t| t.kind() == SyntaxKind::FreeKw)
    }
}

impl ExpectBlock {
    /// The block's fixture cases, in source order.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn cases(&self) -> Vec<ExpectCase> {
        self.syntax
            .children()
            .filter_map(ExpectCase::cast)
            .collect()
    }
}

impl ExpectCase {
    /// The case's verdict word (`pass` or `fail`): the leading ident.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn verdict(&self) -> Option<String> {
        verb_text(&self.syntax)
    }

    /// The case's fixture value node (an entity-sketch `CallExpr`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn fixture(&self) -> Option<SyntaxNode> {
        first_value_child(&self.syntax)
    }
}

impl WaiveBlock {
    /// The waiver's target text: the rule or claim being waived, read
    /// from the header tokens between `waive` and `on`/`:` (e.g.
    /// `dfm(min_web_thickness)` or `Group.claim`). Token texts are
    /// concatenated verbatim (no interior spaces).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn target(&self) -> String {
        self.header_segment(false)
    }

    /// The waiver's scope query text: the `on <query>` clause, if any
    /// (e.g. `milled.body.relief_wall`). Empty when the waiver is
    /// unscoped.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn scope(&self) -> Option<String> {
        let s = self.header_segment(true);
        if s.is_empty() {
            None
        } else {
            Some(s)
        }
    }

    /// The mandatory `basis:` free text (with surrounding quotes
    /// stripped), if the body declares one. Its absence is an INV-2
    /// overreach diagnostic (an unjustified concession) in lowering.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn basis(&self) -> Option<String> {
        self.body_field_value("basis")
    }

    /// The `expires:` marker text, if any (regolith/12 rule 8).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn expires(&self) -> Option<String> {
        self.body_field_value("expires")
    }

    /// True when the waiver carries a `by <evidence>` clause (making it
    /// a deviation rather than a bare waiver): any `by` keyword token in
    /// the block subtree.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn has_evidence(&self) -> bool {
        self.syntax
            .descendants_with_tokens()
            .filter_map(rowan::NodeOrToken::into_token)
            .any(|t| t.kind() == SyntaxKind::ByKw)
    }

    /// The `by <evidence>` clause's reference text (e.g. `test(vr081)` or
    /// `doc(memos/foo.md)`), concatenated verbatim with interior trivia
    /// dropped, stopping at the end of the clause's line. `None` when the
    /// waiver carries no `by` clause (a bare waiver). This is the ref the
    /// Python release gate resolves for evidence-class + trust-floor
    /// checks (D207: `by doc(<memo>)` resolves to an in-project memo);
    /// presence still equals [`WaiveBlock::has_evidence`].
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn evidence(&self) -> Option<String> {
        let mut seen_by = false;
        let mut out = String::new();
        for tok in self
            .syntax
            .descendants_with_tokens()
            .filter_map(rowan::NodeOrToken::into_token)
        {
            if !seen_by {
                if tok.kind() == SyntaxKind::ByKw {
                    seen_by = true;
                }
                continue;
            }
            match tok.kind() {
                SyntaxKind::Newline => break,
                SyntaxKind::Whitespace | SyntaxKind::Comment => {}
                _ => out.push_str(tok.text()),
            }
        }
        seen_by.then_some(out)
    }

    /// The concatenated non-trivia header token texts either before
    /// (`after_on = false`) or after (`after_on = true`) the `on`
    /// keyword, stopping at the header-terminating `:`. Skips the
    /// leading `waive` keyword. Header tokens are the block node's own
    /// direct tokens (body statements are child nodes, not reached).
    fn header_segment(&self, after_on: bool) -> String {
        let mut seen_on = false;
        let mut out = String::new();
        for tok in self
            .syntax
            .children_with_tokens()
            .filter_map(rowan::NodeOrToken::into_token)
        {
            match tok.kind() {
                SyntaxKind::Colon | SyntaxKind::Newline => break,
                SyntaxKind::WaiveKw | SyntaxKind::Whitespace | SyntaxKind::Comment => {}
                SyntaxKind::OnKw => seen_on = true,
                _ if seen_on == after_on => out.push_str(tok.text()),
                _ => {}
            }
        }
        out
    }

    /// The trimmed value text of the first body `Field` named `name`
    /// (`basis`/`expires`), with surrounding double quotes stripped.
    fn body_field_value(&self, name: &str) -> Option<String> {
        self.syntax
            .descendants()
            .filter_map(Field::cast)
            .find(|f| f.name() == name)
            .and_then(|f| field_value_text(&f))
    }
}

/// A `Field`'s raw value text after the `:`, trimmed, with surrounding
/// double quotes stripped -- captures bare string/number values (which
/// are tokens, not wrapped value nodes). Shared by the waiver
/// (`basis:`/`expires:`) and rule (`per:`/`why:`) text accessors.
fn field_value_text(field: &Field) -> Option<String> {
    let text = field.syntax().text().to_string();
    let (_, rest) = text.split_once(':')?;
    Some(rest.trim().trim_matches('"').to_string())
}

impl InstExpr {
    /// The instantiation head name: the type constructor being
    /// instantiated (e.g. `PatternOf`), read from the head
    /// `NameRef`/`Path` child node.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn head_name(&self) -> String {
        self.syntax
            .children()
            .find(|c| matches!(c.kind(), SyntaxKind::NameRef | SyntaxKind::Path))
            .map_or_else(String::new, |head| name_path_text(&head))
    }

    /// The instantiation's typed argument list, if present.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn args(&self) -> Option<GenericArgs> {
        self.syntax.children().find_map(GenericArgs::cast)
    }

    /// The number of top-level arguments (`PatternOf<TappedHole<M3>>`
    /// has arity 1; `Decoder<3, 8>` has arity 2).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn arity(&self) -> usize {
        self.args().map_or(0, |a| a.arity())
    }
}

impl GenericArgs {
    /// The number of top-level (outermost-angle) arguments, counted as
    /// depth-1 commas + 1 when any content is present (nested `<...>`
    /// commas do not count).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn arity(&self) -> usize {
        top_level_arity(&self.syntax)
    }
}

impl GenericParams {
    /// The number of declared parameters (top-level comma count + 1 when
    /// non-empty), the arity a use site must match (INV-11).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn arity(&self) -> usize {
        top_level_arity(&self.syntax)
    }
}

/// Count the top-level arguments/parameters inside an angle-bracketed
/// list node (`GenericArgs`/`GenericParams`): depth-1 commas + 1 when
/// the list holds any non-trivia content, else 0. The node's own outer
/// `<`/`>` open and close the depth; nested `<...>` commas are skipped.
fn top_level_arity(node: &SyntaxNode) -> usize {
    let mut depth = 0i32;
    let mut commas = 0usize;
    let mut saw_content = false;
    for tok in node
        .children_with_tokens()
        .filter_map(rowan::NodeOrToken::into_token)
    {
        match tok.kind() {
            SyntaxKind::Lt => depth += 1,
            SyntaxKind::Gt => depth -= 1,
            SyntaxKind::Comma if depth == 1 => commas += 1,
            SyntaxKind::Whitespace | SyntaxKind::Newline | SyntaxKind::Comment => {}
            _ if depth >= 1 => saw_content = true,
            _ => {}
        }
    }
    // Nested instantiation arguments live in child `InstExpr` nodes (not
    // direct tokens), so also treat any child node as content.
    if node.children().next().is_some() {
        saw_content = true;
    }
    if saw_content {
        commas + 1
    } else {
        0
    }
}

impl Field {
    /// The field's name token text (the leading identifier; dotted
    /// paths are joined with `.`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn name(&self) -> String {
        name_path_text(&self.syntax)
    }

    /// The field's value node, skipping the name/colon/tail trivia:
    /// the first non-trivia, non-`OpaqueIsland` child node.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn value(&self) -> Option<SyntaxNode> {
        first_value_child(&self.syntax)
    }

    /// The field's FULL value text after its `name:` separator, spanning
    /// EVERY value-ish child -- not just the first, as [`Field::value`]
    /// does. A continuation predicate (`settles(x, to=..deg,\n    within
    /// 3s after evt)`) parses as more than one sibling node under the
    /// field: a typed expression node (e.g. `ToleranceExpr`), then an
    /// `OpaqueIsland` catch-all for the `within ... after ...` trailer
    /// the syntax layer does not further type -- `Field::value`'s "first
    /// value child" contract silently drops that trailer (and any
    /// closing bracket living inside it), truncating the rendered value.
    /// Reading every child's text (nodes AND tokens) after the field's
    /// own `name:` separator sidesteps that CST shape entirely, the same
    /// technique `regolith_lower::claims::full_predicate_text` uses for
    /// the require-block discharge path (WO-90 deliverable 2) -- this is
    /// its doc-rendering twin, kept here so any CST consumer (not just
    /// the lowering pass) can read a field's whole value losslessly. The
    /// field's dotted name (the only thing before the first `:`) never
    /// itself contains a `:`, so splitting on the first `:` is
    /// unambiguous even when the value has its own later colon
    /// (`within 5s after anomaly: op = safe`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn full_value_text(&self) -> String {
        let mut full = String::new();
        for elem in self.syntax.children_with_tokens() {
            match elem {
                rowan::NodeOrToken::Node(n) if n.kind() == SyntaxKind::ModelPin => {}
                rowan::NodeOrToken::Node(n) => full.push_str(&n.text().to_string()),
                rowan::NodeOrToken::Token(t) => full.push_str(t.text()),
            }
        }
        match full.split_once(':') {
            Some((_, rest)) => rest.trim().to_string(),
            None => String::new(),
        }
    }

    /// This claim line's trailing `, model=<ident>` rung-5 pin, if any
    /// (WO-80 deliverable 1): the model identifier text, or `None` when
    /// the claim carries no pin.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn model_pin(&self) -> Option<String> {
        self.syntax
            .children()
            .find_map(ModelPin::cast)
            .and_then(|pin| pin.model_name())
    }
}

impl ModelPin {
    /// The pinned model identifier's text (`model=<ident>` -> `<ident>`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn model_name(&self) -> Option<String> {
        self.syntax
            .children_with_tokens()
            .filter_map(rowan::NodeOrToken::into_token)
            .filter(|t| t.kind() == SyntaxKind::Ident)
            .last()
            .map(|t| t.text().to_string())
    }
}

impl BudgetStmt {
    /// The budget's name token text (dotted paths joined with `.`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn name(&self) -> String {
        name_path_text(&self.syntax)
    }

    /// The budget's limit value node (see [`Field::value`]).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn value(&self) -> Option<SyntaxNode> {
        first_value_child(&self.syntax)
    }
}

impl CtorStmt {
    /// The statement's name token text (dotted paths joined with `.`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn name(&self) -> String {
        name_path_text(&self.syntax)
    }

    /// The statement's value node (see [`Field::value`]).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn value(&self) -> Option<SyntaxNode> {
        first_value_child(&self.syntax)
    }
}

impl RequireClaim {
    /// Each claim line in this group's body (parsed as [`Field`]s:
    /// `subject: predicate`). Direct children only -- claims nested
    /// inside a `forall <var> in <domain>:` block are NOT included
    /// here; see [`RequireClaim::sweeps`] and
    /// [`RequireClaim::all_claims`] (WO-68).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn claims(&self) -> Vec<Field> {
        self.syntax.children().filter_map(Field::cast).collect()
    }

    /// Each `forall <var> in <domain>:` BLOCK claim directly in this
    /// group's body (WO-68).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn sweeps(&self) -> Vec<ForallSweepClaim> {
        self.syntax
            .children()
            .filter_map(ForallSweepClaim::cast)
            .collect()
    }

    /// Every claim in this group, direct or nested inside a `forall
    /// <var> in <domain>:` block, paired with the sweep it is under
    /// (`None` for a direct claim) -- source order, direct claims
    /// interleaved with each sweep's claims in the sweep's own
    /// position (WO-68: the single accessor the lowering pass uses so
    /// no claim group can silently drop a nested named claim again).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn all_claims(&self) -> Vec<(Field, Option<ForallSweepClaim>)> {
        let mut out = Vec::new();
        for child in self.syntax.children() {
            if let Some(field) = Field::cast(child.clone()) {
                out.push((field, None));
            } else if let Some(sweep) = ForallSweepClaim::cast(child) {
                for field in sweep.claims() {
                    out.push((field, Some(sweep.clone())));
                }
            }
        }
        out
    }

    /// Each `compute <name>: ...` claim line in this group's body
    /// (WO-33 D98).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn compute_claims(&self) -> Vec<ComputeField> {
        self.syntax
            .children()
            .filter_map(ComputeField::cast)
            .collect()
    }
}

impl ComputeField {
    /// The produced field's name token text (dotted paths joined with
    /// `.`), skipping the leading `compute` word (whole-node-text +
    /// split approach, mirroring [`ComputeField::predicate_text`]).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn name(&self) -> String {
        let full = self.syntax.text().to_string();
        let after_compute = full
            .trim_start()
            .strip_prefix("compute")
            .unwrap_or(full.trim_start())
            .trim_start();
        match after_compute.split_once(':') {
            Some((name, _)) => name.trim().to_string(),
            None => String::new(),
        }
    }

    /// The field's value node (see [`Field::value`]): the `<quantity
    /// kind>` path; the `over <index domain>` tail rides the same
    /// `OpaqueIsland` sweep as any other unmodeled tail.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn value(&self) -> Option<SyntaxNode> {
        first_value_child(&self.syntax)
    }

    /// The full source text after the `:` (quantity kind + `over`
    /// clause, verbatim), for the lowering pass to pattern-match the
    /// `over <zone set ref>` / `over <var> in <interval>` shape without
    /// a dedicated sub-grammar (mirrors `full_predicate_text` in
    /// `regolith-lower::claims`, which uses the same whole-node-text +
    /// split-on-`:` approach).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn predicate_text(&self) -> String {
        let full = self.syntax.text().to_string();
        match full.split_once(':') {
            Some((_, rest)) => rest.trim().to_string(),
            None => String::new(),
        }
    }
}

impl BinExpr {
    /// The left operand.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn lhs(&self) -> Option<SyntaxNode> {
        self.syntax.children().next()
    }

    /// The right operand.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn rhs(&self) -> Option<SyntaxNode> {
        self.syntax.children().nth(1)
    }
}

impl QuantityLit {
    /// The literal's unit spelling (the `Ident` token immediately
    /// after the number).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn unit_text(&self) -> Option<String> {
        self.syntax
            .children_with_tokens()
            .filter_map(rowan::NodeOrToken::into_token)
            .find(|t| t.kind() == SyntaxKind::Ident)
            .map(|t| t.text().to_string())
    }
}

/// Join a `name`/`ctor` statement's leading `Ident (. Ident)*` name
/// tokens with `.` (the accessor both [`Field::name`] and
/// [`CtorStmt::name`] share).
fn name_path_text(node: &SyntaxNode) -> String {
    node.children_with_tokens()
        .filter_map(rowan::NodeOrToken::into_token)
        .take_while(|t| matches!(t.kind(), SyntaxKind::Ident | SyntaxKind::Dot))
        .map(|t| t.text().to_string())
        .collect()
}

/// The first child node of a `Field`/`CtorStmt` that is not the
/// trailing lossless-sweep `OpaqueIsland` (the recognized value, when
/// the grammar classified one).
fn first_value_child(node: &SyntaxNode) -> Option<SyntaxNode> {
    node.children()
        .find(|c| c.kind() != SyntaxKind::OpaqueIsland)
}

impl Decl {
    /// The declaration keyword (`part`, `interface`, `system`, ...).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn kind_keyword(&self) -> Option<SyntaxKind> {
        self.syntax
            .children_with_tokens()
            .filter_map(rowan::NodeOrToken::into_token)
            .map(|t| t.kind())
            .find(|k| !k.is_trivia())
    }

    /// The declaration's own name: the first `Ident` token in the
    /// header line (before any generic-parameter `<...>` list, which
    /// this WO does not further decompose -- see the report note).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn name(&self) -> Option<String> {
        self.syntax
            .children_with_tokens()
            .filter_map(rowan::NodeOrToken::into_token)
            .find(|t| t.kind() == SyntaxKind::Ident)
            .map(|t| t.text().to_string())
    }

    /// The declaration's structured statements (fields, ctor
    /// statements, `then`/`require`/`budget`/`waive`/`policy`/`locked`
    /// blocks); domain-specific statements remain opaque and are
    /// omitted here (call [`AstNode::syntax`] and filter
    /// `OpaqueIsland` children directly to see everything).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn fields(&self) -> Vec<Field> {
        self.syntax.children().filter_map(Field::cast).collect()
    }

    /// The declaration's `require <Group>:` claim groups.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn claims(&self) -> Vec<RequireClaim> {
        self.syntax
            .children()
            .filter_map(RequireClaim::cast)
            .collect()
    }

    /// The declaration's structured `budget ...:` statements.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn budgets(&self) -> Vec<BudgetStmt> {
        self.syntax
            .children()
            .filter_map(BudgetStmt::cast)
            .collect()
    }

    /// Every `waive ...:` block anywhere in the declaration body (top
    /// level or nested inside a `then` scope): the rung-7 concessions
    /// this subject declares (regolith/12 sec. 3).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn waivers(&self) -> Vec<WaiveBlock> {
        self.syntax
            .descendants()
            .filter_map(WaiveBlock::cast)
            .collect()
    }

    /// True when this is a `process` module declaration (hematite/04
    /// sec. 2A) -- the leading word is the contextual `process` ident.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn is_process(&self) -> bool {
        self.syntax
            .children_with_tokens()
            .filter_map(rowan::NodeOrToken::into_token)
            .find(|t| !t.kind().is_trivia())
            .is_some_and(|t| t.kind() == SyntaxKind::Ident && t.text() == "process")
    }

    /// A process decl's own name (`process press_brake_shop:` ->
    /// `press_brake_shop`; a dotted registry path,
    /// `process std.sheet_metal:`, yields `std.sheet_metal` whole --
    /// packs are registry content per regolith/11, so namespaced pack
    /// names are first-class). `None` for non-process decls
    /// ([`Decl::name`] keeps its first-ident behavior, which lowering
    /// subjects rely on).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn process_name(&self) -> Option<String> {
        if !self.is_process() {
            return None;
        }
        // The contiguous Ident/Dot run after the leading `process`
        // word (non-trivia tokens other than Ident/Dot end the name).
        let mut out = String::new();
        for token in self
            .syntax
            .children_with_tokens()
            .filter_map(rowan::NodeOrToken::into_token)
            .filter(|t| !t.kind().is_trivia())
            .skip(1)
        {
            match token.kind() {
                SyntaxKind::Ident | SyntaxKind::Dot => out.push_str(token.text()),
                _ => break,
            }
        }
        (!out.is_empty()).then_some(out)
    }

    /// A process decl's `capability:` table, if declared
    /// (hematite/02 sec. 10).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn capability(&self) -> Option<CapabilityBlock> {
        self.syntax.children().find_map(CapabilityBlock::cast)
    }

    /// A process decl's rule-pack blocks (`dfm:`/`drc:`/`erc:`), in
    /// source order.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn rule_packs(&self) -> Vec<RulePackBlock> {
        self.syntax
            .children()
            .filter_map(RulePackBlock::cast)
            .collect()
    }
}

impl MediumDecl {
    /// The medium's name: the first `Ident` after the leading contextual
    /// `medium` word (`medium ShopAir: gas` -> `ShopAir`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn name(&self) -> Option<String> {
        header_ident_after_keyword(&self.syntax)
    }

    /// The phase word (`liquid`/`gas`): the `Ident` after the header
    /// `:` (fluorite/02 sec. 1).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn phase(&self) -> Option<String> {
        let mut toks = self
            .syntax
            .children_with_tokens()
            .filter_map(rowan::NodeOrToken::into_token)
            .skip_while(|t| t.kind() != SyntaxKind::Colon);
        toks.next(); // the `:` itself
        toks.find(|t| t.kind() == SyntaxKind::Ident)
            .map(|t| t.text().to_string())
    }
}

impl FlownetDecl {
    /// The flownet's name: the first `Ident` after the leading contextual
    /// `flownet` word (`flownet AirDrop(medium=ShopAir):` -> `AirDrop`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn name(&self) -> Option<String> {
        header_ident_after_keyword(&self.syntax)
    }

    /// The `edges:` block, if declared.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn edges(&self) -> Option<EdgesBlock> {
        self.syntax.children().find_map(EdgesBlock::cast)
    }

    /// The `states:` block, if declared.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn states(&self) -> Option<StatesBlock> {
        self.syntax.children().find_map(StatesBlock::cast)
    }

    /// The flownet's `reference:`/`nodes:` header fields.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn fields(&self) -> Vec<Field> {
        self.syntax.children().filter_map(Field::cast).collect()
    }
}

impl RequireDecl {
    /// Each claim line in this group's body (parsed as [`Field`]s:
    /// `subject: predicate`), matching [`RequireClaim::claims`]. Direct
    /// children only -- see [`RequireDecl::sweeps`] and
    /// [`RequireDecl::all_claims`] for claims nested inside a `forall
    /// <var> in <domain>:` block (WO-68).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn claims(&self) -> Vec<Field> {
        self.syntax.children().filter_map(Field::cast).collect()
    }

    /// Each `forall <var> in <domain>:` BLOCK claim directly in this
    /// group's body (WO-68), matching [`RequireClaim::sweeps`].
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn sweeps(&self) -> Vec<ForallSweepClaim> {
        self.syntax
            .children()
            .filter_map(ForallSweepClaim::cast)
            .collect()
    }

    /// Every claim in this group, direct or nested inside a `forall
    /// <var> in <domain>:` block, paired with the sweep it is under
    /// (`None` for a direct claim) -- matches
    /// [`RequireClaim::all_claims`]; the single accessor every
    /// top-level require-group lowering pass (calcite frame claims,
    /// fluid claims, top-level cost claims) uses (WO-68).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn all_claims(&self) -> Vec<(Field, Option<ForallSweepClaim>)> {
        let mut out = Vec::new();
        for child in self.syntax.children() {
            if let Some(field) = Field::cast(child.clone()) {
                out.push((field, None));
            } else if let Some(sweep) = ForallSweepClaim::cast(child) {
                for field in sweep.claims() {
                    out.push((field, Some(sweep.clone())));
                }
            }
        }
        out
    }
}

impl EdgesBlock {
    /// Every declared edge in this block, in source order.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn edges(&self) -> Vec<EdgeStmt> {
        self.syntax.children().filter_map(EdgeStmt::cast).collect()
    }
}

impl EdgeStmt {
    /// The edge's name (`tank`, `reg`, ...): its leading `Ident` path.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn name(&self) -> String {
        name_path_text(&self.syntax)
    }

    /// The edge's constructor value node (the `CallExpr`), skipping the
    /// trailing [`SensePair`] (see [`Field::value`]).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn value(&self) -> Option<SyntaxNode> {
        first_value_child(&self.syntax)
    }

    /// The edge's trailing `(<a> -> <b>)` positive-sense naming pair,
    /// if present (fluorite/02 sec. 4).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn sense(&self) -> Option<SensePair> {
        self.syntax.children().find_map(SensePair::cast)
    }
}

impl SensePair {
    /// The two name-path idents on either side of `->`, in source
    /// order (`(a -> b)` -> `["a", "b"]`; a malformed/partial pair may
    /// yield fewer than two).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn names(&self) -> Vec<String> {
        self.syntax
            .descendants_with_tokens()
            .filter_map(rowan::NodeOrToken::into_token)
            .filter(|t| t.kind() == SyntaxKind::Ident)
            .map(|t| t.text().to_string())
            .collect()
    }

    /// The "from" (positive-sense source) name, if present.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn from_name(&self) -> Option<String> {
        self.names().into_iter().next()
    }

    /// The "to" (positive-sense sink) name, if present.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn to_name(&self) -> Option<String> {
        self.names().into_iter().nth(1)
    }
}

impl DomainSet {
    /// Every label in this `{...}` set, in source order (fluorite/02
    /// sec. 4/5: a state variable's discrete domain). A label may
    /// coincide with a contextual keyword spelling (`on`/`off`, ...);
    /// every token other than the delimiting `{`/`}` and the `,`
    /// separators is a label.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn items(&self) -> Vec<String> {
        self.syntax
            .descendants_with_tokens()
            .filter_map(rowan::NodeOrToken::into_token)
            .filter(|t| {
                let is_brace = t.kind() == SyntaxKind::Error && matches!(t.text(), "{" | "}");
                !matches!(t.kind(), SyntaxKind::Whitespace | SyntaxKind::Comma) && !is_brace
            })
            .map(|t| t.text().to_string())
            .collect()
    }
}

impl StatesBlock {
    /// Every declared state line in this block, in source order.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn states(&self) -> Vec<StateStmt> {
        self.syntax.children().filter_map(StateStmt::cast).collect()
    }
}

impl StateStmt {
    /// The `{...}` domain set on this line, if the line is one of the
    /// two typed shapes (`<edge>.<param> in {...}` or
    /// `state <name> in {...}`); `None` for an `event` line or any
    /// shape the grammar leaves untyped.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn domain(&self) -> Option<DomainSet> {
        self.syntax.children().find_map(DomainSet::cast)
    }
}

impl HarnessDecl {
    /// The harness's name: the first `Ident` after the leading
    /// contextual `harness` word (`harness MainLoom:` -> `MainLoom`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn name(&self) -> Option<String> {
        header_ident_after_keyword(&self.syntax)
    }

    /// Every declared run in this harness, in source order.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn runs(&self) -> Vec<RunStmt> {
        self.syntax.children().filter_map(RunStmt::cast).collect()
    }

    /// Every declared connector environment class in this harness, in
    /// source order.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn environments(&self) -> Vec<EnvironmentStmt> {
        self.syntax
            .children()
            .filter_map(EnvironmentStmt::cast)
            .collect()
    }
}

impl RunStmt {
    /// The run's name: the first `Ident` after the leading contextual
    /// `run` word (`run batt_to_kill: ...` -> `batt_to_kill`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn name(&self) -> Option<String> {
        header_ident_after_keyword(&self.syntax)
    }

    /// The header line's significant text (comment stripped), for
    /// elaboration (WO-34 deliverable 2) to re-tokenize the `from
    /// <ep> to <ep>` endpoint pair this grammar records whole.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn header_text(&self) -> String {
        header_line_text(&self.syntax)
    }

    /// The run's routed-PATH line, if declared.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn along(&self) -> Option<AlongClause> {
        self.syntax.children().find_map(AlongClause::cast)
    }

    /// The run's `bundle <group>` co-routing line, if declared.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn bundle(&self) -> Option<BundleClause> {
        self.syntax.children().find_map(BundleClause::cast)
    }
}

impl AlongClause {
    /// This line's significant text (comment stripped), for elaboration
    /// to re-tokenize as either a waypoint ref list or the planner-free
    /// marker (see the [`SyntaxKind::AlongClause`] doc comment).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn text(&self) -> String {
        header_line_text(&self.syntax)
    }

    /// Whether this line's recorded text spells the planner-routed
    /// marker (`route: free`, with or without a leading `along`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn is_route_free(&self) -> bool {
        let t = self.text();
        let t = t.strip_prefix("along").unwrap_or(&t).trim();
        let t = t.strip_prefix("route").unwrap_or(t).trim();
        let t = t.strip_prefix(':').unwrap_or(t).trim();
        t == "free"
    }
}

impl BundleClause {
    /// The bundle group name: the text after the leading `bundle` word.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn group(&self) -> Option<String> {
        let t = header_line_text(&self.syntax);
        let rest = t.strip_prefix("bundle")?.trim();
        (!rest.is_empty()).then(|| rest.to_string())
    }
}

impl EnvironmentStmt {
    /// The environment class's name: the first `Ident` after the
    /// leading contextual `environment` word.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn name(&self) -> Option<String> {
        header_ident_after_keyword(&self.syntax)
    }

    /// The declared `[lo, hi]` bound, if the value classified as the
    /// existing bracket grammar ([`SyntaxKind::IntervalExpr`]).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn bound(&self) -> Option<SyntaxNode> {
        self.syntax
            .children()
            .find(|c| c.kind() == SyntaxKind::IntervalExpr)
    }
}

impl TestDecl {
    /// The test's name (`test spar_gust_case:` -> `spar_gust_case`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn name(&self) -> Option<String> {
        header_ident_after_keyword(&self.syntax)
    }

    /// The test's `scenario:` block, if declared.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn scenario(&self) -> Option<ScenarioBlock> {
        self.syntax.children().find_map(ScenarioBlock::cast)
    }

    /// The test's `expect:` block, if declared.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn expect(&self) -> Option<TestExpectBlock> {
        self.syntax.children().find_map(TestExpectBlock::cast)
    }
}

impl ScenarioBlock {
    /// The scenario's declared fields (config-axis selections, rung-1
    /// assertions expressed as ordinary [`Field`]s over the value
    /// grammar -- see `ctors()` for the `=` shape).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn fields(&self) -> Vec<Field> {
        self.syntax.children().filter_map(Field::cast).collect()
    }

    /// The scenario's rung-1 assertion / `seed =` / `budget_evals =`
    /// lines (`path = value`, the [`CtorStmt`] shape).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn ctors(&self) -> Vec<CtorStmt> {
        self.syntax.children().filter_map(CtorStmt::cast).collect()
    }

    /// The scenario's rung-2 pin blocks (`locked:` lines).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn locked_blocks(&self) -> Vec<LockedBlock> {
        self.syntax
            .children()
            .filter_map(LockedBlock::cast)
            .collect()
    }
}

impl TestExpectBlock {
    /// Every expectation case in this block, in source order.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn cases(&self) -> Vec<TestExpectCase> {
        self.syntax
            .children()
            .filter_map(TestExpectCase::cast)
            .collect()
    }
}

impl TestExpectCase {
    /// The line's significant text (comment stripped).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn text(&self) -> String {
        header_line_text(&self.syntax)
    }

    /// The leading form word: one of `diagnostic`/`verdict`/`value`/
    /// `count`/`winner` (charter 37 sec. 1's five expectation forms),
    /// or `None` for an unrecognized form (the negative-fixture case --
    /// the CST still records the line whole; only elaboration flags it).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn form(&self) -> Option<String> {
        self.text().split_whitespace().next().map(str::to_string)
    }

    /// The text after the leading form word: `diagnostic`'s `<CODE> on
    /// <subject>`, `verdict`/`count`/`winner`'s `<path> = <rhs>`,
    /// `value`'s `<path> within [lo, hi] [cause <class>]`. Elaboration
    /// (slice B's runner) re-tokenizes this per form; kept as one
    /// recorded string here (the WO-05 header-rest idiom) since the
    /// five shapes do not unify under one field/ctor production.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn tail(&self) -> Option<String> {
        let text = self.text();
        let form = self.form()?;
        let rest = text.strip_prefix(&form)?.trim();
        (!rest.is_empty()).then(|| rest.to_string())
    }
}

/// The first physical line of a node's text, trailing comment and
/// whitespace stripped (mirrors `walk.rs`'s `node_line` helper; kept
/// separate to avoid an inter-module dependency for one small string
/// operation). `pub` so downstream lowering passes (e.g.
/// `regolith_lower::test_decl_lower`) can read a direct CST child's
/// significant line without a second copy of this helper (NO
/// DUPLICATION).
#[must_use]
// frob:doc docs/modules/regolith-syntax.md#ast
// frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
pub fn header_line_text(node: &SyntaxNode) -> String {
    let text = node.text().to_string();
    let first = text.lines().next().unwrap_or("");
    match first.find('#') {
        Some(i) => &first[..i],
        None => first,
    }
    .trim()
    .to_string()
}

/// The name of a fluorite declaration whose header leads with a
/// contextual keyword word (`medium`/`flownet`): the SECOND `Ident`
/// token on the header (the first is the contextual word). `require`
/// leads with the `RequireKw` keyword, so its name is the first `Ident`
/// -- callers there use [`Decl::name`]'s first-ident shape instead.
fn header_ident_after_keyword(node: &SyntaxNode) -> Option<String> {
    node.children_with_tokens()
        .filter_map(rowan::NodeOrToken::into_token)
        .filter(|t| t.kind() == SyntaxKind::Ident)
        .nth(1)
        .map(|t| t.text().to_string())
}

impl File {
    /// The import statements at the head of the file.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn imports(&self) -> Vec<ImportStmt> {
        self.syntax
            .children()
            .filter_map(ImportStmt::cast)
            .collect()
    }

    /// The top-level declarations of the file.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn decls(&self) -> Vec<Decl> {
        self.syntax.children().filter_map(Decl::cast).collect()
    }

    /// The top-level `medium` declarations (fluorite/02 sec. 1).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn mediums(&self) -> Vec<MediumDecl> {
        self.syntax
            .children()
            .filter_map(MediumDecl::cast)
            .collect()
    }

    /// The top-level `flownet` declarations (fluorite/02 sec. 4).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn flownets(&self) -> Vec<FlownetDecl> {
        self.syntax
            .children()
            .filter_map(FlownetDecl::cast)
            .collect()
    }

    /// The top-level `require` claim groups in a `.fluo` file
    /// (fluorite/02 sec. 6).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn fluid_requires(&self) -> Vec<RequireDecl> {
        self.syntax
            .children()
            .filter_map(RequireDecl::cast)
            .collect()
    }

    /// The top-level `harness` declarations (D99, WO-34 deliverable 1).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn harnesses(&self) -> Vec<HarnessDecl> {
        self.syntax
            .children()
            .filter_map(HarnessDecl::cast)
            .collect()
    }

    /// The top-level `site` declarations (calcite/02 sec. 1).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn sites(&self) -> Vec<SiteDecl> {
        self.syntax.children().filter_map(SiteDecl::cast).collect()
    }

    /// The top-level `grid` declarations (calcite/02 sec. 1).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn grids(&self) -> Vec<GridDecl> {
        self.syntax.children().filter_map(GridDecl::cast).collect()
    }

    /// The top-level `level` declarations (calcite/02 sec. 1).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn levels(&self) -> Vec<LevelDecl> {
        self.syntax.children().filter_map(LevelDecl::cast).collect()
    }

    /// The top-level `space` declarations (calcite/02 sec. 2).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn spaces(&self) -> Vec<SpaceDecl> {
        self.syntax.children().filter_map(SpaceDecl::cast).collect()
    }

    /// The top-level `adjacent` declarations (calcite/02 sec. 2).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn adjacents(&self) -> Vec<AdjacentDecl> {
        self.syntax
            .children()
            .filter_map(AdjacentDecl::cast)
            .collect()
    }

    /// The top-level `access` blocks (calcite/02 sec. 2).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn accesses(&self) -> Vec<AccessDecl> {
        self.syntax
            .children()
            .filter_map(AccessDecl::cast)
            .collect()
    }

    /// The top-level `circulation` declarations (calcite/02 sec. 3).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn circulations(&self) -> Vec<CirculationDecl> {
        self.syntax
            .children()
            .filter_map(CirculationDecl::cast)
            .collect()
    }

    /// The top-level `member` declarations (calcite/02 sec. 4).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn members(&self) -> Vec<MemberDecl> {
        self.syntax
            .children()
            .filter_map(MemberDecl::cast)
            .collect()
    }

    /// The top-level `structure` declarations (calcite/02 sec. 6).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn structures(&self) -> Vec<StructureDecl> {
        self.syntax
            .children()
            .filter_map(StructureDecl::cast)
            .collect()
    }

    /// The top-level `loads` blocks (calcite/02 sec. 7).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn loads_blocks(&self) -> Vec<LoadsDecl> {
        self.syntax.children().filter_map(LoadsDecl::cast).collect()
    }

    /// The top-level `power` declarations (charter 43 sec. 1, WO-132).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn power_nets(&self) -> Vec<PowerDecl> {
        self.syntax.children().filter_map(PowerDecl::cast).collect()
    }

    /// The top-level `test` declarations (WO-83; charter 37): every
    /// cross-track design test in this file.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn tests(&self) -> Vec<TestDecl> {
        self.syntax.children().filter_map(TestDecl::cast).collect()
    }
}

impl SiteDecl {
    /// The site's name (`site Riverside:` -> `Riverside`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn name(&self) -> Option<String> {
        header_ident_after_keyword(&self.syntax)
    }
}

impl GridDecl {
    /// The grid's name (`grid cols: A, B, C, D spacing 7.2m` -> `cols`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn name(&self) -> Option<String> {
        header_ident_after_keyword(&self.syntax)
    }
}

impl LevelDecl {
    /// The level's name (`level ground: 0m` -> `ground`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn name(&self) -> Option<String> {
        header_ident_after_keyword(&self.syntax)
    }
}

impl SpaceDecl {
    /// The space's name (`space Lobby:` -> `Lobby`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn name(&self) -> Option<String> {
        header_ident_after_keyword(&self.syntax)
    }

    /// The space's header/body fields (`area:`, `occupancy:`, `at:`,
    /// `bounded_by`, `offers:`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn fields(&self) -> Vec<Field> {
        self.syntax.children().filter_map(Field::cast).collect()
    }
}

impl AccessDecl {
    /// Every declared opening in this `access:` block, in source order
    /// (the same [`EdgeStmt`] shape a flownet `edges:` block types).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST001 reason="thin CST accessor exercised transitively by every parser/lowering test that walks this node kind; no dedicated unit test isolates the accessor itself"
    pub fn openings(&self) -> Vec<EdgeStmt> {
        self.syntax.children().filter_map(EdgeStmt::cast).collect()
    }
}

impl CirculationDecl {
    /// The circulation net's name (`circulation Egress:` -> `Egress`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn name(&self) -> Option<String> {
        header_ident_after_keyword(&self.syntax)
    }

    /// The net's `reference:`/`nodes:`/`edges:` header fields (all
    /// plain comma-list fields at this front-end layer, calcite/02
    /// sec. 3).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn fields(&self) -> Vec<Field> {
        self.syntax.children().filter_map(Field::cast).collect()
    }
}

impl MemberDecl {
    /// The member's name (`member G1: beam` -> `G1`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn name(&self) -> Option<String> {
        header_ident_after_keyword(&self.syntax)
    }

    /// The member's `section:`/`material:` fields plus its `from ... to
    /// ...` anchor line, recorded as ordinary generic statements.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn fields(&self) -> Vec<Field> {
        self.syntax.children().filter_map(Field::cast).collect()
    }
}

impl StructureDecl {
    /// The structure's name (`structure MainFrame:` -> `MainFrame`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn name(&self) -> Option<String> {
        header_ident_after_keyword(&self.syntax)
    }

    /// The `support:`/`members:` header fields.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn fields(&self) -> Vec<Field> {
        self.syntax.children().filter_map(Field::cast).collect()
    }

    /// The `transfers:` block, if declared (calcite/02 sec. 6): the
    /// load-transfer edges, typed identically to a flownet `edges:`
    /// block.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn transfers(&self) -> Option<EdgesBlock> {
        self.syntax.children().find_map(EdgesBlock::cast)
    }
}

impl PowerDecl {
    /// The power net's name (`power PlantMain:` -> `PlantMain`).
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn name(&self) -> Option<String> {
        header_ident_after_keyword(&self.syntax)
    }

    /// The `sources:`/`buses:`/`ties:`/`loads:` header fields.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    // frob:waive TEST002 reason="rust collector fails fast on lib-less fuzz/ crate, killing test-evidence collection repo-wide; binding+tests are real, see FROBLEMS 2026-07-18"
    pub fn fields(&self) -> Vec<Field> {
        self.syntax.children().filter_map(Field::cast).collect()
    }

    /// The `feeders:` block, if declared (charter 43 sec. 1): the
    /// bus-to-bus apparatus edges (services, generators, transformers,
    /// feeders, protective devices), typed identically to a flownet
    /// `edges:` block / a structure's `transfers:` block.
    #[must_use]
    // frob:doc docs/modules/regolith-syntax.md#ast
    pub fn feeders(&self) -> Option<EdgesBlock> {
        self.syntax.children().find_map(EdgesBlock::cast)
    }
}

#[cfg(test)]
mod tests {
    use super::{AstNode, Decl, File};
    use crate::syntax_kind::SyntaxKind;

    #[test]
    // frob:tests crates/regolith-syntax/src/ast.rs::MediumDecl.phase kind="unit"
    // frob:tests crates/regolith-syntax/src/ast.rs::File.decls kind="unit"
    // frob:tests crates/regolith-syntax/src/ast.rs::File.mediums kind="unit"
    // frob:tests crates/regolith-syntax/src/ast.rs::File.fluid_requires kind="unit"
    fn fluorite_surface_exposes_typed_medium_flownet_and_require() {
        // fluorite/02 sec. 1/4/6: medium + flownet(edges/states) +
        // top-level require, all as typed CST nodes with lossless
        // round-trip (WO-31 deliverable 2).
        let src = "import std.fluorite (Pipe, Valve)\n\
                   medium Water: liquid\n\
                   \x20\x20\x20\x20props: registry(freshwater_25c)\n\
                   flownet Loop(medium=Water):\n\
                   \x20\x20\x20\x20reference: ambient(101kPa, 298K)\n\
                   \x20\x20\x20\x20nodes: a, b\n\
                   \x20\x20\x20\x20edges:\n\
                   \x20\x20\x20\x20\x20\x20\x20\x20pipe: Pipe(from=line.run) (a -> b)\n\
                   \x20\x20\x20\x20states:\n\
                   \x20\x20\x20\x20\x20\x20\x20\x20state mode in {idle, run}\n\
                   require Margin:\n\
                   \x20\x20\x20\x20margin: fluids.dp(a -> b) <= 15kPa\n";
        let file_path = camino::Utf8PathBuf::from("t.fluo");
        let parse = crate::parser::parse(src, &file_path);
        assert!(parse.diagnostics().is_empty(), "{:?}", parse.diagnostics());
        // Lossless round-trip (the AD-3 coverage invariant).
        assert_eq!(parse.syntax().text().to_string(), src);
        let file = File::cast(parse.syntax()).expect("root is File");

        let medium = file.mediums().into_iter().next().expect("one medium");
        assert_eq!(medium.name().as_deref(), Some("Water"));
        assert_eq!(medium.phase().as_deref(), Some("liquid"));

        let flownet = file.flownets().into_iter().next().expect("one flownet");
        assert_eq!(flownet.name().as_deref(), Some("Loop"));
        let edges = flownet.edges().expect("edges block");
        let edge = edges.edges().into_iter().next().expect("one edge");
        assert_eq!(edge.name(), "pipe");
        assert!(edge.value().is_some(), "edge constructor is a typed value");
        let states = flownet.states().expect("states block");
        assert_eq!(states.states().len(), 1);

        let req = file
            .fluid_requires()
            .into_iter()
            .next()
            .expect("one require");
        assert_eq!(req.claims().len(), 1);
        // A top-level require is NOT a plain Decl.
        assert!(file.decls().is_empty(), "no generic Decls in this file");
    }

    #[test]
    fn can_cast_matches_kind() {
        assert!(File::can_cast(SyntaxKind::File));
        assert!(!File::can_cast(SyntaxKind::Decl));
        assert!(Decl::can_cast(SyntaxKind::Decl));
    }

    #[test]
    fn file_exposes_imports_and_decls_in_source_order() {
        let src = "import a.b\npart wall:\n    x: 1\nprofile p:\n    y: 2\n";
        let file_path = camino::Utf8PathBuf::from("t.hema");
        let parse = crate::parser::parse(src, &file_path);
        let file = File::cast(parse.syntax()).expect("root is File");
        assert_eq!(file.imports().len(), 1);
        assert_eq!(file.decls().len(), 2);
    }

    #[test]
    // frob:tests crates/regolith-syntax/src/ast.rs::WaiveBlock.expires kind="unit"
    // frob:tests crates/regolith-syntax/src/ast.rs::WaiveBlock.has_evidence kind="unit"
    // frob:tests crates/regolith-syntax/src/ast.rs::Decl.waivers kind="unit"
    fn waive_block_exposes_target_scope_basis_and_evidence() {
        let src = "part p:\n    waive dfm(min_web) on milled.wall:\n        basis: \"qual unit VR-081\"\n        by test(vr081)\n        expires: 2027-01-01\n";
        let file_path = camino::Utf8PathBuf::from("t.hema");
        let parse = crate::parser::parse(src, &file_path);
        let file = File::cast(parse.syntax()).expect("root is File");
        let decl = file.decls().into_iter().next().expect("one decl");
        let wb = decl.waivers().into_iter().next().expect("one waiver");
        assert_eq!(wb.target(), "dfm(min_web)");
        assert_eq!(wb.scope().as_deref(), Some("milled.wall"));
        assert_eq!(wb.basis().as_deref(), Some("qual unit VR-081"));
        assert!(wb.has_evidence(), "the `by` clause is evidence");
        assert_eq!(wb.evidence().as_deref(), Some("test(vr081)"));
        assert_eq!(wb.expires().as_deref(), Some("2027-01-01"));
    }

    #[test]
    fn an_unscoped_basis_less_waiver_reports_none() {
        let src = "part p:\n    waive Group.claim:\n        note: 1\n";
        let file_path = camino::Utf8PathBuf::from("t.hema");
        let parse = crate::parser::parse(src, &file_path);
        let file = File::cast(parse.syntax()).expect("root is File");
        let decl = file.decls().into_iter().next().expect("one decl");
        let wb = decl.waivers().into_iter().next().expect("one waiver");
        assert_eq!(wb.target(), "Group.claim");
        assert_eq!(wb.scope(), None);
        assert_eq!(wb.basis(), None);
        assert!(!wb.has_evidence());
    }

    #[test]
    // frob:tests crates/regolith-syntax/src/ast.rs::SensePair.from_name kind="unit"
    // frob:tests crates/regolith-syntax/src/ast.rs::SensePair.to_name kind="unit"
    // frob:tests crates/regolith-syntax/src/ast.rs::DomainSet.items kind="unit"
    fn flownet_edge_sense_and_state_domain_are_readable() {
        let src = "flownet Loop(medium=Water):\n\
                   \x20\x20\x20\x20reference: tank_in\n\
                   \x20\x20\x20\x20nodes: tank_in, tank_out\n\
                   \x20\x20\x20\x20edges:\n\
                   \x20\x20\x20\x20\x20\x20\x20\x20pump: Pump(from=p.run) (tank_in -> tank_out)\n\
                   \x20\x20\x20\x20states:\n\
                   \x20\x20\x20\x20\x20\x20\x20\x20pump.state in {off, on}\n\
                   \x20\x20\x20\x20\x20\x20\x20\x20state mode in {idle, active}\n";
        let file_path = camino::Utf8PathBuf::from("t.fluo");
        let parse = crate::parser::parse(src, &file_path);
        let file = File::cast(parse.syntax()).expect("root is File");
        let net = file.flownets().into_iter().next().expect("one flownet");

        let edge = net.edges().expect("edges block").edges().remove(0);
        let sense = edge.sense().expect("sense pair");
        assert_eq!(sense.from_name().as_deref(), Some("tank_in"));
        assert_eq!(sense.to_name().as_deref(), Some("tank_out"));

        let states = net.states().expect("states block").states();
        let domains: Vec<Vec<String>> = states
            .iter()
            .map(|s| s.domain().expect("typed domain").items())
            .collect();
        assert_eq!(domains[0], vec!["off".to_string(), "on".to_string()]);
        assert_eq!(domains[1], vec!["idle".to_string(), "active".to_string()]);
    }

    /// fluorite/02 sec. 2: `interface FluidPort<...>` reuses the
    /// existing generic-interface machinery unmodified; `through`/
    /// `across` flow-role markers are ordinary bareword field values
    /// (no new keyword), so the header, the `flow:`/`roles:` blocks,
    /// and every single-name field line parse cleanly with no parse
    /// diagnostics.
    #[test]
    // frob:tests crates/regolith-syntax/src/ast.rs::Decl.kind_keyword kind="unit"
    fn fluid_port_interface_reuses_existing_machinery() {
        let src = "interface FluidPort<m: medium, dia: length>:\n\
                   \x20\x20\x20\x20flow:\n\
                   \x20\x20\x20\x20\x20\x20\x20\x20mdot: through\n\
                   \x20\x20\x20\x20roles:\n\
                   \x20\x20\x20\x20\x20\x20\x20\x20bore: circular(dia)\n";
        let file_path = camino::Utf8PathBuf::from("t.fluo");
        let parse = crate::parser::parse(src, &file_path);
        assert_eq!(parse.syntax().text().to_string(), src);
        assert!(parse.diagnostics().is_empty(), "{:?}", parse.diagnostics());
        let file = File::cast(parse.syntax()).expect("root is File");
        let decl = file.decls().into_iter().next().expect("one decl");
        assert_eq!(decl.kind_keyword(), Some(SyntaxKind::InterfaceKw));
    }
}
