//! Typed AST: zero-cost view structs over the CST (rust-analyzer
//! pattern, AD-3). In the built system these are GENERATED by an xtask
//! from an ungrammar file; the hand-written views below are the
//! scaffold seed and document the shape the codegen must produce.
//!
//! Substrate reference: `docs/mech/02`, `docs/elec/07`. Each view wraps
//! a [`SyntaxNode`] of a specific [`SyntaxKind`] and exposes typed
//! child accessors; trivia is skipped at this layer.

use crate::cst::SyntaxNode;
use crate::syntax_kind::SyntaxKind;

/// A typed view over a CST node of a known kind. Cheap: holds one
/// `SyntaxNode` (an `Rc`-backed handle).
pub trait AstNode {
    /// True if a node of this `kind` can be viewed as `Self`.
    fn can_cast(kind: SyntaxKind) -> bool
    where
        Self: Sized;
    /// Wrap `node` if its kind matches, else `None`.
    fn cast(node: SyntaxNode) -> Option<Self>
    where
        Self: Sized;
    /// The underlying CST node.
    fn syntax(&self) -> &SyntaxNode;
}

/// Declare a typed AST view struct over a single [`SyntaxKind`]. Keeps
/// the boilerplate identical across views (the codegen target).
macro_rules! ast_node {
    ($(#[$m:meta])* $name:ident => $kind:ident) => {
        $(#[$m])*
        #[derive(Debug, Clone)]
        pub struct $name {
            syntax: SyntaxNode,
        }
        impl AstNode for $name {
            fn can_cast(kind: SyntaxKind) -> bool {
                kind == SyntaxKind::$kind
            }
            fn cast(node: SyntaxNode) -> Option<Self> {
                if node.kind() == SyntaxKind::$kind {
                    Some($name { syntax: node })
                } else {
                    None
                }
            }
            fn syntax(&self) -> &SyntaxNode {
                &self.syntax
            }
        }
    };
}

ast_node!(
    /// The file root: imports followed by top-level declarations.
    File => File
);
ast_node!(
    /// An `import` statement.
    ImportStmt => ImportStmt
);
ast_node!(
    /// A top-level declaration (`part`, `interface`, `system`, ...).
    Decl => Decl
);
ast_node!(
    /// A `key: value` field.
    Field => Field
);
ast_node!(
    /// A `name = Ctor(args)` construction statement.
    CtorStmt => CtorStmt
);
ast_node!(
    /// A `require <Group>:` claim group.
    RequireClaim => RequireClaim
);
ast_node!(
    /// A `then [label] [on <region>]:` scope.
    ThenScope => ThenScope
);
ast_node!(
    /// A `budget ...:` statement.
    BudgetStmt => BudgetStmt
);
ast_node!(
    /// A `waive ...:` block.
    WaiveBlock => WaiveBlock
);
ast_node!(
    /// A `policy:` block.
    PolicyBlock => PolicyBlock
);
ast_node!(
    /// A `locked:` block.
    LockedBlock => LockedBlock
);
ast_node!(
    /// A binary expression (comparison, `+ - * /`).
    BinExpr => BinExpr
);
ast_node!(
    /// A unary expression: `-x`, or a bound-only claim comparator
    /// (`>= certified`) with an implicit subject.
    UnaryExpr => UnaryExpr
);
ast_node!(
    /// A parenthesized expression.
    ParenExpr => ParenExpr
);
ast_node!(
    /// A call expression: callee (`NameRef`/`Path`) plus an `ArgList`.
    CallExpr => CallExpr
);
ast_node!(
    /// A call's argument list.
    ArgList => ArgList
);
ast_node!(
    /// A number literal with an adjacent unit (`5 mm`, `1 V`).
    QuantityLit => QuantityLit
);
ast_node!(
    /// A single dotted-path-free name reference.
    NameRef => NameRef
);
ast_node!(
    /// A dotted path reference (`a.b.c`).
    Path => Path
);
ast_node!(
    /// A `[a, b]` closed real interval.
    IntervalExpr => IntervalExpr
);
ast_node!(
    /// A `[i .. j]` half-open index range.
    RangeExpr => RangeExpr
);
ast_node!(
    /// A value source wrapper (`default`/`derived`/`free`/`allocated`,
    /// or `in [...]`).
    ValueSource => ValueSource
);
ast_node!(
    /// A bare cause keyword leaf (`default`, `derived`, `free`,
    /// `allocated`).
    CauseValue => CauseValue
);
ast_node!(
    /// A `+- N %` tolerance suffix on a value.
    ToleranceExpr => ToleranceExpr
);
ast_node!(
    /// A `during <expr>` clause.
    DuringClause => DuringClause
);
ast_node!(
    /// A use-site generic instantiation (`TappedHole<M3>`): a head
    /// name plus a [`GenericArgs`] list (INV-11 use site).
    InstExpr => InstExpr
);
ast_node!(
    /// A use-site generic-argument list (`<M3>`, `<3, 8>`).
    GenericArgs => GenericArgs
);
ast_node!(
    /// A declaration-header generic-parameter list (`<screw: thread,
    /// n: int>`).
    GenericParams => GenericParams
);

impl InstExpr {
    /// The instantiation head name: the type constructor being
    /// instantiated (e.g. `PatternOf`), read from the head
    /// `NameRef`/`Path` child node.
    #[must_use]
    pub fn head_name(&self) -> String {
        self.syntax
            .children()
            .find(|c| matches!(c.kind(), SyntaxKind::NameRef | SyntaxKind::Path))
            .map_or_else(String::new, |head| name_path_text(&head))
    }

    /// The instantiation's typed argument list, if present.
    #[must_use]
    pub fn args(&self) -> Option<GenericArgs> {
        self.syntax.children().find_map(GenericArgs::cast)
    }

    /// The number of top-level arguments (`PatternOf<TappedHole<M3>>`
    /// has arity 1; `Decoder<3, 8>` has arity 2).
    #[must_use]
    pub fn arity(&self) -> usize {
        self.args().map_or(0, |a| a.arity())
    }
}

impl GenericArgs {
    /// The number of top-level (outermost-angle) arguments, counted as
    /// depth-1 commas + 1 when any content is present (nested `<...>`
    /// commas do not count).
    #[must_use]
    pub fn arity(&self) -> usize {
        top_level_arity(&self.syntax)
    }
}

impl GenericParams {
    /// The number of declared parameters (top-level comma count + 1 when
    /// non-empty), the arity a use site must match (INV-11).
    #[must_use]
    pub fn arity(&self) -> usize {
        top_level_arity(&self.syntax)
    }
}

/// Count the top-level arguments/parameters inside an angle-bracketed
/// list node (`GenericArgs`/`GenericParams`): depth-1 commas + 1 when
/// the list holds any non-trivia content, else 0. The node's own outer
/// `<`/`>` open and close the depth; nested `<...>` commas are skipped.
fn top_level_arity(node: &SyntaxNode) -> usize {
    let mut depth = 0i32;
    let mut commas = 0usize;
    let mut saw_content = false;
    for tok in node
        .children_with_tokens()
        .filter_map(rowan::NodeOrToken::into_token)
    {
        match tok.kind() {
            SyntaxKind::Lt => depth += 1,
            SyntaxKind::Gt => depth -= 1,
            SyntaxKind::Comma if depth == 1 => commas += 1,
            SyntaxKind::Whitespace | SyntaxKind::Newline | SyntaxKind::Comment => {}
            _ if depth >= 1 => saw_content = true,
            _ => {}
        }
    }
    // Nested instantiation arguments live in child `InstExpr` nodes (not
    // direct tokens), so also treat any child node as content.
    if node.children().next().is_some() {
        saw_content = true;
    }
    if saw_content {
        commas + 1
    } else {
        0
    }
}

impl Field {
    /// The field's name token text (the leading identifier; dotted
    /// paths are joined with `.`).
    #[must_use]
    pub fn name(&self) -> String {
        name_path_text(&self.syntax)
    }

    /// The field's value node, skipping the name/colon/tail trivia:
    /// the first non-trivia, non-`OpaqueIsland` child node.
    #[must_use]
    pub fn value(&self) -> Option<SyntaxNode> {
        first_value_child(&self.syntax)
    }
}

impl BudgetStmt {
    /// The budget's name token text (dotted paths joined with `.`).
    #[must_use]
    pub fn name(&self) -> String {
        name_path_text(&self.syntax)
    }

    /// The budget's limit value node (see [`Field::value`]).
    #[must_use]
    pub fn value(&self) -> Option<SyntaxNode> {
        first_value_child(&self.syntax)
    }
}

impl CtorStmt {
    /// The statement's name token text (dotted paths joined with `.`).
    #[must_use]
    pub fn name(&self) -> String {
        name_path_text(&self.syntax)
    }

    /// The statement's value node (see [`Field::value`]).
    #[must_use]
    pub fn value(&self) -> Option<SyntaxNode> {
        first_value_child(&self.syntax)
    }
}

impl RequireClaim {
    /// Each claim line in this group's body (parsed as [`Field`]s:
    /// `subject: predicate`).
    #[must_use]
    pub fn claims(&self) -> Vec<Field> {
        self.syntax.children().filter_map(Field::cast).collect()
    }
}

impl BinExpr {
    /// The left operand.
    #[must_use]
    pub fn lhs(&self) -> Option<SyntaxNode> {
        self.syntax.children().next()
    }

    /// The right operand.
    #[must_use]
    pub fn rhs(&self) -> Option<SyntaxNode> {
        self.syntax.children().nth(1)
    }
}

impl QuantityLit {
    /// The literal's unit spelling (the `Ident` token immediately
    /// after the number).
    #[must_use]
    pub fn unit_text(&self) -> Option<String> {
        self.syntax
            .children_with_tokens()
            .filter_map(rowan::NodeOrToken::into_token)
            .find(|t| t.kind() == SyntaxKind::Ident)
            .map(|t| t.text().to_string())
    }
}

/// Join a `name`/`ctor` statement's leading `Ident (. Ident)*` name
/// tokens with `.` (the accessor both [`Field::name`] and
/// [`CtorStmt::name`] share).
fn name_path_text(node: &SyntaxNode) -> String {
    node.children_with_tokens()
        .filter_map(rowan::NodeOrToken::into_token)
        .take_while(|t| matches!(t.kind(), SyntaxKind::Ident | SyntaxKind::Dot))
        .map(|t| t.text().to_string())
        .collect()
}

/// The first child node of a `Field`/`CtorStmt` that is not the
/// trailing lossless-sweep `OpaqueIsland` (the recognized value, when
/// the grammar classified one).
fn first_value_child(node: &SyntaxNode) -> Option<SyntaxNode> {
    node.children()
        .find(|c| c.kind() != SyntaxKind::OpaqueIsland)
}

impl Decl {
    /// The declaration keyword (`part`, `interface`, `system`, ...).
    #[must_use]
    pub fn kind_keyword(&self) -> Option<SyntaxKind> {
        self.syntax
            .children_with_tokens()
            .filter_map(rowan::NodeOrToken::into_token)
            .map(|t| t.kind())
            .find(|k| !k.is_trivia())
    }

    /// The declaration's own name: the first `Ident` token in the
    /// header line (before any generic-parameter `<...>` list, which
    /// this WO does not further decompose -- see the report note).
    #[must_use]
    pub fn name(&self) -> Option<String> {
        self.syntax
            .children_with_tokens()
            .filter_map(rowan::NodeOrToken::into_token)
            .find(|t| t.kind() == SyntaxKind::Ident)
            .map(|t| t.text().to_string())
    }

    /// The declaration's structured statements (fields, ctor
    /// statements, `then`/`require`/`budget`/`waive`/`policy`/`locked`
    /// blocks); domain-specific statements remain opaque and are
    /// omitted here (call [`AstNode::syntax`] and filter
    /// `OpaqueIsland` children directly to see everything).
    #[must_use]
    pub fn fields(&self) -> Vec<Field> {
        self.syntax.children().filter_map(Field::cast).collect()
    }

    /// The declaration's `require <Group>:` claim groups.
    #[must_use]
    pub fn claims(&self) -> Vec<RequireClaim> {
        self.syntax
            .children()
            .filter_map(RequireClaim::cast)
            .collect()
    }

    /// The declaration's structured `budget ...:` statements.
    #[must_use]
    pub fn budgets(&self) -> Vec<BudgetStmt> {
        self.syntax
            .children()
            .filter_map(BudgetStmt::cast)
            .collect()
    }
}

impl File {
    /// The import statements at the head of the file.
    #[must_use]
    pub fn imports(&self) -> Vec<ImportStmt> {
        self.syntax
            .children()
            .filter_map(ImportStmt::cast)
            .collect()
    }

    /// The top-level declarations of the file.
    #[must_use]
    pub fn decls(&self) -> Vec<Decl> {
        self.syntax.children().filter_map(Decl::cast).collect()
    }
}

#[cfg(test)]
mod tests {
    use super::{AstNode, Decl, File};
    use crate::syntax_kind::SyntaxKind;

    #[test]
    fn can_cast_matches_kind() {
        assert!(File::can_cast(SyntaxKind::File));
        assert!(!File::can_cast(SyntaxKind::Decl));
        assert!(Decl::can_cast(SyntaxKind::Decl));
    }

    #[test]
    fn file_exposes_imports_and_decls_in_source_order() {
        let src = "import a.b\npart wall:\n    x: 1\nprofile p:\n    y: 2\n";
        let file_path = camino::Utf8PathBuf::from("t.hem");
        let parse = crate::parser::parse(src, &file_path);
        let file = File::cast(parse.syntax()).expect("root is File");
        assert_eq!(file.imports().len(), 1);
        assert_eq!(file.decls().len(), 2);
    }
}
