"""GENERATED by `make codes` (D247/WO-131) -- never hand-edit.

Single-sourced from `crates/regolith-diag/src/code.rs` + `explain.rs`
(the ONE registry, D247.1) via `regolith-export-codes`. A Python
failure kind that does not name one of these constants is a build
error, not a bare string (D247.1) -- see `tools/health/diag_codes.py`
for the sweep that enforces it.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class CodeEntry(BaseModel):
    """One diagnostic code's rendered form + explain content."""

    model_config = ConfigDict(frozen=True)

    code: str
    symbol: str
    family: str
    meaning: str
    why: str
    fix: str
    example: str | None
    authored: bool


# One CodeEntry per registered code, in registry order.
ALL: tuple[CodeEntry, ...] = (
    CodeEntry(
        code="E0102",
        symbol="EQUALITY_ON_CONTINUOUS",
        family="Parse",
        meaning="`==` (structural equality) was used to compare a CONTINUOUS quantity (a real-valued measurement: length, voltage, pressure, ...).",
        why="Continuous quantities are produced by measurement, solve, or simulation and never land on an exact bit-identical value twice -- `==` between two continuous values is either always false (a guaranteed-failing assertion the author almost certainly did not intend) or a coincidence that will not survive the next solve. The language bans it at compile time rather than letting it silently pass or silently fail (regolith/02).",
        fix="Compare within a tolerance instead: use a `within [lo, hi]` claim, or an explicit `abs(a - b) < tol` form. Discrete/enum-valued quantities (an index, a boolean, a named state) are unaffected -- `==` is still legal there.",
        example="`length == 10mm` (rejected, E0102) becomes `length within [9.9mm, 10.1mm]`.",
        authored=True,
    ),
    CodeEntry(
        code="E0901",
        symbol="FAB_SET_INCOMPLETE",
        family="Emission",
        meaning="A shipped gerber/fab-package set is missing a required charter 41 sec. 3 layer (e.g. a copper layer, soldermask, or drill file).",
        why="The emission backend (`regolith.backends.elec_fabset`) checks the REQUIRED_FAB_SET against what was actually written before letting the package be called complete -- a fab house cannot manufacture from a partial layer set, so this is refused at emission time rather than discovered at the fab house.",
        fix="Re-run the board emission for every declared layer (check the board's stackup declares the layer, and that its producer ran without error); the diagnostic names exactly which required layer(s) are missing.",
        example="A 2-layer board whose bottom-copper producer silently skipped (an earlier IR gap) ships only top copper + drill -> E0901 names `B.Cu` as the missing layer.",
        authored=True,
    ),
    CodeEntry(
        code="E0902",
        symbol="DRAFTING_AUDIT_REFUSED",
        family="Emission",
        meaning="A drafting-rule check failed on a GATING sheet of a drawing package (a title-block, dimension, or tolerance rule the audit considers release-blocking).",
        why="`regolith.backends.drawings.audit` runs every attached drafting rule over every sheet before a drawing package is allowed to ship; a rule failing on a sheet marked gating (not `_sheet_is_non_gating`) means the drawing does not meet the package's own declared standard, so shipping it would hand a fabricator/assembler an unreliable drawing.",
        fix="Read the named rule and sheet in the message, fix the underlying drawing content (missing dimension, wrong title-block field, ...), and re-run the audit. If the sheet is genuinely non-gating, mark it so explicitly rather than relying on the audit to guess.",
        example="A detail sheet missing a required GD&T datum callout fails rule `datum.required` -> E0902 names the rule, the sheet's drawing number, and the failing message.",
        authored=True,
    ),
    CodeEntry(
        code="E0903",
        symbol="ARTIFACT_INDEX_DRIFT",
        family="Emission",
        meaning="A shipped package's artifact index (the manifest's declared file list) disagrees with the files the package actually wrote to disk.",
        why="A manifest is the receiver's promise of exactly what shipped; an index that lists a file never written (or omits one that was) is a silent integrity gap that hash/signature checks alone do not catch, since they verify files the manifest names, not the completeness of the naming itself.",
        fix="Regenerate the manifest from the actual output directory rather than a stale in-memory file list; if a producer is skipping a file it should emit, fix the producer.",
        example="RESERVED (WO-131 escalation F-WO131-1): no current producer raises this code yet, so no worked example is authored. The mechanism (registry entry, family, this explain content) is in place for the producer that closes the gap.",
        authored=True,
    ),
    CodeEntry(
        code="E1001",
        symbol="UNEXPLAINED_OVERRIDE",
        family="Injection",
        meaning="RESERVED for WO-129A (D246): an override applied through the D243 injection channel with no author/reason recorded.",
        why="The override channel exists to let a human deliberately supersede a computed value with an explicit, attributed decision (D243); an override with no author/reason attached is indistinguishable from an accidental or malicious value injection, so D246 refuses it rather than accept an unattributed claim override.",
        fix="Not yet implemented by this WO -- WO-129A wires the raise site. The fix, once implemented, will be: supply the required `author=`/`reason=` fields on the override declaration.",
        example="RESERVED -- worked example lands with WO-129A.",
        authored=True,
    ),
    CodeEntry(
        code="E1002",
        symbol="SOURCE_ONLY_TARGET_REFUSED",
        family="Injection",
        meaning="RESERVED for WO-129A (D246): an override names a SOURCE-only claim as its target -- the D246 claims/evidence boundary.",
        why="D246 draws a hard line between a claim that is pure declared SOURCE (never independently checked) and one backed by evidence; letting an override silently reclassify a source-only claim as if it had evidence would let an unverified assertion masquerade as a proven one.",
        fix="Not yet implemented by this WO -- WO-129A wires the raise site. The fix, once implemented, will be: target an evidence-backed claim, or promote the source claim to an evidence-backed one first.",
        example="RESERVED -- worked example lands with WO-129A.",
        authored=True,
    ),
    CodeEntry(
        code="E1003",
        symbol="UNRESOLVABLE_OVERRIDE_TARGET",
        family="Injection",
        meaning="RESERVED for WO-129A (D246): an override names a target that cannot be resolved anywhere in the build.",
        why="An override that points at nothing is either a typo or stale (the target was renamed/removed since the override was written); silently ignoring it would let the override rot without anyone noticing the value it was meant to control is now unsupervised.",
        fix="Not yet implemented by this WO -- WO-129A wires the raise site. The fix, once implemented, will be: correct the target ref, or remove the stale override.",
        example="RESERVED -- worked example lands with WO-129A.",
        authored=True,
    ),
    CodeEntry(
        code="E1101",
        symbol="EXPECTATION_PROVENANCE_UNRESOLVED",
        family="BringUp",
        meaning="A bring-up harness's `expected_signals.json` carries a provenance ref that does not resolve inside the package, or a populated expected value with no units attached (D224).",
        why="A bring-up expectation exists to let a technician verify a measured signal against a declared, TRACEABLE value; a provenance ref that resolves to nothing means the expected value's origin cannot be audited, and a unitless populated value is neither a value-with-units nor an honest named absence (D224's units invariant, charter 40 sec. 3) -- both are refused rather than shipped ambiguous.",
        fix="Fix the provenance ref to name a claim that actually exists in the package, or attach the missing `units` field to every populated expected value.",
        example='`expected_signals.json` row `{"channel": "VCC", "expected": "claim:Board.vcc_out"}` where no claim named `Board.vcc_out` exists in the package -> E1101 names the channel and the unresolved ref.',
        authored=True,
    ),
    CodeEntry(
        code="E1102",
        symbol="RELEASE_GATE_REFUSES_DEBUG_EVIDENCE",
        family="BringUp",
        meaning="A ship manifest built with `profile=debug` was presented as release-gate evidence (D237.1).",
        why="A debug build's provenance chain (optimizer settings, symbol stripping, evidence rollup) is not the same artifact as what ships to a customer; accepting a debug package as release proof would let a downstream gate (an acceptance test, a jig-mating check) certify against the wrong artifact. Debug packages stay fully verifiable (`verify_manifest`/`verify_file_hashes`) -- only their ELIGIBILITY as release evidence is refused.",
        fix="Ship (or re-ship) with `profile=release` before presenting the package as release-gate evidence; keep the debug package for its own purpose (bring-up, debugging) instead.",
        example='`release_gate_refuses_debug_evidence(manifest)` where `manifest.profile == "debug"` -> E1102 names the profile and cites D237.1.',
        authored=True,
    ),
    CodeEntry(
        code="E1103",
        symbol="TAP_MAP_DISAGREEMENT",
        family="BringUp",
        meaning="A debug tap map disagrees with the artifact it claims to describe (`tap_map_artifact_mismatch`, `regolith.backends.debug_taps`).",
        why="A tap map is the bring-up harness's promise of which physical test point corresponds to which internal signal; a tap map that no longer matches the artifact it was generated against (a stale map after a layout change, or a hand-edited map) would send a technician probing the wrong point -- refused rather than trusted.",
        fix="Regenerate the tap map from the current artifact rather than reusing a cached one; if the map was hand-edited, verify every entry against the current layout before re-attaching it.",
        example="A tap map built against board rev A, reused unchanged after a rev B layout shuffled net names -> E1103 names the artifact digest mismatch.",
        authored=True,
    ),
    CodeEntry(
        code="E0101",
        symbol="INCOMPATIBLE_QUANTITIES",
        family="Parse",
        meaning="arithmetic between incompatible quantities.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0103",
        symbol="INTERVAL_RANGE_CONFUSION",
        family="Parse",
        meaning="a `[a, b]` interval and a `[i .. j]` index range were confused: both separators in one bracket, or a range endpoint carrying a unit/fractional literal (regolith/02 sec. 3).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0104",
        symbol="ILLEGAL_LOG_SUM",
        family="Parse",
        meaning="an illegal logarithmic-unit sum: after cancelling subtracted references against added ones, more than one reference survives (`dBm + dBm`) or a subtracted reference is uncancelled (regolith/02 sec. 5a; the linear product/quotient is not a valid quantity).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0105",
        symbol="COMBINATIONAL_CYCLE",
        family="Parse",
        meaning="a combinational (instantaneous `=`) cycle entirely within one clock/continuous domain, with no converter or register delta to break it (an algebraic loop, INV-16). A cross-domain edge always passes through a converter (a ZOH delta by type), so no zero-delay cycle can cross the continuous/discrete boundary; this code flags only a within-domain loop the source actually declares.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0106",
        symbol="RUN_MISSING_ENDPOINT",
        family="Parse",
        meaning="a `run <name>:` line inside a `harness:` block (D99, WO-34 deliverable 1) whose header does not spell both a `from` and a `to` endpoint. Parse-time structural validation only (required-field presence): it does not resolve the endpoint refs (that is elaboration's job, WO-34 deliverable 2) -- only that the two keywords are both present, so a run with no path to extract a length over is rejected as close to the source as possible.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0107",
        symbol="SELECT_EMPTY_CANDIDATE_LIST",
        family="Parse",
        meaning="`by select(...)` (WO-56, D161) declared with an empty candidate list. A choice point over zero candidates has nothing to search, so it is rejected as a structural, parse-adjacent malformation (same L1 tier as `RUN_MISSING_ENDPOINT`) rather than surfacing as an empty domain at the optimizer.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0201",
        symbol="IMPOSER_FREE_SUBNET",
        family="FluidNet",
        meaning="a flownet subnet with no pressure imposer (reference, regulator, pump curve, or `Imposer`): the network is singular by construction and is rejected at COMPILE time, never at solve time (fluorite/02 sec. 4, the AD-23 fluid discipline).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0202",
        symbol="UNJOINED_TERMINAL",
        family="FluidNet",
        meaning="a declared flownet node that no edge joins and that is not the reference (an unjoined terminal in the fluorite terminal ledger, fluorite/02 sec. 4): a dangling node cannot participate in the solved network.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0203",
        symbol="TRANSIENT_NO_COMPLIANCE",
        family="FluidNet",
        meaning="a transient/volume-budget claim (`fluids.volume_consumed`, `peak(...)`) names an edge with neither a compliance record nor an extractable wall (fluorite/03 sec. 1): the claim would be undischargeable, so lowering rejects it at compile time rather than leaving it to fail at solve time. WO-32 deliverable 5.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0204",
        symbol="SPACE_NOT_IN_CIRCULATION",
        family="FluidNet",
        meaning="a circulation net declares no `edges:` and no `reference:` (calcite/03 sec. 3, the circulation discipline's whole-net imposer-free-subnet analog; WO-47 deliverable 4). The per-space unjoined-terminal half of the sec. 3 ledger needs a connectivity extraction this front-end layer does not have (see `regolith_lower::calcite`'s module doc comment).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0205",
        symbol="CIRCULATION_UNREACHABLE",
        family="FluidNet",
        meaning="a space cannot reach a reference (exit) through circulation edges (calcite/03 sec. 3, reference reachability). NOT YET DECIDABLE at this front-end layer without a new reachability traversal beyond the existing imposer-counting `net_core` (WO-47 close-out cut; see the crate's `calcite` module doc comment for the escalation).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0206",
        symbol="EGRESS_EDGE_UNDECLARED",
        family="FluidNet",
        meaning="an egress edge on a required path with zero/undeclared width or `path_length` (calcite/03 sec. 3).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0207",
        symbol="MEMBER_UNSUPPORTED",
        family="FluidNet",
        meaning="a member cannot reach a support through transfer edges (calcite/03 sec. 3, the load-LEAK check). Same reachability cut as `E0205` -- see `CIRCULATION_UNREACHABLE`'s doc comment.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0208",
        symbol="STRUCTURE_NO_SUPPORT",
        family="FluidNet",
        meaning="a structure subnet has no `support:` node (calcite/03 sec. 3, the load-path discipline's imposer-counting analog; WO-47 deliverable 4).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0209",
        symbol="MEMBER_UNJOINED_OR_TRIBUTARY_MISMATCH",
        family="FluidNet",
        meaning="a member end/bearing terminal is unjoined and not `unloaded`, or declared tributary shares fail to partition their loaded surface (calcite/03 sec. 3; two conditions share one code per the spec's own allocation).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0210",
        symbol="MEDIUM_MISMATCH",
        family="FluidNet",
        meaning="FOPEN-1 (fluorite/04, WO-49): a flownet edge resolves, through its `from=<part>.<role>` ref, to a component with a declared `impl FluidPort<medium=...>` binding whose medium disagrees with the flownet's own `medium=` header -- a mixed- medium subnet, rejected at compile time before payload construction (fluorite/02 sec. 1, the one-medium-per-subnet rule). Names both media and both declaration sites. (Landed as E0204 on the WO-49 branch; renumbered at integration -- the ratified calcite spec owns E0204-E0209.).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0211",
        symbol="POINT_LOAD_NEEDS_STATION",
        family="FluidNet",
        meaning="WO-85/D194: a concentrated (force/moment-unit) load row targets a bare MEMBER with no `@<station>` refinement (the location is ambiguous: name a station, `G1@0.5`, or target a joint/support instead -- never inferred), or its declared station is malformed / outside the normalized `[0, 1]` range. Constructive: the message names both valid spellings.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0301",
        symbol="AMBIGUOUS_SELECTION",
        family="References",
        meaning="an entity query matched more than one entity.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0302",
        symbol="BORROW_CONFLICT",
        family="References",
        meaning="conflicting borrow of an owned region.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0303",
        symbol="UNRESOLVED_FIELD_REFERENCE",
        family="References",
        meaning="WO-33 D98: a claim projection (`max`/`min`/`at`/ `slope`) names a field no `compute` claim in scope declares (the unresolved-reference family, mirroring `E0301`).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0304",
        symbol="STRUCTURE_CLASS_CHANGE",
        family="References",
        meaning="a change that alters an entity's structure class.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0305",
        symbol="COMPUTE_FIELD_CYCLE",
        family="References",
        meaning="WO-33 D98: a `compute` claim's `over` clause (directly or transitively) references itself as a given, forming a cycle in the computed-field promise DAG. Names the full chain.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0306",
        symbol="RUN_CROSS_NET",
        family="References",
        meaning="WO-34 deliverable 2 (D99): a `harness:` run's `from`/ `to` endpoints resolve to two different nets with no inline component between them. Names both nets.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0307",
        symbol="RUN_DANGLING_ENDPOINT",
        family="References",
        meaning="WO-34 deliverable 2: a `harness:` run's `from`/`to` header text does not spell a non-empty endpoint on one (or both) sides after the `from`/`to` keyword -- a dangling endpoint elaboration cannot resolve. Distinct from the D1 parse-time `E0106` (which only checks the keywords are present): this fires when a keyword is present but names no endpoint text.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0308",
        symbol="RUN_UNKNOWN_BUNDLE",
        family="References",
        meaning="WO-34 deliverable 2: a `harness:` run's `bundle` clause is present but names no group text (an empty/malformed `bundle` line) -- the co-routing group is unknown.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0309",
        symbol="RUN_EXTRACT_FAILED",
        family="References",
        meaning="WO-34 deliverable 2: a `harness:` run's `along` structural ref failed extraction through the shared WO-32 seam (no realized record, an empty path, or an unknown roughness class -- see `regolith_lower::extract::ExtractError`).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0407",
        symbol="BOUNDARY_NOT_SUBSUMED",
        family="Contracts",
        meaning="an enclosing system's boundary envelope is not contained in an imported/child artifact's proven boundary (boundary subsumption, INV-7).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0410",
        symbol="CAPABILITY_VS_DEMAND",
        family="Contracts",
        meaning="a demanded capability exceeds the supplied one.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0420",
        symbol="LEDGER_IMBALANCE",
        family="Contracts",
        meaning="a ledger imbalance (DOF / driver / domain-crossing).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0432",
        symbol="BUDGET_CANNOT_CLOSE",
        family="Contracts",
        meaning="a budget cannot close at its worst-case corner.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0433",
        symbol="REALIZATION_NOT_EXACTLY_ONE",
        family="Contracts",
        meaning="a compute intent is realized by other than exactly one workload (zero or two-or-more), naming both sides (cuprite/05 sec. 1 rule 1, EOPEN-15's realization ledger).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0434",
        symbol="PROMISED_BOUND_UNMATCHED",
        family="Contracts",
        meaning="an interface-side promised bound field has no same-name field on the impl side (or vice versa): conformance windows match by field NAME (WO-26 D104), so a name present on only one side is a constructive diagnostic naming both.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0435",
        symbol="TEMPORAL_REDUCTION_MISSING_COMPARATOR",
        family="Contracts",
        meaning="a temporal REDUCTION claim form (`peak`/`rms`/ `overshoot`) was recognized but carries no trailing external comparator (WO-26 D102): a reduction yields a scalar and always needs one, so a missing comparator is rejected at compile time rather than silently deferred.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0436",
        symbol="TEMPORAL_CONTAINMENT_UNEXPECTED_COMPARATOR",
        family="Contracts",
        meaning="a temporal CONTAINMENT claim form (`settles`/ `stays_within`) was recognized but carries a trailing external comparator (WO-26 D102): a containment's own parameters (`to=` tolerance, `mask=` reference) ARE the acceptance, so a trailing comparator is a shape error, not an extra check.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0437",
        symbol="GENERAL_COMPARISON_MULTIPLE_COMPARATORS",
        family="Contracts",
        meaning="a general comparison claim line carries MORE than one top-level comparator (WO-26 D103: exactly ONE per claim line -- each side is an ordinary quantity expression; chained or double-bounded comparisons have no defined lowering).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0438",
        symbol="COST_CLAIM_MALFORMED",
        family="Contracts",
        meaning="an `mfg.cost(...)` claim's argument list is malformed (WO-54, toolchain/27 sec. 1.1): the accepted shape is `mfg.cost(<subject>[, profile=<name>])` -- a missing/empty subject, a duplicate or empty `profile=`, an unknown keyword, or a stray positional argument is rejected at compile time with the offending argument named, never silently deferred.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0440",
        symbol="SINGULAR_SYSTEM",
        family="Contracts",
        meaning="a numeric L2 solve (rigid statics, stiffness network) hit a singular or rank-deficient system: an under-determined support set, a disconnected stiffness network, or an ill-conditioned assembly (WO-23). Always a diagnostic, never a panic and never a NaN/non-finite value escaping the solve.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0441",
        symbol="SKETCH_RESIDUAL_INCONSISTENT",
        family="Contracts",
        meaning="an exactly-constrained sketch (WO-11's conservative DOF ledger reports residual zero) whose numeric residual closure does not converge to zero: the declared constraints are mutually inconsistent, not merely under/over-counted (WO-23, hematite/07 OPEN-5/D65).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0442",
        symbol="UNBOUND_SEGMENT_LABEL",
        family="Contracts",
        meaning="a profile `constraints:` item references a segment name that no walk-step label binds (D150: segment names are syntax, `a: line right`; a comment is not a binding). The diagnostic is constructive: it names the walk's steps and the label spelling.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0443",
        symbol="UNSUPPORTED_FEATURE_OP",
        family="Contracts",
        meaning="a `then:` feature op has no projection into the v1 `FeatureProgram` op set (WO-51 d2): the part's program is emitted without it and this NAMED warning records the gap -- never silent truncation.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0444",
        symbol="CAVITY_PORT_UNRESOLVED",
        family="Contracts",
        meaning="a `.cavity(inlet=..., outlet=...)` query names a port whose feature binding no `then:` op in the part declares (D152 misuse; constructive: lists the part's op bindings).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0445",
        symbol="CAVITY_CHAIN_INEXPRESSIBLE",
        family="Contracts",
        meaning="a cavity's inlet->outlet feature-op chain contains an op the v1 feature-op set cannot express, so no wetted path can be derived (hematite/07 sec. 2a's named escalation diagnostic -- the syntax-gap criterion, not a reopen).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0446",
        symbol="SELECT_DUPLICATE_CANDIDATE",
        family="Contracts",
        meaning='a `by select(...)` (WO-56, D161) candidate list names the same impl-ref twice. Constructive: the check names the repeated candidate and its subject, since a duplicate candidate can never change a search\'s outcome and is always a authoring mistake (a copy/paste or a stale edit), never a legal "weight" on one alternative to preserve.',
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0447",
        symbol="SKETCH_CLOSE_EDGE_UNDERCONSTRAINED",
        family="Contracts",
        meaning="a walk with a labeled `close` edge (an unconstrained 2-DOF vector, WO-62 D171/AD-32) still carries an explicit `free` segment length: closure gives the close edge both equations, so there is nothing left to determine the other free length -- under-constrained, naming the residual segment and the missing constraint class (assert its length or remove the `close` label). The over-constrained sibling is `E0441`.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0448",
        symbol="SHEET_BLANK_NO_GAUGE_SOURCE",
        family="Contracts",
        meaning="a sheet-metal `Blank(...)` op has no thickness value source: no explicit `thickness=` arg AND no enclosing `process=<proc>(sheet=<t>)` gauge source (WO-62 D171/AD-32, INV-21's `cause: process(<proc>.sheet)` API). A gauge-less unasserted sheet part is a compile diagnostic, never a silently unthickened blank.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0449",
        symbol="PLAN_CLAUSE_MALFORMED",
        family="Contracts",
        meaning="a `plan: extern(<ref>, <dialect>)` field (WO-69, regolith/08 sec. 4's L6 row) is malformed: the extern ref string is missing, OR the dialect is not a registered `fmt.gcode_*` name (`gcode_fanuc`/`gcode_marlin`). No `cam.*` obligations are emitted for a malformed clause (honest silence, never a guess); this diagnostic is the only signal.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0450",
        symbol="FORALL_DOMAIN_UNDECLARED",
        family="Contracts",
        meaning="a `forall <var> in <domain>:` sweep names a BARE PLURAL (`boards`, `assemblies`) that resolves to no declared domain, so the sweep silently covers zero points -- a vacuous pass, the honesty gap WO-90 closes. A declared domain (`[lo, hi]` interval, `{a, b}` discrete set, `registry(<family>)`, `<Entity>.members.all`, or a dotted pack ref) is legal; an explicitly EMPTY declared domain stays legal (empty sweep = zero obligations, honestly). Only the undeclared bare-plural name trips this diagnostic.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0451",
        symbol="REMOVAL_FAMILY_MALFORMED",
        family="Contracts",
        meaning="a material-removal family constructor (`Ribs`, `PocketGrid`, `Shell`, `Lattice` -- charter 34 phase 1, D200/ WO-77) spells malformed parameters: a missing required slot, an unknown/duplicate slot, a wrong-dimension value (an int slot given a length, a length slot given a bare number), a `density` outside `[0, 1]`, or an unknown lattice `cell` name. Constructive: the diagnostic names the family's full signature and the exact offending slot; the op is omitted from the emitted feature program (never a guessed value, never silent truncation).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0452",
        symbol="SI_IMPEDANCE_MALFORMED",
        family="Contracts",
        meaning="an `elec.impedance(...) within [lo, hi]` claim (WO-78, charter 35 sec. 1.2) names no net: the call's first argument is empty or keyword-only, so there is nothing to attribute the impedance window to. Constructive: the message names the accepted shape (`elec.impedance(<net>[, role=..., stackup=..., layer=..., w=...]) within [lo, hi]`); the claim is not lowered (never a guessed subject).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0501",
        symbol="INDEX_VS_DOMAIN",
        family="Instances",
        meaning="positional index used where a domain is required.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0502",
        symbol="BROKEN_ORBIT_ANY",
        family="Instances",
        meaning="`any` over a broken (non-uniform) orbit.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0503",
        symbol="DEAD_GENERIC",
        family="Instances",
        meaning="a generic declaration is never instantiated (a dead generic: a monomorphization point-set with no points, INV-11).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0504",
        symbol="GENERIC_ARITY_MISMATCH",
        family="Instances",
        meaning="a use-site generic instantiation supplies the wrong number of arguments for its declaration, so no static check can run at that point (an un-expandable instantiation, INV-11).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0601",
        symbol="RULE_VIOLATION",
        family="RulePacks",
        meaning="a rule pack's static rule evaluated `false` against a matched entity (`pack.rule` provenance, `why:` rendered).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0602",
        symbol="RULE_NAME_COLLISION",
        family="RulePacks",
        meaning="two attached rule packs declare a rule of the same qualified name (`pack.rule`): union composition with no priority arithmetic means a collision is an error, never silent shadowing (design doc D-C).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0603",
        symbol="RULE_FACT_UNPROVIDED",
        family="RulePacks",
        meaning="a rule's predicate references a fact no layer (static entity DB, WO-22/24 realized-fact extraction) provides: a compile error on the rule itself (design doc D-E), not a deferral.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0604",
        symbol="RULE_STALE_RESOLVER",
        family="RulePacks",
        meaning="a `resolves:` clause names a field that is never `free` at any use site in the corpus (a stale resolver, mirror of `E0701`).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0701",
        symbol="STALE_WAIVER",
        family="Evidence",
        meaning="a declared waiver matched no claim or rule (stale).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0702",
        symbol="WAIVER_MISSING_BASIS",
        family="Evidence",
        meaning="a waiver carries no mandatory `basis:` (regolith/12 rule 2): an unjustified concession, rejected as an INV-2 ladder overreach rather than accepted.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="L0801",
        symbol="UNUSED_IMPORT",
        family="Lint",
        meaning="WO-40: an `import` line whose bound name is never referenced anywhere else in the same file (a dead import).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="L0802",
        symbol="RETIRED_VOCABULARY_USAGE",
        family="Lint",
        meaning='WO-40: source text spells a retired project name (`mill`, `loom`, `dcad`, `deda`, `quarry`, `lodestone`, or the dead `.calc` extension spelling) as an identifier/word token -- the "dead names are DEAD" CLAUDE.md rule, made mechanically checkable (design-log verbatim history and negative-fixture filenames are exempt, see `lints::retired_vocabulary`).',
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="L0803",
        symbol="TODO_ASSUME_INVENTORY",
        family="Lint",
        meaning="WO-40: one advisory per file summarizing its `todo!`/ `assume!` count + locations (the honest-deferral surface; not a nag per line).",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
    CodeEntry(
        code="E0703",
        symbol="WAIVE_NAMES_LINT_CODE",
        family="Evidence",
        meaning="WO-40/D117: a `waive` block's target spells a lint code (`Lxxxx`, case-insensitive) instead of a `Group.claim`/rule reference. Deliberately in `Family::Evidence`, NOT `Family::Lint` (`apply_lint_config` only ever touches the `Lint` family): the waive ladder cannot silence its own audit, so this rejection can never itself be configured away by `[lints]`.",
        why="no explanation authored yet",
        fix="no explanation authored yet",
        example=None,
        authored=False,
    ),
)

# name -> "E0901"-style code string, one constant per symbol
# (the Python-side raise sites import THESE, never a literal).
EQUALITY_ON_CONTINUOUS = "E0102"
FAB_SET_INCOMPLETE = "E0901"
DRAFTING_AUDIT_REFUSED = "E0902"
ARTIFACT_INDEX_DRIFT = "E0903"
UNEXPLAINED_OVERRIDE = "E1001"
SOURCE_ONLY_TARGET_REFUSED = "E1002"
UNRESOLVABLE_OVERRIDE_TARGET = "E1003"
EXPECTATION_PROVENANCE_UNRESOLVED = "E1101"
RELEASE_GATE_REFUSES_DEBUG_EVIDENCE = "E1102"
TAP_MAP_DISAGREEMENT = "E1103"
INCOMPATIBLE_QUANTITIES = "E0101"
INTERVAL_RANGE_CONFUSION = "E0103"
ILLEGAL_LOG_SUM = "E0104"
COMBINATIONAL_CYCLE = "E0105"
RUN_MISSING_ENDPOINT = "E0106"
SELECT_EMPTY_CANDIDATE_LIST = "E0107"
IMPOSER_FREE_SUBNET = "E0201"
UNJOINED_TERMINAL = "E0202"
TRANSIENT_NO_COMPLIANCE = "E0203"
SPACE_NOT_IN_CIRCULATION = "E0204"
CIRCULATION_UNREACHABLE = "E0205"
EGRESS_EDGE_UNDECLARED = "E0206"
MEMBER_UNSUPPORTED = "E0207"
STRUCTURE_NO_SUPPORT = "E0208"
MEMBER_UNJOINED_OR_TRIBUTARY_MISMATCH = "E0209"
MEDIUM_MISMATCH = "E0210"
POINT_LOAD_NEEDS_STATION = "E0211"
AMBIGUOUS_SELECTION = "E0301"
BORROW_CONFLICT = "E0302"
UNRESOLVED_FIELD_REFERENCE = "E0303"
STRUCTURE_CLASS_CHANGE = "E0304"
COMPUTE_FIELD_CYCLE = "E0305"
RUN_CROSS_NET = "E0306"
RUN_DANGLING_ENDPOINT = "E0307"
RUN_UNKNOWN_BUNDLE = "E0308"
RUN_EXTRACT_FAILED = "E0309"
BOUNDARY_NOT_SUBSUMED = "E0407"
CAPABILITY_VS_DEMAND = "E0410"
LEDGER_IMBALANCE = "E0420"
BUDGET_CANNOT_CLOSE = "E0432"
REALIZATION_NOT_EXACTLY_ONE = "E0433"
PROMISED_BOUND_UNMATCHED = "E0434"
TEMPORAL_REDUCTION_MISSING_COMPARATOR = "E0435"
TEMPORAL_CONTAINMENT_UNEXPECTED_COMPARATOR = "E0436"
GENERAL_COMPARISON_MULTIPLE_COMPARATORS = "E0437"
COST_CLAIM_MALFORMED = "E0438"
SINGULAR_SYSTEM = "E0440"
SKETCH_RESIDUAL_INCONSISTENT = "E0441"
UNBOUND_SEGMENT_LABEL = "E0442"
UNSUPPORTED_FEATURE_OP = "E0443"
CAVITY_PORT_UNRESOLVED = "E0444"
CAVITY_CHAIN_INEXPRESSIBLE = "E0445"
SELECT_DUPLICATE_CANDIDATE = "E0446"
SKETCH_CLOSE_EDGE_UNDERCONSTRAINED = "E0447"
SHEET_BLANK_NO_GAUGE_SOURCE = "E0448"
PLAN_CLAUSE_MALFORMED = "E0449"
FORALL_DOMAIN_UNDECLARED = "E0450"
REMOVAL_FAMILY_MALFORMED = "E0451"
SI_IMPEDANCE_MALFORMED = "E0452"
INDEX_VS_DOMAIN = "E0501"
BROKEN_ORBIT_ANY = "E0502"
DEAD_GENERIC = "E0503"
GENERIC_ARITY_MISMATCH = "E0504"
RULE_VIOLATION = "E0601"
RULE_NAME_COLLISION = "E0602"
RULE_FACT_UNPROVIDED = "E0603"
RULE_STALE_RESOLVER = "E0604"
STALE_WAIVER = "E0701"
WAIVER_MISSING_BASIS = "E0702"
UNUSED_IMPORT = "L0801"
RETIRED_VOCABULARY_USAGE = "L0802"
TODO_ASSUME_INVENTORY = "L0803"
WAIVE_NAMES_LINT_CODE = "E0703"

BY_CODE: dict[str, CodeEntry] = {e.code: e for e in ALL}
BY_SYMBOL: dict[str, CodeEntry] = {e.symbol: e for e in ALL}
