# GENERATED by `make schema` (AD-5) -- never hand-edit.

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import ConfigDict, Field, RootModel

from regolith._schema_base import FrozenModel


class Model(RootModel[Any]):
    root: Any


class Assumption(FrozenModel):
    """
    An `assume!(expr, basis=)` assumption: an un-discharged claim that `--release` refuses (recorded in the todo/assume/waive ledger).
    """

    basis: Annotated[str, Field(description="The stated basis for the assumption.")]
    expr: Annotated[str, Field(description="The assumed expression, as text.")]


class CapabilityDemand(FrozenModel):
    """
    One raw capability demand from a resource block's `promises:` bound. `>= 20Mops f32 sustained` -> `{capability: "", comparator: ">=", value: "20Mops f32 sustained"}`; `latency <= 2 cycles` -> `{capability: "latency", comparator: "<=", value: "2 cycles"}`.
    """

    capability: Annotated[
        str,
        Field(
            description="The named subject of the bound (`latency`, `context_switch`), or empty for the block-kind's implicit primary bound (an `executor`'s throughput, a `mover`'s bandwidth): a bare `>= <value>` names no left-hand subject."
        ),
    ]
    comparator: Annotated[
        str,
        Field(
            description="The comparator spelled (`>=`, `<=`, `==`, `>`, `<`): the demand's direction, preserved verbatim for the Python screen to interpret."
        ),
    ]
    value: Annotated[
        str,
        Field(
            description="The raw right-hand value text as spelled (`20Mops f32 sustained`), NOT unit-resolved -- the Python bridge parses the quantity."
        ),
    ]


class Cause2(StrEnum):
    dfm = "dfm"


class Cause1(FrozenModel):
    """
    A DFM rule pinned it (`dfm(sheet.min_bend_radius)`).
    """

    cause: Cause2
    ref: str


class Cause4(StrEnum):
    drc = "drc"


class Cause3(FrozenModel):
    """
    A DRC rule pinned it (`drc(jlc_2l.current_capacity)`).
    """

    cause: Cause4
    ref: str


class Cause6(StrEnum):
    obligation = "obligation"


class Cause5(FrozenModel):
    """
    An obligation determined it (`obligation(vdd_core.droop)`).
    """

    cause: Cause6
    ref: str


class Cause8(StrEnum):
    budget = "budget"


class Cause7(FrozenModel):
    """
    A budget allocation set it (`budget(mesh_alignment)`).
    """

    cause: Cause8
    ref: str


class Cause10(StrEnum):
    topology = "topology"


class Cause9(FrozenModel):
    """
    A topology/structure boundary pinned it.
    """

    cause: Cause10
    ref: str


class Cause12(StrEnum):
    planner = "planner"


class Cause11(FrozenModel):
    """
    A planner produced it.
    """

    cause: Cause12
    ref: str


class Cause14(StrEnum):
    extern = "extern"


class Cause13(FrozenModel):
    """
    A foreign artifact linked via `extern(ref)` supplied it (regolith/08 lowering, `by extern`).
    """

    cause: Cause14
    ref: str


class Cause16(StrEnum):
    derived_intent = "derived_intent"


class Cause15(FrozenModel):
    """
    A derived intent/workload analysis pinned it (`derived(intent <name>)`, regolith/09 sec. 1).
    """

    cause: Cause16
    ref: str


class Cause18(StrEnum):
    policy = "policy"


class Cause17(FrozenModel):
    """
    A `policy:` block at system altitude decided it (regolith/03 sec. 2, `allocated (policy)`).
    """

    cause: Cause18
    ref: str


class Form(StrEnum):
    comparison = "comparison"


class ClaimForm1(FrozenModel):
    """
    A scalar comparison (`stress < limit`, `k within [lo, hi]`).
    """

    form: Form
    lhs: Annotated[
        str,
        Field(description="The quantity expression (kept as text; parsed in WO-05)."),
    ]
    op: Annotated[
        str, Field(description="The comparator/containment (`<`, `within`, ...).")
    ]
    rhs: Annotated[str, Field(description="The bound expression.")]


class Form1(StrEnum):
    peak = "peak"


class Form2(StrEnum):
    settles = "settles"


class Form3(StrEnum):
    overshoot = "overshoot"


class ClaimForm4(FrozenModel):
    """
    `overshoot(x, after e) <op> <rhs>` (D102: a REDUCTION form).
    """

    event: Annotated[str, Field(description="The anchoring event.")]
    form: Form3
    op: Annotated[str, Field(description="The external comparator (`<`, `<=`, ...).")]
    rhs: Annotated[str, Field(description="The bound expression.")]
    signal: Annotated[str, Field(description="The signal expression.")]


class Form4(StrEnum):
    rms = "rms"


class ClaimForm5(FrozenModel):
    """
    `rms(x, band=[f1, f2]) <op> <rhs>` (D102: a REDUCTION form).
    """

    band: Annotated[str, Field(description="The frequency band, as text.")]
    form: Form4
    op: Annotated[str, Field(description="The external comparator (`<`, `<=`, ...).")]
    rhs: Annotated[str, Field(description="The bound expression.")]
    signal: Annotated[str, Field(description="The signal expression.")]


class Form5(StrEnum):
    stays_within = "stays_within"


class ClaimForm6(FrozenModel):
    """
    `stays_within(x, mask)`.
    """

    form: Form5
    mask: Annotated[str, Field(description="The hash-pinned mask reference.")]
    signal: Annotated[str, Field(description="The signal expression.")]


class CoverageDomain1(FrozenModel):
    """
    A continuous domain, as text (e.g. `"[300K, 400K]"`).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    interval: str


class Values(FrozenModel):
    values: Annotated[list[str], Field(description="The enumerated values, as text.")]


class CoverageDomain2(FrozenModel):
    """
    A discrete domain (valve line-ups, failure states, ...).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    values: Values


class CoverageMethod1(StrEnum):
    """
    Corner-only sampling.
    """

    corners = "corners"


class KItem(RootModel[int]):
    root: Annotated[int, Field(ge=0)]


class Grid(FrozenModel):
    k: Annotated[list[KItem], Field(description="Per-axis grid resolution.")]


class CoverageMethod2(FrozenModel):
    """
    A grid with per-axis resolution `k` (multi-dim: `grid(k x m)`, the G29 demand).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    grid: Grid


class CoverageMethod3(StrEnum):
    """
    Every discrete value was enumerated.
    """

    enumerated = "enumerated"


class CoverageMethod4(StrEnum):
    """
    A closed-form analytic bound covers the whole domain.
    """

    analytic = "analytic"


class CoverageMethod5(StrEnum):
    """
    Declared monotonicity lets the worst corner stand for the domain.
    """

    monotone = "monotone"


class Material(RootModel[list[str]]):
    root: Annotated[list[str], Field(max_length=2, min_length=2)]


class Ref(RootModel[list[str]]):
    root: Annotated[list[str], Field(max_length=2, min_length=2)]


class Given(FrozenModel):
    """
    The `given:` context an obligation is evaluated under: the pinned facts (materials, loads, backing evidence) the discharge assumes.
    """

    backing: Annotated[
        list[str], Field(description="Backing evidence references the given relies on.")
    ]
    loads: Annotated[
        list[str], Field(description="Applied loads/environment, as text expressions.")
    ]
    materials: Annotated[
        list[Material],
        Field(description="Pinned material/component records (name -> content hash)."),
    ]
    refs: Annotated[
        list[Ref] | None,
        Field(
            description="Entity-field reference terms (D103): reference path (e.g. `comms.pa_out`) -> the resolved value-source text, for expression givens a general comparison claim's sides name.",
            validate_default=True,
        ),
    ] = []


class ImplRecord(FrozenModel):
    """
    A harness impl record for a signature (data only; the code lives in the Python harness).
    """

    cost: Annotated[int, Field(description="Relative cost hint for scheduling.", ge=0)]
    domain: Annotated[
        list[str], Field(description="The validity domain this impl covers.")
    ]
    error_model: Annotated[
        str, Field(description="The error-model tag (how `eps` is derived).")
    ]
    name: Annotated[str, Field(description="The impl's name (the discharge model id).")]
    signature: Annotated[str, Field(description="The signature this implements.")]


class LedgerEntry1(FrozenModel):
    """
    A `todo!` placeholder.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    todo: str


class LedgerEntry2(FrozenModel):
    """
    An `assume!` assumption.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    assume: str


class LedgerEntry3(FrozenModel):
    """
    An unwaived indeterminate discharge.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    indeterminate: str


class PayloadRef(FrozenModel):
    """
    A hash-pinned reference to a payload of a declared `kind`, crossing the `DischargeRequest.payloads` channel (D96). The kind vocabulary is feldspar 09 sec. 4's list VERBATIM: `geometry.parametric`, `geometry.realized`, `mesh`, `table`, `spectrum`, `profile`, `mask`, `field`, `flownet`, `plan`.
    """

    digest: Annotated[
        str, Field(description="The blake3 content digest of the payload bytes.")
    ]
    kind: Annotated[
        str,
        Field(
            description="The payload kind (feldspar 09 sec. 4 vocabulary, verbatim)."
        ),
    ]
    origin: Annotated[
        str,
        Field(
            description="The producing snapshot/record name, for diagnostics only (never part of the digest/identity)."
        ),
    ]


class ResolvedFeatureParam(FrozenModel):
    """
    One resolved scalar parameter a feature constructor spelled, with its `Cause` tag (INV-21). `text` is the raw quantity/keyword text as parsed (e.g. `28mm`, `free`) -- this pass does not unit-convert or numerically resolve it (that is the harness/DFM pack's job); it only records WHAT was spelled and WHY (its provenance class).
    """

    cause: Annotated[
        str,
        Field(
            description="The INV-21 provenance class: `literal` for an ordinary spelled value, or one of `free`/`derived`/`allocated`/`planner` when the text itself is a value-source keyword (regolith/03 sec. 2's vocabulary) rather than a literal quantity."
        ),
    ]
    text: Annotated[
        str, Field(description="The raw parameter text as spelled in source.")
    ]


class Input(RootModel[list[str]]):
    root: Annotated[list[str], Field(max_length=2, min_length=2)]


class Output(RootModel[list[str]]):
    root: Annotated[list[str], Field(max_length=2, min_length=2)]


class Signature(FrozenModel):
    """
    A physics-model signature: a typed input/output contract.
    """

    domain: Annotated[
        list[str], Field(description="Validity domain tags (`clamped`, `linear`).")
    ]
    inputs: Annotated[
        list[Input],
        Field(description="Input port names -> their quantity type (as text)."),
    ]
    name: Annotated[str, Field(description="Signature name (`bolted_joint_state`).")]
    outputs: Annotated[
        list[Output], Field(description="Output port names -> their quantity type.")
    ]


class SignatureAlgorithm1(StrEnum):
    """
    Ed25519 (RFC 8032) -- the only algorithm implemented in v1.
    """

    ed25519 = "ed25519"


class SignatureAlgorithm(RootModel[SignatureAlgorithm1]):
    root: Annotated[
        SignatureAlgorithm1,
        Field(
            description="The one signature algorithm this WO speaks. A closed enum (not a free string) so an unrecognized algorithm is a deserialization error, not a silently-accepted unknown."
        ),
    ]


class SignatureRegistry(FrozenModel):
    """
    The signature + impl registry the orchestrator matches discharge against.
    """

    impls: list[ImplRecord]
    signatures: dict[str, Signature]


class SnapshotRecord(FrozenModel):
    """
    One committed `EntityDb` scope's content-addressed snapshot, keyed by its scope name -- the WO-19 lowering pipeline emits one of these per scope (`docs/design-log/2026-07-04-cycle-11.md`).
    """

    hash: Annotated[
        str,
        Field(description="The scope's `EntityDb::snapshot_hash()` content address."),
    ]
    scope: Annotated[
        str,
        Field(description="The scope this snapshot belongs to (a declaration name)."),
    ]


class Status1(StrEnum):
    """
    The claim holds with margin after the model's error.
    """

    discharged = "discharged"


class Status2(StrEnum):
    """
    The claim provably fails at its worst corner.
    """

    violated = "violated"


class Status3(StrEnum):
    """
    No adequate model, coverage, or trust; neither proven nor disproven (distinct from violated).
    """

    indeterminate = "indeterminate"


class SweepDomain(FrozenModel):
    """
    A sweep domain an obligation is instantiated over (one obligation per domain point; the obligation carries its own domain).
    """

    axis: Annotated[str, Field(description="The swept axis name.")]
    domain: Annotated[
        str,
        Field(
            description="The domain description (interval or discrete set, as text)."
        ),
    ]


class Unit(FrozenModel):
    pass


class Waiver(FrozenModel):
    """
    A source-declared waiver: it matches some set of claims/rules and carries a basis (and optionally evidence, making it a deviation).
    """

    basis: Annotated[
        str,
        Field(
            description="The stated basis (regolith/12 rule 2 -- mandatory; an absent basis is an INV-2 overreach diagnostic raised at lowering)."
        ),
    ]
    evidence: Annotated[
        str | None,
        Field(
            description="Backing evidence reference, if this is a deviation (a `by` clause) rather than a bare, release-gated waiver."
        ),
    ] = None
    expires: Annotated[
        str | None, Field(description="Expiry marker, if any (regolith/12 rule 8).")
    ] = None
    scope: Annotated[
        str | None,
        Field(
            description="The `on <query>` scope pattern, if any; `None` is an unscoped waiver covering the target wherever it fails in the artifact."
        ),
    ] = None
    target: Annotated[
        str,
        Field(
            description="The rule or claim being waived (`dfm(min_web_thickness)`, `Group.claim`)."
        ),
    ]


class WaiverKind1(StrEnum):
    """
    The waiver matched one or more emitted obligations (recorded as the accepted match set); their true status is untouched.
    """

    matched = "matched"


class WaiverKind2(StrEnum):
    """
    The target is a rule-pack rule (`dfm`/`drc`/`erc`) the static core does not lower to obligations: recorded and release-gated, but NOT stale -- the core simply cannot see the target here.
    """

    deferred_rule_pack = "deferred_rule_pack"


class WaiverKind3(StrEnum):
    """
    The target is a claim the pipeline emits obligations for, yet the waiver matched none of them: a stale-waiver error (INV-12).
    """

    stale = "stale"


class WaiverRecord(FrozenModel):
    """
    A declared waiver plus its honesty outcome: the classification and the exact obligation content-hashes it accepted. This is the audit surface INV-12 requires -- every waiver appears here with its reason and match set; no waiver silently vanishes.
    """

    kind: Annotated[
        WaiverKind1 | WaiverKind2 | WaiverKind3,
        Field(description="Its relationship to the obligation set."),
    ]
    match_set: Annotated[
        list[str] | None,
        Field(
            description="D105(d): the sorted entity refs the waiver matched AT AUTHORSHIP time, so a later `regolith build` can diff prior lockfile match sets and report GROWTH as a named diagnostic (the waiver ladder's anti-rot residual). Schema field only here (WO-30); the diff pass is the WO-26 remainder's job."
        ),
    ] = []
    matched: Annotated[
        list[str],
        Field(
            description="The content hashes of the obligations this waiver accepted (empty for `DeferredRulePack`/`Stale`), in source order."
        ),
    ]
    waiver: Annotated[Waiver, Field(description="The declared waiver.")]


class Window1(FrozenModel):
    """
    `during <event-or-config-domain>`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    during: str


class WithinAfter(FrozenModel):
    duration: Annotated[
        str, Field(description="The bounding duration (source text; typed in qty).")
    ]
    event: Annotated[str, Field(description="The anchoring event.")]


class Window2(FrozenModel):
    """
    `within <duration> after <event>`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    within_after: WithinAfter


class Window3(FrozenModel):
    """
    `until <event>`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    until: str


class Attestation(FrozenModel):
    """
    A solver's signature over one evidence value's content address.

    Attaching, detaching, or re-signing (key rotation) an `Attestation` never changes the evidence's own hash (D-E): this type carries attribution metadata (which model/pack/key produced and vouched for the result) alongside the signature bytes, and nothing here is a hash input for `Evidence` itself.
    """

    algorithm: Annotated[
        SignatureAlgorithm, Field(description="The signature algorithm.")
    ]
    key_id: Annotated[
        str,
        Field(
            description="The signing key's identifier (matched against the consumer's quarry key-set designations at verification time, INV-14/INV-28)."
        ),
    ]
    model_id: Annotated[
        str,
        Field(description="The discharging model's id (matches `Evidence::model_id`)."),
    ]
    pack_name: Annotated[
        str, Field(description="The signing solver pack's name (AD-19 pack identity).")
    ]
    pack_version: Annotated[
        str, Field(description="The signing solver pack's version.")
    ]
    signature_base64: Annotated[
        str,
        Field(
            description="The signature bytes, base64-encoded on the wire (JSON has no native byte type; the Python side decodes before verifying)."
        ),
    ]


class BlockRequirement(FrozenModel):
    """
    One abstract resource block's raw capability demand, projected from a single `resources:`/`memories:`/`peripherals:` entry that carries a `promises:` keyword argument. The `BlockRequirement`-shaped lowering output WO-24's allocation search screens candidates against.
    """

    block: Annotated[
        str,
        Field(
            description="The abstract block/resource name the demand is FOR (`cpu0`, `sram`, `dma`): the allocation-search block identity."
        ),
    ]
    contract: Annotated[
        str,
        Field(
            description="The stdlib block-contract kind the resource instantiates (`executor`, `memory`, `mover`, `fabric`): the demand's vocabulary namespace."
        ),
    ]
    demands: Annotated[
        list[CapabilityDemand],
        Field(
            description="The raw capability demands spelled in this block's `promises:` argument, in source order (AD-6)."
        ),
    ]
    owner: Annotated[
        str,
        Field(
            description="The owning `architecture for <owner>:` target (the computer this block belongs to, `FlightCore`): grouping + traceability."
        ),
    ]


class ClaimForm2(FrozenModel):
    """
    `peak(x, during w) <op> <rhs>` (D102: a REDUCTION form that yields a scalar and requires an external comparator).
    """

    form: Form1
    op: Annotated[str, Field(description="The external comparator (`<`, `<=`, ...).")]
    rhs: Annotated[str, Field(description="The bound expression.")]
    signal: Annotated[str, Field(description="The signal expression.")]
    window: Annotated[
        Window1 | Window2 | Window3, Field(description="The evaluation window.")
    ]


class ClaimForm3(FrozenModel):
    """
    `settles(x, to=tol, within d after e)`. A CONTAINMENT form (D102): self-contained, no external comparator (its `tol` IS the acceptance).
    """

    form: Form2
    signal: Annotated[str, Field(description="The signal expression.")]
    tol: Annotated[str, Field(description="Settling tolerance text.")]
    window: Annotated[
        Window1 | Window2 | Window3, Field(description="The bounding window.")
    ]


class CoverageAxis(FrozenModel):
    """
    One axis of structured coverage: the swept variable, its domain, and the method used to cover it (D95, sec. 8.2).
    """

    axis: Annotated[str, Field(description="The swept axis name.")]
    domain: Annotated[
        CoverageDomain1 | CoverageDomain2,
        Field(description="The axis's domain (continuous or discrete)."),
    ]
    method: Annotated[
        CoverageMethod1
        | CoverageMethod2
        | CoverageMethod3
        | CoverageMethod4
        | CoverageMethod5,
        Field(description="The method used to cover this axis."),
    ]


class FeatureOp(FrozenModel):
    """
    One feature op materialized from a `then:` claim-scope constructor call (the SAME structured calls deliverable 2's entity projector reads, `claim_scope::feature_calls_in_decl` -- one traversal, two consumers, AD-17/NO DUPLICATION).
    """

    constructor: Annotated[
        str,
        Field(
            description="The constructor verb actually spelled (`Bore`, `CBore`, `Pierce`, `Bend`, ...) -- a stable discriminant alongside the coarse kind."
        ),
    ]
    count: Annotated[
        int,
        Field(
            description="Orbit multiplicity: `n=N` for a `PatternOf<...>(n=N)` orbit, else 1 (matches deliverable 2's per-instance entity count).",
            ge=0,
        ),
    ]
    kind: Annotated[
        str,
        Field(
            description="The domain kind this op materializes (`hole`, `bend`) -- mirrors `regolith_sem::EntityKind`'s two domain variants at the string level (this type does not depend on `regolith-sem`)."
        ),
    ]
    name: Annotated[
        str,
        Field(description="The feature's local binding (`pilot`, `mounts`, `flange`)."),
    ]
    params: Annotated[
        dict[str, ResolvedFeatureParam],
        Field(
            description="The well-known scalar measures this constructor spelled (`diameter`/`depth`/`edge_distance` for a hole, `angle`/`radius` for a bend), each Cause-tagged."
        ),
    ]


class FeatureProgram(FrozenModel):
    """
    The (partial, per the scope note above) feature program for one declaration: every `FeatureOp` its `then:` claim scopes construct, in source order (AD-6).
    """

    features: Annotated[
        list[FeatureOp], Field(description="Feature ops in source order.")
    ]
    part_name: Annotated[
        str, Field(description="The declaration name this program belongs to.")
    ]


class LedgerEntry4(FrozenModel):
    """
    A waiver that matched and shadowed a claim/rule, with its match set (INV-12 audit surface).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    waived: WaiverRecord


class Qty(FrozenModel):
    magnitude: float
    unit: Unit


class Resolution(FrozenModel):
    """
    A resolved value with its cause: one lockfile row. There is no way to build one without a `Cause` (INV-21).
    """

    cause: Annotated[
        Cause1
        | Cause3
        | Cause5
        | Cause7
        | Cause9
        | Cause11
        | Cause13
        | Cause15
        | Cause17,
        Field(
            description="Why a value resolved to what it did. Mandatory on every resolution (INV-21). The variants mirror the resolving mechanisms."
        ),
    ]
    value: Qty


class WaiveLedger(FrozenModel):
    """
    The build's todo/assume/waive ledger.
    """

    entries: list[LedgerEntry1 | LedgerEntry2 | LedgerEntry3 | LedgerEntry4]


class Claim(FrozenModel):
    """
    A single named claim inside a `require` group.
    """

    forall: Annotated[
        list[str],
        Field(description="`forall <cfg>` config axes the claim quantifies over."),
    ]
    form: Annotated[
        ClaimForm1 | ClaimForm2 | ClaimForm3 | ClaimForm4 | ClaimForm5 | ClaimForm6,
        Field(description="The claim form."),
    ]
    hints: Annotated[list[str], Field(description="Discharge-model hints (`@hint`).")]
    model_pin: Annotated[
        str | None, Field(description="A `model=` pin selecting the discharge model.")
    ] = None
    name: Annotated[str | None, Field(description="Optional claim name.")] = None
    scatter_factor: Annotated[
        float | None, Field(description="Scatter factor (`scatter_factor=`), if any.")
    ] = None
    sf: Annotated[float | None, Field(description="Safety factor (`sf=`), if any.")] = (
        None
    )
    trust_floor: Annotated[
        str | None,
        Field(description="Minimum required evidence trust tier (`trust: >= tier`)."),
    ] = None


class Coverage(FrozenModel):
    """
    Structured coverage (D95, sec. 8.2): per-axis coverage plus the conservative scalar collapse kept for margin notes and old consumers -- `fraction` must never overstate what `axes` states. `Evidence`/`SolverResponse` carry this instead of a bare float.
    """

    axes: Annotated[
        list[CoverageAxis],
        Field(
            description="The per-axis coverage record (empty for a closed-form/full claim)."
        ),
    ]
    fraction_bits: Annotated[
        int,
        Field(
            description="The conservative scalar collapse (`1.0` = full), as `f64` bits.",
            ge=0,
        ),
    ]


class Evidence(FrozenModel):
    """
    The evidence produced by discharging one obligation.
    """

    cost: Annotated[int, Field(description="Relative cost incurred.", ge=0)]
    coverage: Annotated[
        Coverage,
        Field(
            description="Structured per-axis coverage (D95, sec. 8.2); `Coverage::full()` for a closed-form/full claim."
        ),
    ]
    eps_bits: Annotated[int, Field(description="The model error `eps`'s bits.", ge=0)]
    hash: Annotated[
        str, Field(description="Content hash of this evidence (cache key component).")
    ]
    margin_bits: Annotated[
        int,
        Field(
            description="The margin after error (`limit - (value + eps)`)'s bits.", ge=0
        ),
    ]
    model_id: Annotated[
        str, Field(description="The discharge model id that produced this.")
    ]
    status: Annotated[
        Status1 | Status2 | Status3, Field(description="The discharge status.")
    ]
    value_bits: Annotated[
        int,
        Field(
            description="The computed value's bits (f64 as bits for exact serialization).",
            ge=0,
        ),
    ]


class EvidenceCache(FrozenModel):
    """
    A cache of evidence keyed on (subject, contract, registry versions), so a second run is a hit.
    """

    entries: dict[str, Evidence]


class Obligation(FrozenModel):
    """
    A self-contained verification obligation.
    """

    claim: Annotated[Claim, Field(description="The claim being discharged.")]
    given: Annotated[Given, Field(description="The pinned evaluation context.")]
    hints: Annotated[
        list[str], Field(description="Discharge hints carried from the claim/symmetry.")
    ]
    subject_ref: Annotated[
        str,
        Field(
            description="Content-addressed reference to the subject (entity/snapshot hash)."
        ),
    ]
    sweep: Annotated[
        SweepDomain | None,
        Field(description="The sweep domain this obligation instance carries, if any."),
    ] = None


class SolverResponse(FrozenModel):
    """
    The schema-versioned JSON document a subprocess solver writes to stdout: its worst-corner prediction, plus the identity/determinism metadata the evidence hash folds (AD-19: `solver_version` is always folded; non-deterministic solvers also fold `settings_digest`).
    """

    coverage: Annotated[
        Coverage, Field(description="Structured coverage achieved (D95, sec. 8.2).")
    ]
    domain_ok: Annotated[
        bool,
        Field(
            description="True iff the request fell inside the solver's validity domain; false maps to an honest `indeterminate`, never a silent pass."
        ),
    ]
    eps_bits: Annotated[
        int,
        Field(
            description="The solver's declared worst-case error `eps`'s `f64` bits.",
            ge=0,
        ),
    ]
    note: Annotated[
        str | None,
        Field(
            description="Optional human-readable note carried into logs (never hashed)."
        ),
    ] = None
    schema_version: Annotated[
        int,
        Field(
            description="The `SCHEMA_VERSION` the solver spoke; a mismatch with ours is the adapter's `SchemaVersionMismatch` failure arm (AD-5).",
            ge=0,
        ),
    ]
    settings_digest: Annotated[
        str | None,
        Field(
            description="Settings/seed digest for non-deterministic solvers (INV-10); absent for a fully deterministic solve."
        ),
    ] = None
    solver_version: Annotated[
        str,
        Field(
            description="The solver binary's own version id (always folded into the evidence hash, AD-19)."
        ),
    ]
    value_bits: Annotated[
        int, Field(description="The predicted worst-corner value's `f64` bits.", ge=0)
    ]
