# GENERATED by `make schema` (AD-5) -- never hand-edit.

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import ConfigDict, Field, RootModel

from regolith._schema_base import FrozenModel


class Model(RootModel[Any]):
    root: Any


class Annotation(FrozenModel):
    """
    A free-text or symbolic annotation (notes, GD&T frames, per: citations).
    """

    anchor: Annotated[
        list[float],
        Field(description="Anchor point on the sheet.", max_length=2, min_length=2),
    ]
    datum_refs: Annotated[
        list[str] | None,
        Field(
            description="Referenced datum labels, if this annotation is a GD&T frame."
        ),
    ] = []
    per: Annotated[
        str | None,
        Field(
            description='Optional standard-clause citation (`per:` prefix convention, e.g. "ASME Y14.5 7.2").'
        ),
    ] = None
    text: Annotated[
        str,
        Field(
            description="Annotation text (a GD&T frame renders as its text form here; v1 does not model frame glyph geometry separately)."
        ),
    ]
    text_height_mm: Annotated[
        float,
        Field(description="Text height, mm (drives the minimum-text-height rule)."),
    ]


class Assumption(FrozenModel):
    """
    An `assume!(expr, basis=)` assumption: an un-discharged claim that `--release` refuses (recorded in the todo/assume/waive ledger).
    """

    basis: Annotated[str, Field(description="The stated basis for the assumption.")]
    expr: Annotated[str, Field(description="The assumed expression, as text.")]


class Bend(FrozenModel):
    """
    A bend within a routed segment: turn angle (rad) and centreline radius (m), each an `[lo, hi]` interval.
    """

    angle: Annotated[
        list[float],
        Field(description="Turn angle interval, rad.", max_length=2, min_length=2),
    ]
    radius: Annotated[
        list[float],
        Field(description="Centreline radius interval, m.", max_length=2, min_length=2),
    ]


class BoardSide1(StrEnum):
    """
    Top (component) side.
    """

    top = "top"


class BoardSide2(StrEnum):
    """
    Bottom side.
    """

    bottom = "bottom"


class CapabilityDemand(FrozenModel):
    """
    One raw capability demand from a resource block's `promises:` bound. `>= 20Mops f32 sustained` -> `{capability: "", comparator: ">=", value: "20Mops f32 sustained"}`; `latency <= 2 cycles` -> `{capability: "latency", comparator: "<=", value: "2 cycles"}`.
    """

    capability: Annotated[
        str,
        Field(
            description="The named subject of the bound (`latency`, `context_switch`), or empty for the block-kind's implicit primary bound (an `executor`'s throughput, a `mover`'s bandwidth): a bare `>= <value>` names no left-hand subject."
        ),
    ]
    comparator: Annotated[
        str,
        Field(
            description="The comparator spelled (`>=`, `<=`, `==`, `>`, `<`): the demand's direction, preserved verbatim for the Python screen to interpret."
        ),
    ]
    value: Annotated[
        str,
        Field(
            description="The raw right-hand value text as spelled (`20Mops f32 sustained`), NOT unit-resolved -- the Python bridge parses the quantity."
        ),
    ]


class Cause2(StrEnum):
    dfm = "dfm"


class Cause1(FrozenModel):
    """
    A DFM rule pinned it (`dfm(sheet.min_bend_radius)`).
    """

    cause: Cause2
    ref: str


class Cause4(StrEnum):
    drc = "drc"


class Cause3(FrozenModel):
    """
    A DRC rule pinned it (`drc(jlc_2l.current_capacity)`).
    """

    cause: Cause4
    ref: str


class Cause6(StrEnum):
    obligation = "obligation"


class Cause5(FrozenModel):
    """
    An obligation determined it (`obligation(vdd_core.droop)`).
    """

    cause: Cause6
    ref: str


class Cause8(StrEnum):
    budget = "budget"


class Cause7(FrozenModel):
    """
    A budget allocation set it (`budget(mesh_alignment)`).
    """

    cause: Cause8
    ref: str


class Cause10(StrEnum):
    topology = "topology"


class Cause9(FrozenModel):
    """
    A topology/structure boundary pinned it.
    """

    cause: Cause10
    ref: str


class Cause12(StrEnum):
    planner = "planner"


class Cause11(FrozenModel):
    """
    A planner produced it.
    """

    cause: Cause12
    ref: str


class Cause14(StrEnum):
    extern = "extern"


class Cause13(FrozenModel):
    """
    A foreign artifact linked via `extern(ref)` supplied it (regolith/08 lowering, `by extern`).
    """

    cause: Cause14
    ref: str


class Cause16(StrEnum):
    derived_intent = "derived_intent"


class Cause15(FrozenModel):
    """
    A derived intent/workload analysis pinned it (`derived(intent <name>)`, regolith/09 sec. 1).
    """

    cause: Cause16
    ref: str


class Cause18(StrEnum):
    policy = "policy"


class Cause17(FrozenModel):
    """
    A `policy:` block at system altitude decided it (regolith/03 sec. 2, `allocated (policy)`).
    """

    cause: Cause18
    ref: str


class Form(StrEnum):
    comparison = "comparison"


class ClaimForm1(FrozenModel):
    """
    A scalar comparison (`stress < limit`, `k within [lo, hi]`).
    """

    form: Form
    lhs: Annotated[
        str,
        Field(description="The quantity expression (kept as text; parsed in WO-05)."),
    ]
    op: Annotated[
        str, Field(description="The comparator/containment (`<`, `within`, ...).")
    ]
    rhs: Annotated[str, Field(description="The bound expression.")]


class Form1(StrEnum):
    peak = "peak"


class Form2(StrEnum):
    settles = "settles"


class Form3(StrEnum):
    overshoot = "overshoot"


class ClaimForm4(FrozenModel):
    """
    `overshoot(x, after e) <op> <rhs>` (D102: a REDUCTION form).
    """

    event: Annotated[str, Field(description="The anchoring event.")]
    form: Form3
    op: Annotated[str, Field(description="The external comparator (`<`, `<=`, ...).")]
    rhs: Annotated[str, Field(description="The bound expression.")]
    signal: Annotated[str, Field(description="The signal expression.")]


class Form4(StrEnum):
    rms = "rms"


class ClaimForm5(FrozenModel):
    """
    `rms(x, band=[f1, f2]) <op> <rhs>` (D102: a REDUCTION form).
    """

    band: Annotated[str, Field(description="The frequency band, as text.")]
    form: Form4
    op: Annotated[str, Field(description="The external comparator (`<`, `<=`, ...).")]
    rhs: Annotated[str, Field(description="The bound expression.")]
    signal: Annotated[str, Field(description="The signal expression.")]


class Form5(StrEnum):
    stays_within = "stays_within"


class ClaimForm6(FrozenModel):
    """
    `stays_within(x, mask)`.
    """

    form: Form5
    mask: Annotated[str, Field(description="The hash-pinned mask reference.")]
    signal: Annotated[str, Field(description="The signal expression.")]


class Form6(StrEnum):
    compute = "compute"


class ClaimForm7(FrozenModel):
    """
    `compute <name>: <quantity kind> over <index domain>` (WO-33 D98): produces a named indexed field instead of asserting a bound. Lowers to ONE obligation whose successful evidence carries a `field` payload; the produced name enters the datum ledger ([`crate::field::FieldDatum`]).
    """

    form: Form6
    over: Annotated[
        str,
        Field(
            description="The index domain text after `over` (e.g. `liner.zones` or `travel in [-80mm, 120mm]`), kept as text like every other predicate-side expression in this AST (parsed structurally by the harness half, not the core)."
        ),
    ]
    quantity_kind: Annotated[
        str,
        Field(
            description="The dotted quantity-kind path (e.g. `thermo.wall_temperature`)."
        ),
    ]


class CopperArea(FrozenModel):
    """
    One named copper region's area (a `CopperSummary` entry).
    """

    area_mm2: Annotated[float, Field(description="Copper area, mm^2.")]
    region: Annotated[
        str, Field(description="The copper region name (a zone/pour identifier).")
    ]


class CoverageDomain1(FrozenModel):
    """
    A continuous domain, as text (e.g. `"[300K, 400K]"`).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    interval: str


class Values(FrozenModel):
    values: Annotated[list[str], Field(description="The enumerated values, as text.")]


class CoverageDomain2(FrozenModel):
    """
    A discrete domain (valve line-ups, failure states, ...).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    values: Values


class CoverageMethod1(StrEnum):
    """
    Corner-only sampling.
    """

    corners = "corners"


class KItem(RootModel[int]):
    root: Annotated[int, Field(ge=0)]


class Grid(FrozenModel):
    k: Annotated[list[KItem], Field(description="Per-axis grid resolution.")]


class CoverageMethod2(FrozenModel):
    """
    A grid with per-axis resolution `k` (multi-dim: `grid(k x m)`, the G29 demand).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    grid: Grid


class CoverageMethod3(StrEnum):
    """
    Every discrete value was enumerated.
    """

    enumerated = "enumerated"


class CoverageMethod4(StrEnum):
    """
    A closed-form analytic bound covers the whole domain.
    """

    analytic = "analytic"


class CoverageMethod5(StrEnum):
    """
    Declared monotonicity lets the worst corner stand for the domain.
    """

    monotone = "monotone"


class CoverageMethod6(StrEnum):
    """
    WO-33 D98: the axis is DECLARED (a `compute` claim's index domain) but not yet resolved by any model -- the honest pre-discharge state of a [`crate::field::FieldDatum`]'s axis (`payload: null`). Never appears once evidence has landed; a discharging model replaces it with the method it actually used.
    """

    undischarged = "undischarged"


class DatumKind(StrEnum):
    level = "level"


class Datum1(FrozenModel):
    """
    A named `level` declaration ref.
    """

    datum_kind: DatumKind
    value: str


class DatumKind1(StrEnum):
    elevation = "elevation"


class Declared(FrozenModel):
    source: Annotated[
        str,
        Field(
            description="The source fact the value came from (`pilot.diameter = 28mm`, `part datum: none orients gravity (D151)`)."
        ),
    ]
    value: Annotated[
        str, Field(description="The raw declared value text (`28mm`, `0`).")
    ]


class DerivedFact1(FrozenModel):
    """
    The value, with the declared source fact cited verbatim.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    declared: Declared


class Indeterminate(FrozenModel):
    reason: Annotated[
        str, Field(description="Why no declared source covers this field.")
    ]


class DerivedFact2(FrozenModel):
    """
    No declared source exists: honestly indeterminate, with the reason named.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    indeterminate: Indeterminate


class EdgeKind1(StrEnum):
    """
    A rigid pipe run (hydraulic loss from wetted geometry).
    """

    pipe = "pipe"


class EdgeKind2(StrEnum):
    """
    A flexible hose run (may carry a wall-compliance record).
    """

    hose = "hose"


class EdgeKind3(StrEnum):
    """
    A fixed restriction / metering orifice.
    """

    orifice = "orifice"


class EdgeKind4(StrEnum):
    """
    A valve (curve record, possibly with a commanded state var).
    """

    valve = "valve"


class EdgeKind5(StrEnum):
    """
    A pump (head/flow curve record; imposes pressure rise).
    """

    pump = "pump"


class EdgeKind6(StrEnum):
    """
    A regulator (imposes a controlled downstream pressure).
    """

    regulator = "regulator"


class EdgeKind7(StrEnum):
    """
    A filter (loss curve record).
    """

    filter = "filter"


class EdgeKind8(StrEnum):
    """
    An imposer (imposes a value via the derivation machinery).
    """

    imposer = "imposer"


class EdgeKind9(StrEnum):
    """
    A heat-exchanger segment (couples to a hematite zone datum).
    """

    hx_segment = "hx_segment"


class EdgeKind10(StrEnum):
    """
    A declared-outlet medium boundary (D142, WO-52): two or more inlet terminals on their own single-medium subnet, an outlet whose medium is DECLARED (never solved composition).
    """

    mixer = "mixer"


class Source(StrEnum):
    scalars = "scalars"


class Source1(StrEnum):
    geom_extract = "geom_extract"


class Source2(StrEnum):
    mixer_outlet = "mixer_outlet"


class Kind(StrEnum):
    segment = "segment"


class Entity1(FrozenModel):
    """
    A straight segment.
    """

    from_: Annotated[
        list[float],
        Field(
            alias="from", description="Segment start point.", max_length=2, min_length=2
        ),
    ]
    kind: Kind
    to: Annotated[
        list[float], Field(description="Segment end point.", max_length=2, min_length=2)
    ]


class Kind1(StrEnum):
    arc = "arc"


class Entity2(FrozenModel):
    """
    A circular arc.
    """

    center: Annotated[
        list[float], Field(description="Arc center.", max_length=2, min_length=2)
    ]
    end_angle: Annotated[float, Field(description="End angle, radians.")]
    kind: Kind1
    radius: Annotated[float, Field(description="Arc radius, mm.")]
    start_angle: Annotated[float, Field(description="Start angle, radians.")]


class Kind2(StrEnum):
    polyline = "polyline"


class Point(RootModel[list[float]]):
    root: Annotated[list[float], Field(max_length=2, min_length=2)]


class Entity3(FrozenModel):
    """
    An ordered polyline.
    """

    kind: Kind2
    points: Annotated[list[Point], Field(description="Vertices, in order.")]


class Kind3(StrEnum):
    symbol = "symbol"


class Entity4(FrozenModel):
    """
    A symbol instance (diagram glyph from a pack record, charter sec. 1 decision 6 -- never hard-coded art).
    """

    kind: Kind3
    origin: Annotated[
        list[float], Field(description="Placement origin.", max_length=2, min_length=2)
    ]
    record_digest: Annotated[
        str, Field(description="The hash-pinned symbol record digest.")
    ]
    rotation: Annotated[float, Field(description="Rotation, radians.")]


class FlowSegmentIr(FrozenModel):
    """
    One segment of a cavity-derived wetted flow path: the projection of one feature op in the inlet->outlet chain (D151), fields sourced per [`DerivedFact`]. Mirrors the realizer input's `FlowSegment` (D130) at the declared-fact level -- unit resolution and interval emission are the consumer's job.
    """

    bore: Annotated[
        str | None,
        Field(
            description="The feature binding this segment projects (`gallery`) -- the realizer's cross-validation reference."
        ),
    ] = None
    elevation_change: Annotated[
        DerivedFact1 | DerivedFact2,
        Field(
            description="Elevation change against the part datum (declared `0` with cited provenance when no datum orients gravity, D151)."
        ),
    ]
    flow_area: Annotated[
        DerivedFact1 | DerivedFact2,
        Field(
            description="Flow area's declared source: the op's minimum section (a hole op's declared diameter; the consumer derives area from it)."
        ),
    ]
    length: Annotated[
        DerivedFact1 | DerivedFact2,
        Field(description="Segment length (a hole op's declared depth)."),
    ]
    role: Annotated[
        str,
        Field(
            description="The seam's per-segment environment slot, from the op kind (`bore` for a hole op)."
        ),
    ]
    roughness_class: Annotated[
        DerivedFact1 | DerivedFact2,
        Field(
            description="Roughness class from the material/finish record the op cites."
        ),
    ]
    wall: Annotated[
        DerivedFact1 | DerivedFact2,
        Field(description="Wall record where the op has a wall-thickness derivation."),
    ]


class Material(RootModel[list[str]]):
    root: Annotated[list[str], Field(max_length=2, min_length=2)]


class Ref(RootModel[list[str]]):
    root: Annotated[list[str], Field(max_length=2, min_length=2)]


class Given(FrozenModel):
    """
    The `given:` context an obligation is evaluated under: the pinned facts (materials, loads, backing evidence) the discharge assumes.
    """

    backing: Annotated[
        list[str], Field(description="Backing evidence references the given relies on.")
    ]
    loads: Annotated[
        list[str], Field(description="Applied loads/environment, as text expressions.")
    ]
    materials: Annotated[
        list[Material],
        Field(description="Pinned material/component records (name -> content hash)."),
    ]
    refs: Annotated[
        list[Ref] | None,
        Field(
            description="Entity-field reference terms (D103): reference path (e.g. `comms.pa_out`) -> the resolved value-source text, for expression givens a general comparison claim's sides name.",
            validate_default=True,
        ),
    ] = []


class ImplRecord(FrozenModel):
    """
    A harness impl record for a signature (data only; the code lives in the Python harness).
    """

    cost: Annotated[int, Field(description="Relative cost hint for scheduling.", ge=0)]
    domain: Annotated[
        list[str], Field(description="The validity domain this impl covers.")
    ]
    error_model: Annotated[
        str, Field(description="The error-model tag (how `eps` is derived).")
    ]
    name: Annotated[str, Field(description="The impl's name (the discharge model id).")]
    signature: Annotated[str, Field(description="The signature this implements.")]


class LedgerEntry1(FrozenModel):
    """
    A `todo!` placeholder.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    todo: str


class LedgerEntry2(FrozenModel):
    """
    An `assume!` assumption.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    assume: str


class LedgerEntry3(FrozenModel):
    """
    An unwaived indeterminate discharge.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    indeterminate: str


class LoadKind1(StrEnum):
    """
    A distributed (area/length) load.
    """

    distributed = "distributed"


class LoadKind2(StrEnum):
    """
    A concentrated point load.
    """

    point = "point"


class LoadKind3(StrEnum):
    """
    An applied moment.
    """

    moment = "moment"


class MemberRole1(StrEnum):
    """
    A beam (primarily flexural member).
    """

    beam = "beam"


class MemberRole2(StrEnum):
    """
    A column (primarily axial vertical member).
    """

    column = "column"


class MemberRole3(StrEnum):
    """
    A brace (axial lateral-system member).
    """

    brace = "brace"


class MemberRole4(StrEnum):
    """
    A slab (planar surface member).
    """

    slab = "slab"


class MemberRole5(StrEnum):
    """
    A wall (planar vertical member).
    """

    wall = "wall"


class MemberRole6(StrEnum):
    """
    A footing (foundation member; MAY be point-anchored/zero-length -- calcite/03 sec. 4).
    """

    footing = "footing"


class MemberRole7(FrozenModel):
    """
    Any other declared role word, kept verbatim.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    other: str


class NetLength(FrozenModel):
    """
    One net's total routed length (a `CopperSummary` entry; a `Vec` of pairs rather than a map for AD-6 deterministic ordering across the FFI/JSON boundary).
    """

    length_mm: Annotated[
        float, Field(description="Total routed length for this net, mm.")
    ]
    net: Annotated[str, Field(description="The net name.")]


class ParasiticSlot(FrozenModel):
    """
    One extracted parasitic slot: a layout-dependent parasitic value (e.g. a trace's parasitic resistance/inductance/capacitance) shaped as a model-pack input, keyed by the net or segment it belongs to.
    """

    kind: Annotated[
        str,
        Field(
            description="The kind of parasitic quantity (e.g. `resistance_ohm`, `inductance_nh`, `capacitance_pf`) -- a coarse label rather than a closed enum since the extraction surface grows per WO-25 model pack needs."
        ),
    ]
    subject: Annotated[
        str,
        Field(description="The net or segment this parasitic value is extracted for."),
    ]
    value: Annotated[
        float, Field(description="The extracted value, in the unit implied by `kind`.")
    ]


class PayloadRef(FrozenModel):
    """
    A hash-pinned reference to a payload of a declared `kind`, crossing the `DischargeRequest.payloads` channel (D96). The kind vocabulary is feldspar 09 sec. 4's list VERBATIM: `geometry.parametric`, `geometry.realized`, `mesh`, `table`, `spectrum`, `profile`, `mask`, `field`, `flownet`, `plan`.
    """

    digest: Annotated[
        str, Field(description="The blake3 content digest of the payload bytes.")
    ]
    kind: Annotated[
        str,
        Field(
            description="The payload kind (feldspar 09 sec. 4 vocabulary, verbatim)."
        ),
    ]
    origin: Annotated[
        str,
        Field(
            description="The producing snapshot/record name, for diagnostics only (never part of the digest/identity)."
        ),
    ]


class Placement(FrozenModel):
    """
    One placed footprint on the board.
    """

    footprint: Annotated[
        str, Field(description="The footprint name resolved from the registry record.")
    ]
    position_mm: Annotated[
        list[float],
        Field(
            description="Placement position on the board, mm, board-outline-relative.",
            max_length=2,
            min_length=2,
        ),
    ]
    reference: Annotated[
        str,
        Field(
            description="The reference designator (e.g. `U1`, `R12`) the placement binds."
        ),
    ]
    rotation_deg: Annotated[
        float, Field(description="Placement rotation, degrees, board-outline-relative.")
    ]
    side: Annotated[
        BoardSide1 | BoardSide2,
        Field(description="Which side of the board this footprint is placed on."),
    ]


class Kind4(StrEnum):
    cause = "cause"


class Provenance1(FrozenModel):
    """
    The lockfile resolution cause (free-string label mirroring `regolith_qty::Cause`'s own wire shape, kept free-form here so this schema never re-imports `regolith-qty` for a display-only field).
    """

    kind: Kind4
    label: Annotated[
        str, Field(description="The cause label as the lockfile records it.")
    ]


class Kind5(StrEnum):
    record = "record"


class Provenance2(FrozenModel):
    """
    A content-addressed record (e.g. a realized-geometry or flownet payload digest) this value was read from.
    """

    digest: Annotated[
        str, Field(description="The blake3/sha256 digest of the source record.")
    ]
    kind: Kind5


class Kind6(StrEnum):
    obligation = "obligation"


class Provenance3(FrozenModel):
    """
    The obligation id whose discharge produced this value.
    """

    id: Annotated[str, Field(description="The obligation id.")]
    kind: Kind6


class RecordRef(FrozenModel):
    """
    A hash-pinned reference to a registry record (property table, vendor curve, wall record, realized-geometry snapshot). Refs are by digest ONLY -- resolution is the orchestrator's content-addressed store, never a pack's own IO (mirrors [`crate::payload::PayloadRef`]).
    """

    digest: Annotated[
        str,
        Field(
            description="The blake3 content digest of the referenced record's bytes."
        ),
    ]
    name: Annotated[
        str,
        Field(
            description="The producing record name, for diagnostics only (never part of the digest/identity)."
        ),
    ]


class Releases(FrozenModel):
    """
    The kept degrees of freedom at each end of a member's transfer (calcite/03 sec. 4: "the mating vocabulary IS the release model; no second encoding"). Empty until a transfer class's `dof: kept=` is resolved -- `std.civil`'s transfer-class records are a different slice's deliverable (WO-48 std.civil authoring); this schema carries the field honestly empty rather than fabricating a release set.
    """

    a: Annotated[
        list[str], Field(description="Kept DOF codes at the member's `a` end.")
    ]
    b: Annotated[
        list[str], Field(description="Kept DOF codes at the member's `b` end.")
    ]


class ResolvedFeatureParam(FrozenModel):
    """
    One resolved scalar parameter a feature constructor spelled, with its `Cause` tag (INV-21). `text` is the raw quantity/keyword text as parsed (e.g. `28mm`, `free`) -- this pass does not unit-convert or numerically resolve it (that is the harness/DFM pack's job); it only records WHAT was spelled and WHY (its provenance class).
    """

    cause: Annotated[
        str,
        Field(
            description="The INV-21 provenance class: `literal` for an ordinary spelled value, or one of `free`/`derived`/`allocated`/`planner` when the text itself is a value-source keyword (regolith/03 sec. 2's vocabulary) rather than a literal quantity."
        ),
    ]
    text: Annotated[
        str, Field(description="The raw parameter text as spelled in source.")
    ]


class RoutedSegment(FrozenModel):
    """
    One routed copper segment (a track) belonging to a net.
    """

    layer: Annotated[
        str,
        Field(
            description="The copper layer this segment was routed on (e.g. `F.Cu`, `B.Cu`, an inner layer name)."
        ),
    ]
    length_mm: Annotated[float, Field(description="Segment length, mm.")]
    net: Annotated[str, Field(description="The net this segment belongs to.")]
    width_mm: Annotated[float, Field(description="Track width, mm.")]


class Kind7(StrEnum):
    waypoints = "waypoints"


class Kind8(StrEnum):
    planner_free = "planner_free"


class ScalarInterval(FrozenModel):
    """
    A closed scalar interval `[lo, hi]` in a named unit -- the boundary representation for every numeric flownet field (a schema-friendly wire form of `regolith_qty::Interval`, whose internal representation is not itself a boundary type).
    """

    hi: Annotated[float, Field(description="The upper bound (`hi >= lo`).")]
    lo: Annotated[float, Field(description="The lower bound.")]
    unit: Annotated[
        str,
        Field(
            description='The unit both bounds are expressed in (e.g. `"Pa"`, `"m"`).'
        ),
    ]


class SegmentLength1(FrozenModel):
    """
    Pinned to a constraint value.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    pinned: float


class SegmentLength2(FrozenModel):
    """
    Declared `free`; the payload is the parameter name the resolution is recorded under (`c.length`).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    free: str


class SheetSize1(StrEnum):
    """
    ANSI A / 8.5x11 in.
    """

    ansi_a = "ansi_a"


class SheetSize2(StrEnum):
    """
    ANSI B / 11x17 in.
    """

    ansi_b = "ansi_b"


class SheetSize3(StrEnum):
    """
    ANSI C / 17x22 in.
    """

    ansi_c = "ansi_c"


class SheetSize4(StrEnum):
    """
    ISO A4.
    """

    iso_a4 = "iso_a4"


class SheetSize5(StrEnum):
    """
    ISO A3.
    """

    iso_a3 = "iso_a3"


class Input(RootModel[list[str]]):
    root: Annotated[list[str], Field(max_length=2, min_length=2)]


class Output(RootModel[list[str]]):
    root: Annotated[list[str], Field(max_length=2, min_length=2)]


class Signature(FrozenModel):
    """
    A physics-model signature: a typed input/output contract.
    """

    domain: Annotated[
        list[str], Field(description="Validity domain tags (`clamped`, `linear`).")
    ]
    inputs: Annotated[
        list[Input],
        Field(description="Input port names -> their quantity type (as text)."),
    ]
    name: Annotated[str, Field(description="Signature name (`bolted_joint_state`).")]
    outputs: Annotated[
        list[Output], Field(description="Output port names -> their quantity type.")
    ]


class SignatureAlgorithm1(StrEnum):
    """
    Ed25519 (RFC 8032) -- the only algorithm implemented in v1.
    """

    ed25519 = "ed25519"


class SignatureAlgorithm(RootModel[SignatureAlgorithm1]):
    root: Annotated[
        SignatureAlgorithm1,
        Field(
            description="The one signature algorithm this WO speaks. A closed enum (not a free string) so an unrecognized algorithm is a deserialization error, not a silently-accepted unknown."
        ),
    ]


class SignatureRegistry(FrozenModel):
    """
    The signature + impl registry the orchestrator matches discharge against.
    """

    impls: list[ImplRecord]
    signatures: dict[str, Signature]


class SnapshotRecord(FrozenModel):
    """
    One committed `EntityDb` scope's content-addressed snapshot, keyed by its scope name -- the WO-19 lowering pipeline emits one of these per scope (`docs/workflow/design-log/2026-07-04-cycle-11.md`).
    """

    hash: Annotated[
        str,
        Field(description="The scope's `EntityDb::snapshot_hash()` content address."),
    ]
    scope: Annotated[
        str,
        Field(description="The scope this snapshot belongs to (a declaration name)."),
    ]


class StateDomain(FrozenModel):
    """
    A symbolic state domain: either an edge parameter or a net-level state variable, left symbolic for the ONE-swept-obligation rule (regolith/07 sec. 2) rather than enumerated into obligation copies.
    """

    domain: Annotated[
        str,
        Field(
            description="The domain expression (the symbolic sweep set / discrete axis)."
        ),
    ]
    target: Annotated[
        str, Field(description="The target the state applies to (edge id or net name).")
    ]
    var: Annotated[
        str, Field(description="The state variable name (e.g. a valve line-up config).")
    ]


class Status1(StrEnum):
    """
    The claim holds with margin after the model's error.
    """

    discharged = "discharged"


class Status2(StrEnum):
    """
    The claim provably fails at its worst corner.
    """

    violated = "violated"


class Status3(StrEnum):
    """
    No adequate model, coverage, or trust; neither proven nor disproven (distinct from violated).
    """

    indeterminate = "indeterminate"


class Support(FrozenModel):
    """
    One synthesized support (calcite/03 sec. 4): a `support:` node's joint plus its fixed degrees of freedom.
    """

    fixity: Annotated[
        list[str],
        Field(
            description="The fixed DOF codes. Empty until the support role's fixity is resolved through `std.civil` (out of this slice's scope, honestly deferred rather than guessed)."
        ),
    ]
    joint: Annotated[str, Field(description="The support's joint id.")]


class SweepDomain(FrozenModel):
    """
    A sweep domain an obligation is instantiated over (one obligation per domain point; the obligation carries its own domain).
    """

    axis: Annotated[str, Field(description="The swept axis name.")]
    domain: Annotated[
        str,
        Field(
            description="The domain description (interval or discrete set, as text)."
        ),
    ]


class TableRow(FrozenModel):
    """
    One typed row in a [`Table`] (schedules: member/opening/area/BOM). Cells are stored as strings (the display form); numeric cells still trace back to a [`Dimension`]/record elsewhere when they represent a toleranced value.
    """

    cells: Annotated[list[str], Field(description="Cell values, in column order.")]


class TitleBlock(FrozenModel):
    """
    Title-block fields (charter sec. 1.7 title-block-completeness rule checks these are non-empty): the minimal set every drafting standard demands.
    """

    drawing_number: Annotated[
        str, Field(description="Drawing number (project-assigned, free string).")
    ]
    revision: Annotated[str, Field(description="Revision label.")]
    scale_label: Annotated[str, Field(description='Scale label as drawn (e.g. "1:2").')]
    subject: Annotated[
        str,
        Field(
            description="The name/id of the entity this drawing documents (e.g. the realized-part or flownet subject name)."
        ),
    ]
    title: Annotated[str, Field(description="Drawing/part/assembly title.")]


class TopologySummary(FrozenModel):
    """
    A platform-portable summary of a realized solid's shape (AD-6), promoted verbatim from WO-22's `TopologySummary` forward contract. Deliberately NOT the raw STEP bytes (OCCT's serializer is not byte- stable cross-platform/version, WO-22 acceptance) -- this is the cross-platform determinism golden.
    """

    area_mm2: Annotated[float, Field(description="Total surface area in mm^2.")]
    bbox_max_mm: Annotated[
        list[float],
        Field(
            description="Axis-aligned bounding-box maximum corner, mm.",
            max_length=3,
            min_length=3,
        ),
    ]
    bbox_min_mm: Annotated[
        list[float],
        Field(
            description="Axis-aligned bounding-box minimum corner, mm.",
            max_length=3,
            min_length=3,
        ),
    ]
    center_of_mass_mm: Annotated[
        list[float],
        Field(description="Center of mass, mm.", max_length=3, min_length=3),
    ]
    num_edges: Annotated[int, Field(description="Number of edges.", ge=0)]
    num_faces: Annotated[int, Field(description="Number of faces.", ge=0)]
    num_solids: Annotated[
        int, Field(description="Number of solids in the realized body.", ge=0)
    ]
    num_vertices: Annotated[int, Field(description="Number of vertices.", ge=0)]
    volume_mm3: Annotated[float, Field(description="Solid volume in mm^3.")]


class Unit(FrozenModel):
    pass


class EntityIndice(RootModel[int]):
    root: Annotated[int, Field(ge=0)]


class ViewSource(FrozenModel):
    """
    Which realized-IR digest a [`View`] projects, and how.
    """

    source_digest: Annotated[
        str,
        Field(
            description="The realized-IR content digest this view projects (provenance: a view can never disagree with the build state it renders)."
        ),
    ]
    source_kind: Annotated[
        str,
        Field(
            description='The payload kind the digest belongs to (`"geometry.realized"`, `"layout.realized"`, `"flownet"`) -- free string mirroring the existing domain-tag constants, kept free-form so this schema never depends on every producing crate\'s tag constant.'
        ),
    ]


class Waiver(FrozenModel):
    """
    A source-declared waiver: it matches some set of claims/rules and carries a basis (and optionally evidence, making it a deviation).
    """

    basis: Annotated[
        str,
        Field(
            description="The stated basis (regolith/12 rule 2 -- mandatory; an absent basis is an INV-2 overreach diagnostic raised at lowering)."
        ),
    ]
    evidence: Annotated[
        str | None,
        Field(
            description="Backing evidence reference, if this is a deviation (a `by` clause) rather than a bare, release-gated waiver."
        ),
    ] = None
    expires: Annotated[
        str | None, Field(description="Expiry marker, if any (regolith/12 rule 8).")
    ] = None
    scope: Annotated[
        str | None,
        Field(
            description="The `on <query>` scope pattern, if any; `None` is an unscoped waiver covering the target wherever it fails in the artifact."
        ),
    ] = None
    target: Annotated[
        str,
        Field(
            description="The rule or claim being waived (`dfm(min_web_thickness)`, `Group.claim`)."
        ),
    ]


class WaiverKind1(StrEnum):
    """
    The waiver matched one or more emitted obligations (recorded as the accepted match set); their true status is untouched.
    """

    matched = "matched"


class WaiverKind2(StrEnum):
    """
    The target is a rule-pack rule (`dfm`/`drc`/`erc`) the static core does not lower to obligations: recorded and release-gated, but NOT stale -- the core simply cannot see the target here.
    """

    deferred_rule_pack = "deferred_rule_pack"


class WaiverKind3(StrEnum):
    """
    The target is a claim the pipeline emits obligations for, yet the waiver matched none of them: a stale-waiver error (INV-12).
    """

    stale = "stale"


class WaiverRecord(FrozenModel):
    """
    A declared waiver plus its honesty outcome: the classification and the exact obligation content-hashes it accepted. This is the audit surface INV-12 requires -- every waiver appears here with its reason and match set; no waiver silently vanishes.
    """

    kind: Annotated[
        WaiverKind1 | WaiverKind2 | WaiverKind3,
        Field(description="Its relationship to the obligation set."),
    ]
    match_set: Annotated[
        list[str] | None,
        Field(
            description="D105(d): the sorted entity refs the waiver matched AT AUTHORSHIP time, so a later `regolith build` can diff prior lockfile match sets and report GROWTH as a named diagnostic (the waiver ladder's anti-rot residual). Schema field only here (WO-30); the diff pass is the WO-26 remainder's job."
        ),
    ] = []
    matched: Annotated[
        list[str],
        Field(
            description="The content hashes of the obligations this waiver accepted (empty for `DeferredRulePack`/`Stale`), in source order."
        ),
    ]
    waiver: Annotated[Waiver, Field(description="The declared waiver.")]


class Unsupported(FrozenModel):
    reason: Annotated[
        str,
        Field(description="What exactly the surface cannot express (names the step)."),
    ]


class WalkPromotion2(FrozenModel):
    """
    The walk is outside the v1 promotion surface, with the reason.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    unsupported: Unsupported


class Wall(FrozenModel):
    """
    A thin-wall record on a segment: Young's modulus (Pa), wall thickness (m), and (inner) diameter (m) -- the inputs to wall compliance and the Korteweg wave speed (D93), each an `[lo, hi]` interval.
    """

    diameter: Annotated[
        list[float],
        Field(description="Inner diameter interval, m.", max_length=2, min_length=2),
    ]
    thickness: Annotated[
        list[float],
        Field(description="Wall thickness interval, m.", max_length=2, min_length=2),
    ]
    youngs_modulus: Annotated[
        list[float],
        Field(description="Young's modulus interval, Pa.", max_length=2, min_length=2),
    ]


class Window1(FrozenModel):
    """
    `during <event-or-config-domain>`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    during: str


class WithinAfter(FrozenModel):
    duration: Annotated[
        str, Field(description="The bounding duration (source text; typed in qty).")
    ]
    event: Annotated[str, Field(description="The anchoring event.")]


class Window2(FrozenModel):
    """
    `within <duration> after <event>`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    within_after: WithinAfter


class Window3(FrozenModel):
    """
    `until <event>`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    until: str


class Attestation(FrozenModel):
    """
    A solver's signature over one evidence value's content address.

    Attaching, detaching, or re-signing (key rotation) an `Attestation` never changes the evidence's own hash (D-E): this type carries attribution metadata (which model/pack/key produced and vouched for the result) alongside the signature bytes, and nothing here is a hash input for `Evidence` itself.
    """

    algorithm: Annotated[
        SignatureAlgorithm, Field(description="The signature algorithm.")
    ]
    key_id: Annotated[
        str,
        Field(
            description="The signing key's identifier (matched against the consumer's magnetite key-set designations at verification time, INV-14/INV-28)."
        ),
    ]
    model_id: Annotated[
        str,
        Field(description="The discharging model's id (matches `Evidence::model_id`)."),
    ]
    pack_name: Annotated[
        str, Field(description="The signing solver pack's name (AD-19 pack identity).")
    ]
    pack_version: Annotated[
        str, Field(description="The signing solver pack's version.")
    ]
    signature_base64: Annotated[
        str,
        Field(
            description="The signature bytes, base64-encoded on the wire (JSON has no native byte type; the Python side decodes before verifying)."
        ),
    ]


class BlockRequirement(FrozenModel):
    """
    One abstract resource block's raw capability demand, projected from a single `resources:`/`memories:`/`peripherals:` entry that carries a `promises:` keyword argument. The `BlockRequirement`-shaped lowering output WO-24's allocation search screens candidates against.
    """

    block: Annotated[
        str,
        Field(
            description="The abstract block/resource name the demand is FOR (`cpu0`, `sram`, `dma`): the allocation-search block identity."
        ),
    ]
    contract: Annotated[
        str,
        Field(
            description="The stdlib block-contract kind the resource instantiates (`executor`, `memory`, `mover`, `fabric`): the demand's vocabulary namespace."
        ),
    ]
    demands: Annotated[
        list[CapabilityDemand],
        Field(
            description="The raw capability demands spelled in this block's `promises:` argument, in source order (AD-6)."
        ),
    ]
    owner: Annotated[
        str,
        Field(
            description="The owning `architecture for <owner>:` target (the computer this block belongs to, `FlightCore`): grouping + traceability."
        ),
    ]


class ClaimForm2(FrozenModel):
    """
    `peak(x, during w) <op> <rhs>` (D102: a REDUCTION form that yields a scalar and requires an external comparator).
    """

    form: Form1
    op: Annotated[str, Field(description="The external comparator (`<`, `<=`, ...).")]
    rhs: Annotated[str, Field(description="The bound expression.")]
    signal: Annotated[str, Field(description="The signal expression.")]
    window: Annotated[
        Window1 | Window2 | Window3, Field(description="The evaluation window.")
    ]


class ClaimForm3(FrozenModel):
    """
    `settles(x, to=tol, within d after e)`. A CONTAINMENT form (D102): self-contained, no external comparator (its `tol` IS the acceptance).
    """

    form: Form2
    signal: Annotated[str, Field(description="The signal expression.")]
    tol: Annotated[str, Field(description="Settling tolerance text.")]
    window: Annotated[
        Window1 | Window2 | Window3, Field(description="The bounding window.")
    ]


class ClosureSegment(FrozenModel):
    """
    One straight segment of a closed walk: its heading and length.
    """

    angle_deg: Annotated[
        float,
        Field(
            description="Heading in degrees, counterclockwise from +x (`0` = right, `90` = up -- the walk's cardinal direction words)."
        ),
    ]
    length: Annotated[
        SegmentLength1 | SegmentLength2,
        Field(description="The segment length: pinned or free."),
    ]
    name: Annotated[str, Field(description="Segment name (for diagnostics).")]


class Compliance(FrozenModel):
    """
    Wall compliance and wave-speed parameters for a compliant edge (D93). Present only for edges named by transient/volume-budget claims; a rigid edge carries `None`.
    """

    snapshot_hash: Annotated[
        str,
        Field(
            description="The realized-geometry snapshot hash the fields were cited to (extraction provenance; empty when compliance came from a record ref rather than extraction)."
        ),
    ]
    wall_compliance: Annotated[
        ScalarInterval,
        Field(
            description="The wall compliance `dV/dp` interval (volume gained per unit pressure rise over the edge's wetted length)."
        ),
    ]
    wave_speed: Annotated[
        ScalarInterval,
        Field(description="The Korteweg wave speed interval for the edge."),
    ]


class CopperSummary(FrozenModel):
    """
    Board-wide copper-usage summary (post-route extraction surface, mirroring `regolith.realizer.elec.extraction.LayoutExtraction`'s field shapes but keyed for the schema, not a bare mapping).
    """

    copper_areas_mm2: Annotated[
        list[CopperArea],
        Field(
            description="Total copper area per named copper region (a zone/pour), mm^2."
        ),
    ]
    net_lengths_mm: Annotated[
        list[NetLength], Field(description="Total routed track length per net, mm.")
    ]


class CoverageAxis(FrozenModel):
    """
    One axis of structured coverage: the swept variable, its domain, and the method used to cover it (D95, sec. 8.2).
    """

    axis: Annotated[str, Field(description="The swept axis name.")]
    domain: Annotated[
        CoverageDomain1 | CoverageDomain2,
        Field(description="The axis's domain (continuous or discrete)."),
    ]
    method: Annotated[
        CoverageMethod1
        | CoverageMethod2
        | CoverageMethod3
        | CoverageMethod4
        | CoverageMethod5
        | CoverageMethod6,
        Field(description="The method used to cover this axis."),
    ]


class Datum2(FrozenModel):
    """
    A raw elevation quantity.
    """

    datum_kind: DatumKind1
    value: ScalarInterval


class Dimension(FrozenModel):
    """
    One dimension on a sheet: a resolved value with a MANDATORY provenance field (charter sec. 1 decision 3 -- the schema makes an unattributed number unrepresentable).
    """

    anchor: Annotated[
        list[float],
        Field(
            description="Anchor point on the sheet (leader/witness-line origin).",
            max_length=2,
            min_length=2,
        ),
    ]
    provenance: Annotated[
        Provenance1 | Provenance2 | Provenance3,
        Field(description="MANDATORY: where this value came from (never omittable)."),
    ]
    role: Annotated[
        str,
        Field(
            description='The interface/feature role this dimension documents (e.g. `"bore.diameter"`), matched against contract-coverage checking.'
        ),
    ]
    tolerance: Annotated[
        list[float] | None,
        Field(
            description="Optional tolerance band `[lo, hi]` in `unit`; a toleranced dimension is what the contract-coverage check demands appear somewhere on the sheet set.",
            max_length=2,
            min_length=2,
        ),
    ] = None
    unit: Annotated[str, Field(description="The unit the value is expressed in.")]
    value: Annotated[float, Field(description="The resolved value, in `unit`.")]
    view_name: Annotated[
        str, Field(description="The view (by name) this dimension is drawn against.")
    ]


class EdgeParams1(FrozenModel):
    """
    Literal scalar-interval parameters keyed by name (e.g. `"area"`, `"length"`, `"roughness"`).
    """

    source: Source
    values: Annotated[
        dict[str, ScalarInterval],
        Field(
            description="Parameter name -> interval; `BTreeMap` for deterministic key order (AD-6)."
        ),
    ]


class EdgeParams2(FrozenModel):
    """
    Parameters derived from a realized-geometry record via a path/role selector (D99/F102 extraction seam).
    """

    record: Annotated[
        RecordRef,
        Field(
            description="The realized-geometry record the parameters are extracted from."
        ),
    ]
    selector: Annotated[
        str,
        Field(
            description='The path/role selector into that record (e.g. `"coolant_jacket.wetted"`).'
        ),
    ]
    source: Source1


class FeatureOp(FrozenModel):
    """
    One feature op materialized from a `then:` claim-scope constructor call (the SAME structured calls deliverable 2's entity projector reads, `claim_scope::feature_calls_in_decl` -- one traversal, two consumers, AD-17/NO DUPLICATION).
    """

    constructor: Annotated[
        str,
        Field(
            description="The constructor verb actually spelled (`Bore`, `CBore`, `Pierce`, `Bend`, ...) -- a stable discriminant alongside the coarse kind."
        ),
    ]
    count: Annotated[
        int,
        Field(
            description="Orbit multiplicity: `n=N` for a `PatternOf<...>(n=N)` orbit, else 1 (matches deliverable 2's per-instance entity count).",
            ge=0,
        ),
    ]
    kind: Annotated[
        str,
        Field(
            description="The domain kind this op materializes (`hole`, `bend`) -- mirrors `regolith_sem::EntityKind`'s two domain variants at the string level (this type does not depend on `regolith-sem`)."
        ),
    ]
    name: Annotated[
        str,
        Field(description="The feature's local binding (`pilot`, `mounts`, `flange`)."),
    ]
    params: Annotated[
        dict[str, ResolvedFeatureParam],
        Field(
            description="The well-known scalar measures this constructor spelled (`diameter`/`depth`/`edge_distance` for a hole, `angle`/`radius` for a bend), each Cause-tagged."
        ),
    ]
    process: Annotated[
        str | None,
        Field(
            description="The enclosing stage's `process=<name>` head word (`cnc_mill`), when spelled (WO-51)."
        ),
    ] = None
    stage: Annotated[
        str | None,
        Field(
            description="The enclosing `stage <name>:` header's name (WO-51: the realizer's stage attribution); `None` for a stage-less op."
        ),
    ] = None


class FieldDatum(FrozenModel):
    """
    One computed indexed field's ledger entry: a named quantity over one index axis (a zone set or a config interval), plus its discharge payload once resolved.
    """

    axis: Annotated[
        CoverageAxis,
        Field(
            description="The field's index axis: the domain declared by the `over` clause, plus the method it was resolved with (`Undischarged` pre-evidence -- see [`crate::evidence::CoverageMethod::Undischarged`])."
        ),
    ]
    name: Annotated[
        str, Field(description="The field's name (the `compute <name>: ...` binding).")
    ]
    payload: Annotated[
        PayloadRef | None,
        Field(
            description='The discharged field payload (`kind: "field"`), or `None` before any model has produced one.'
        ),
    ] = None
    quantity_kind: Annotated[
        str,
        Field(
            description="The dotted quantity-kind path (e.g. `thermo.wall_temperature`)."
        ),
    ]


class FlowPathIr(FrozenModel):
    """
    One cavity-derived wetted flow path (D151/D152: the ONLY flow_paths source): the feature-op chain between the cavity query's named inlet and outlet port faces, in op-graph (source) order.
    """

    inlet: Annotated[
        str, Field(description="The inlet port reference as spelled (`inlet.mouth`).")
    ]
    outlet: Annotated[
        str,
        Field(
            description="The outlet port reference as spelled; empty when the query names no outlet (the chain is the inlet op alone)."
        ),
    ]
    segments: Annotated[
        list[FlowSegmentIr],
        Field(description="The chain's segments in source order (AD-6)."),
    ]
    selector: Annotated[
        str,
        Field(description="D130's pinned selector convention: `<stage_name>.wetted`."),
    ]


class FrameLoad(FrozenModel):
    """
    One load-case entry (calcite/03 sec. 4): a literal magnitude over a declared target, from a `loads:` field carrying a quantity literal and an `on [...]` target clause. `derived` self-weight rows and pack-model refs (`site.x -> std.civil.y`, resolved through the `effects:` derivation-obligation mechanism, calcite/03 sec. 2) are NOT payload load entries -- they are ordinary derived givens on the obligations that consume them, not literal frame data.
    """

    case: Annotated[
        str,
        Field(description="The load case's declared name (e.g. `pedestrian`, `live`)."),
    ]
    direction: Annotated[
        str,
        Field(
            description='The load\'s direction descriptor (`"gravity"` in v1 -- calcite/03 sec. 4 does not yet specify a direction vocabulary beyond the gravity-dominant case every corpus design exercises).'
        ),
    ]
    kind: Annotated[
        LoadKind1 | LoadKind2 | LoadKind3,
        Field(description="The load's distribution shape."),
    ]
    target: Annotated[
        str, Field(description="The load's target (a member or joint name).")
    ]
    value: Annotated[
        ScalarInterval, Field(description="The load's magnitude interval.")
    ]


class FrameMember(FrozenModel):
    """
    One structural member (calcite/03 sec. 4): its joints, geometry (derived from grid/level datums), resolved section/material, and end releases.
    """

    a: Annotated[str, Field(description="The `a`-end joint id.")]
    b: Annotated[
        str,
        Field(
            description="The `b`-end joint id (equal to `a` for a point-anchored footing -- calcite/03 sec. 4, legal, not a lowering error)."
        ),
    ]
    id: Annotated[str, Field(description="The member's declared name.")]
    length: Annotated[
        ScalarInterval,
        Field(
            description="The member's span length, derived from its two anchors' grid/level datums (zero for a point-anchored footing)."
        ),
    ]
    material: Annotated[
        RecordRef, Field(description="The resolved material record ref.")
    ]
    orientation: Annotated[
        str,
        Field(
            description='A deterministic descriptor of the member\'s spatial orientation (`"vertical"` / `"horizontal"` / `"inclined"` / `"point"`), derived from which datum axes differ between its two anchors.'
        ),
    ]
    releases: Annotated[
        Releases, Field(description="The kept-DOF releases at each end.")
    ]
    role: Annotated[
        MemberRole1
        | MemberRole2
        | MemberRole3
        | MemberRole4
        | MemberRole5
        | MemberRole6
        | MemberRole7,
        Field(description="The member's structural role."),
    ]
    section: Annotated[
        RecordRef,
        Field(
            description='The resolved section record ref (post-L3); the pre-resolution placeholder (`RecordRef { name: "free", digest: "" }`) when the member\'s `section: free` has not yet been resolved (AD-25 verbatim).'
        ),
    ]


class JointAt(FrozenModel):
    """
    A joint's resolved position: the grid refs (in declaration order) plus its level/elevation datum. `None` (on [`Joint::at`]) for a support-only joint whose anchor is not yet resolvable at this front end (the AD-25 GeomExtract placeholder idiom, applied to position rather than geometry: honestly indeterminate, not fabricated).
    """

    datum: Annotated[Datum1 | Datum2, Field(description="The joint's vertical datum.")]
    grid_refs: Annotated[
        list[str],
        Field(
            description='The grid refs naming this joint\'s plan position (e.g. `["A"]` or `["A", "2"]`), in the order they appeared in the member anchor line.'
        ),
    ]


class LedgerEntry4(FrozenModel):
    """
    A waiver that matched and shadowed a claim/rule, with its match set (INV-12 audit surface).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    waived: WaiverRecord


class MediumRef(FrozenModel):
    """
    The property-record refs pinning the working medium (density, bulk modulus, viscosity, vapour pressure). A flownet is single-medium at the payload level (FOPEN-1 is enforced upstream of construction, in `regolith_lower::fluid::check_flownet`'s `impl FluidPort<medium=...>` binding check, WO-49 -- diagnostic `E0210`).
    """

    records: Annotated[
        list[RecordRef],
        Field(description="The hash-pinned property records describing the medium."),
    ]


class PathSegment(FrozenModel):
    """
    One realized routed segment: the wetted-geometry measures the WO-32 `regolith-lower::extract` seam reads to fill an `EdgeParams::GeomExtract` selector (D131 -- the seam's field list verbatim).
    """

    bend: Annotated[Bend | None, Field(description="Optional bend geometry.")] = None
    elevation_change: Annotated[
        list[float],
        Field(
            description="Signed elevation change over the segment (outlet minus inlet) interval, m.",
            max_length=2,
            min_length=2,
        ),
    ]
    flow_area: Annotated[
        list[float],
        Field(
            description="Wetted flow area interval, m^2.", max_length=2, min_length=2
        ),
    ]
    length: Annotated[
        list[float],
        Field(description="Centreline length interval, m.", max_length=2, min_length=2),
    ]
    role: Annotated[
        str,
        Field(
            description="Per-segment environment slot name (shared with WO-34 wire runs)."
        ),
    ]
    roughness_class: Annotated[
        str,
        Field(
            description="Process-capability roughness class label (free string, resolved against `regolith-lower::extract`'s `ROUGHNESS_TABLE`; not an enum -- the table is the single home for valid labels, D131)."
        ),
    ]
    wall: Annotated[
        Wall | None,
        Field(
            description="Optional wall record (geometry only; the seam combines this with a medium's properties to derive compliance/wave speed)."
        ),
    ] = None


class Qty(FrozenModel):
    magnitude: float
    unit: Unit


class RealizedLayout(FrozenModel):
    """
    The serialized realized-layout payload (AD-25, WO-24's placed/routed board content): a board outline reference, every placement, every routed segment, a copper summary, extracted parasitic slots, and the `.kicad_pcb` content-hash pin.
    """

    board_outline_ref: Annotated[
        str,
        Field(
            description="A reference to the board outline this layout was placed within (e.g. the mech interface outline-import record id/hash)."
        ),
    ]
    copper: Annotated[
        CopperSummary, Field(description="The board-wide copper-usage summary.")
    ]
    kicad_pcb_content_hash: Annotated[
        str,
        Field(
            description="The SHA-256 content hash of the routed `.kicad_pcb` file (the pinned native side artifact; verify-only L4 re-import per regolith/08)."
        ),
    ]
    netlist_hash: Annotated[
        str,
        Field(
            description="The content hash of the bound netlist this layout was routed from (provenance; the G42 anti-staleness citation)."
        ),
    ]
    parasitics: Annotated[
        list[ParasiticSlot],
        Field(
            description="Every extracted parasitic slot (realizer-sorted for determinism, AD-6)."
        ),
    ]
    placements: Annotated[
        list[Placement],
        Field(
            description="Every placed footprint (realizer-sorted for determinism, AD-6)."
        ),
    ]
    routed_segments: Annotated[
        list[RoutedSegment],
        Field(
            description="Every routed segment (realizer-sorted for determinism, AD-6)."
        ),
    ]


class Reference(FrozenModel):
    """
    The datum node and its imposed reference state (the one node whose pressure/temperature is fixed, anchoring the network solve).
    """

    node: Annotated[str, Field(description="The datum node id.")]
    p: Annotated[
        ScalarInterval, Field(description="The imposed pressure interval at the datum.")
    ]
    t: Annotated[
        ScalarInterval,
        Field(description="The imposed temperature interval at the datum."),
    ]


class Resolution(FrozenModel):
    """
    A resolved value with its cause: one lockfile row. There is no way to build one without a `Cause` (INV-21).
    """

    cause: Annotated[
        Cause1
        | Cause3
        | Cause5
        | Cause7
        | Cause9
        | Cause11
        | Cause13
        | Cause15
        | Cause17,
        Field(
            description="Why a value resolved to what it did. Mandatory on every resolution (INV-21). The variants mirror the resolving mechanisms."
        ),
    ]
    value: Qty


class RoutedPath(FrozenModel):
    """
    A resolved routed path: an ordered list of segments (D131). Keyed by selector in [`RealizedGeometry::paths`]; the pinned convention for mech-emitted paths is `<stage_name>.wetted` (D130).
    """

    segments: Annotated[
        list[PathSegment], Field(description="The path's segments, in order.")
    ]


class RunRoute2(FrozenModel):
    """
    `route: free`: planner-routed. `resolved_length` is `None` until the planner materializes a lockfile row (`cause: planner(route <run>)`, `regolith_qty::Cause::Planner`); a consumer reading a run with `resolved_length: None` sees an honestly indeterminate length, never a fabricated one.
    """

    kind: Kind8
    resolved_length: Annotated[
        ScalarInterval | None,
        Field(description="The planner-resolved length, once materialized."),
    ] = None


class RunSegment(FrozenModel):
    """
    One segment of a run's routed path: a structural ref extracted through the shared WO-32 seam, with its resolved length and the per-segment environment role (the seam's shared "wire run is a multi-segment path" shape, `regolith_lower::extract` module doc).
    """

    length: Annotated[
        ScalarInterval, Field(description="The extracted centreline length, m.")
    ]
    role: Annotated[
        str,
        Field(
            description="The segment's environment role (shared slot with fluid edges)."
        ),
    ]
    structural_ref: Annotated[
        str,
        Field(
            description='The structural ref this segment was extracted along (e.g. `"frame.spine_tube"`).'
        ),
    ]


class SketchClosure(FrozenModel):
    """
    The typed closure problem for one profile walk.
    """

    close_edge: Annotated[
        str | None,
        Field(
            description="The labeled implicit return edge of a planar `close` (`d: close`), when the walk has one: recorded for the payload (the close edge is an unconstrained 2-DOF vector -- the closure gap itself), NOT a [`ClosureSegment`]. [`close_walk`] treats the explicit segments as the full loop; solving a problem whose close edge absorbs the gap is the solver's next increment."
        ),
    ] = None
    profile: Annotated[
        str,
        Field(
            description="The profile the walk belongs to (names diagnostics/resolutions)."
        ),
    ]
    segments: Annotated[
        list[ClosureSegment],
        Field(description="Segments in walk order (AD-6: fixed summation order)."),
    ]
    unit: Annotated[
        Unit,
        Field(
            description="The unit pinned lengths are expressed in (resolved free lengths carry it too)."
        ),
    ]


class Table(FrozenModel):
    """
    A schedule table (member schedule, opening schedule, area schedule, BOM) -- the ONE schedule mechanism (charter/AD-27: schedules are `tables` in the same IR, not a second mechanism).
    """

    columns: Annotated[list[str], Field(description="Column headers, in order.")]
    rows: Annotated[list[TableRow], Field(description="Rows, in order.")]
    title: Annotated[
        str,
        Field(description='Table title (e.g. "Member Schedule", "Bill of Materials").'),
    ]


class View(FrozenModel):
    """
    One named view on a sheet: a projection (mech/civil) or a schematic layout (fluid P&ID, elec one-line) of a [`ViewSource`].
    """

    entity_indices: Annotated[
        list[EntityIndice],
        Field(
            description="Entity indices (into [`DrawingModel::entities`]) belonging to this view, in stable order."
        ),
    ]
    name: Annotated[
        str, Field(description='View name (e.g. "front", "top", "isometric", "pid").')
    ]
    plane: Annotated[
        str,
        Field(
            description='The projection plane/axis label, free string (e.g. "XY", "XZ", or "schematic" for net-derived diagrams that are not a geometric projection, charter sec. 1 decision 6).'
        ),
    ]
    scale: Annotated[
        float, Field(description='Drawing scale as a ratio, e.g. 0.5 for "1:2".')
    ]
    source: Annotated[
        ViewSource, Field(description="The realized-IR source this view projects.")
    ]


class WaiveLedger(FrozenModel):
    """
    The build's todo/assume/waive ledger.
    """

    entries: list[LedgerEntry1 | LedgerEntry2 | LedgerEntry3 | LedgerEntry4]


class WalkPromotion1(FrozenModel):
    """
    The walk promoted into a typed closure problem.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    promoted: SketchClosure


class Claim(FrozenModel):
    """
    A single named claim inside a `require` group.
    """

    forall: Annotated[
        list[str],
        Field(description="`forall <cfg>` config axes the claim quantifies over."),
    ]
    form: Annotated[
        ClaimForm1
        | ClaimForm2
        | ClaimForm3
        | ClaimForm4
        | ClaimForm5
        | ClaimForm6
        | ClaimForm7,
        Field(description="The claim form."),
    ]
    hints: Annotated[list[str], Field(description="Discharge-model hints (`@hint`).")]
    model_pin: Annotated[
        str | None, Field(description="A `model=` pin selecting the discharge model.")
    ] = None
    name: Annotated[str | None, Field(description="Optional claim name.")] = None
    scatter_factor: Annotated[
        float | None, Field(description="Scatter factor (`scatter_factor=`), if any.")
    ] = None
    sf: Annotated[float | None, Field(description="Safety factor (`sf=`), if any.")] = (
        None
    )
    trust_floor: Annotated[
        str | None,
        Field(description="Minimum required evidence trust tier (`trust: >= tier`)."),
    ] = None


class Coverage(FrozenModel):
    """
    Structured coverage (D95, sec. 8.2): per-axis coverage plus the conservative scalar collapse kept for margin notes and old consumers -- `fraction` must never overstate what `axes` states. `Evidence`/`SolverResponse` carry this instead of a bare float.
    """

    axes: Annotated[
        list[CoverageAxis],
        Field(
            description="The per-axis coverage record (empty for a closed-form/full claim)."
        ),
    ]
    fraction_bits: Annotated[
        int,
        Field(
            description="The conservative scalar collapse (`1.0` = full), as `f64` bits.",
            ge=0,
        ),
    ]


class EdgeParams3(FrozenModel):
    """
    A `Mixer` edge's declared outlet medium (D142, WO-52): the property-record refs for the medium named by `outlet=<medium>`. Per-subnet payloads stay structurally single-medium -- this is the ONE place a `flownet` payload carries a second `MediumRef`, and it names the far side of the boundary, never a merged or solved composition.
    """

    outlet: Annotated[
        MediumRef,
        Field(description="The declared outlet medium's property-record refs."),
    ]
    source: Source2


class Evidence(FrozenModel):
    """
    The evidence produced by discharging one obligation.
    """

    cost: Annotated[int, Field(description="Relative cost incurred.", ge=0)]
    coverage: Annotated[
        Coverage,
        Field(
            description="Structured per-axis coverage (D95, sec. 8.2); `Coverage::full()` for a closed-form/full claim."
        ),
    ]
    eps_bits: Annotated[int, Field(description="The model error `eps`'s bits.", ge=0)]
    hash: Annotated[
        str, Field(description="Content hash of this evidence (cache key component).")
    ]
    margin_bits: Annotated[
        int,
        Field(
            description="The margin after error (`limit - (value + eps)`)'s bits.", ge=0
        ),
    ]
    model_id: Annotated[
        str, Field(description="The discharge model id that produced this.")
    ]
    status: Annotated[
        Status1 | Status2 | Status3, Field(description="The discharge status.")
    ]
    value_bits: Annotated[
        int,
        Field(
            description="The computed value's bits (f64 as bits for exact serialization).",
            ge=0,
        ),
    ]


class EvidenceCache(FrozenModel):
    """
    A cache of evidence keyed on (subject, contract, registry versions), so a second run is a hit.
    """

    entries: dict[str, Evidence]


class FeatureProgram(FrozenModel):
    """
    The (partial, per the scope note above) feature program for one declaration: every `FeatureOp` its `then:` claim scopes construct, in source order (AD-6).
    """

    features: Annotated[
        list[FeatureOp], Field(description="Feature ops in source order.")
    ]
    flow_paths: Annotated[
        list[FlowPathIr] | None,
        Field(
            description="Cavity-derived wetted flow paths (D151/D152), one per `.cavity(inlet=...)` query the part spells."
        ),
    ] = None
    part_name: Annotated[
        str, Field(description="The declaration name this program belongs to.")
    ]
    sketches: Annotated[
        dict[str, WalkPromotion1 | WalkPromotion2] | None,
        Field(
            description="The typed sketch payload per profile this part's ops reference (WO-51: the promoted walk, or the NAMED unsupported reason -- zero silent gaps), keyed by profile name in reference order."
        ),
    ] = None


class FlowEdge(FrozenModel):
    """
    One flow edge: a directed (positive-sense `a -> b`) network element with its kind, parameters, optional wall compliance, and any vendor curve records.
    """

    a: Annotated[str, Field(description="The positive-sense tail node.")]
    b: Annotated[str, Field(description="The positive-sense head node.")]
    compliance: Annotated[
        Compliance | None,
        Field(description="Wall compliance + wave speed, when the edge is compliant."),
    ] = None
    curves: Annotated[
        list[RecordRef],
        Field(
            description="Hash-pinned vendor/datasheet curve records (valve/pump/filter)."
        ),
    ]
    id: Annotated[str, Field(description="The stable edge id (elaboration-assigned).")]
    kind: Annotated[
        EdgeKind1
        | EdgeKind2
        | EdgeKind3
        | EdgeKind4
        | EdgeKind5
        | EdgeKind6
        | EdgeKind7
        | EdgeKind8
        | EdgeKind9
        | EdgeKind10,
        Field(description="The constructor kind."),
    ]
    params: Annotated[
        EdgeParams1 | EdgeParams2 | EdgeParams3,
        Field(
            description="The edge's hydraulic parameters (scalars or a geometry-extract selector)."
        ),
    ]


class FlownetPayload(FrozenModel):
    """
    The serialized flownet payload (fluorite/03 sec. 2, verbatim): a content-addressed record carrying the medium, topology, datum, edges, and symbolic state domains a solver pack needs to solve the network.
    """

    edges: Annotated[
        list[FlowEdge],
        Field(description="Every flow edge (elaboration-sorted for determinism)."),
    ]
    medium: Annotated[
        MediumRef, Field(description="The working-medium property-record refs.")
    ]
    nodes: Annotated[
        list[str],
        Field(
            description="Every node in the network (elaboration-sorted for determinism)."
        ),
    ]
    reference: Annotated[
        Reference, Field(description="The datum node and its imposed reference state.")
    ]
    states: Annotated[
        list[StateDomain],
        Field(description="Symbolic edge-parameter and net-level state domains."),
    ]


class Joint(FrozenModel):
    """
    One synthesized joint (calcite/03 sec. 4): member ends meeting at a shared anchor coalesce onto the SAME joint id (the partition key is the anchor's canonical grid/level tuple); a declared `support:` node with no member anchor of its own gets a distinct joint with `at: None`.
    """

    at: Annotated[
        JointAt | None,
        Field(description="The joint's resolved grid/level position, when known."),
    ] = None
    id: Annotated[str, Field(description="The stable joint id.")]


class Obligation(FrozenModel):
    """
    A self-contained verification obligation.
    """

    claim: Annotated[Claim, Field(description="The claim being discharged.")]
    given: Annotated[Given, Field(description="The pinned evaluation context.")]
    hints: Annotated[
        list[str], Field(description="Discharge hints carried from the claim/symmetry.")
    ]
    payloads: Annotated[
        list[PayloadRef] | None,
        Field(
            description="General content-addressed payload refs this obligation carries (D129): any D96 kind (`flownet` first; `field`, `geometry.realized`, `plan` are known future riders). A GENERAL vector channel, not a single-purpose slot, so future payload kinds never need another `Obligation` field.",
            validate_default=True,
        ),
    ] = []
    subject_ref: Annotated[
        str,
        Field(
            description="Content-addressed reference to the subject (entity/snapshot hash)."
        ),
    ]
    sweep: Annotated[
        SweepDomain | None,
        Field(description="The sweep domain this obligation instance carries, if any."),
    ] = None


class RealizedGeometry(FrozenModel):
    """
    The serialized realized-geometry payload (AD-25, WO-22's forward contract promoted + unified per D131 onto the WO-32 extract seam's consumed shape): one realized part's STEP content hash, mass/topology summary, and selector-keyed routed paths.
    """

    feature_program_hash: Annotated[
        str,
        Field(
            description="The content hash of the `FeatureProgram` this geometry was realized from (provenance; the G42 anti-staleness citation)."
        ),
    ]
    paths: Annotated[
        dict[str, RoutedPath],
        Field(
            description="Every routed path, keyed by selector (`<stage_name>.wetted` convention, D130). No per-stage struct: per-stage structure is realized purely by the selector-key convention (D131)."
        ),
    ]
    step_content_hash: Annotated[
        str,
        Field(
            description="The SHA-256 content hash of the normalized STEP export (WO-22's determinism note: OCCT's own STEP serialization is not byte- stable cross-platform, so `topology` is the cross-platform golden and this hash pins the side-artifact STEP bytes)."
        ),
    ]
    topology: Annotated[
        TopologySummary,
        Field(
            description="The cross-platform-stable topology/mass-properties summary."
        ),
    ]


class RunRoute1(FrozenModel):
    """
    `along <structural refs>`: every ref extracted and concatenated in declaration order.
    """

    kind: Kind7
    segments: Annotated[
        list[RunSegment],
        Field(description="The extracted segments, in declaration order."),
    ]
    snapshot_hash: Annotated[
        str,
        Field(
            description="The realized-geometry snapshot hash every segment is cited to."
        ),
    ]
    total_length: Annotated[
        ScalarInterval, Field(description="Sum of the segment lengths, m.")
    ]


class Sheet(FrozenModel):
    """
    One sheet: paper size, title block, its views, and the entities/ dimensions/annotations/tables placed on it.
    """

    annotations: Annotated[
        list[Annotation],
        Field(description="Annotations on this sheet, in stable order."),
    ]
    dimensions: Annotated[
        list[Dimension], Field(description="Dimensions on this sheet, in stable order.")
    ]
    entities: Annotated[
        list[Entity1 | Entity2 | Entity3 | Entity4],
        Field(
            description="Projected/schematic entities, in stable order (referenced by index from [`View::entity_indices`])."
        ),
    ]
    size: Annotated[
        SheetSize1 | SheetSize2 | SheetSize3 | SheetSize4 | SheetSize5,
        Field(description="Sheet paper size."),
    ]
    tables: Annotated[
        list[Table],
        Field(description="Schedule tables on this sheet, in stable order."),
    ]
    title_block: Annotated[TitleBlock, Field(description="Title-block fields.")]
    views: Annotated[
        list[View], Field(description="Named views on this sheet, in stable order.")
    ]


class SolverResponse(FrozenModel):
    """
    The schema-versioned JSON document a subprocess solver writes to stdout: its worst-corner prediction, plus the identity/determinism metadata the evidence hash folds (AD-19: `solver_version` is always folded; non-deterministic solvers also fold `settings_digest`).
    """

    coverage: Annotated[
        Coverage, Field(description="Structured coverage achieved (D95, sec. 8.2).")
    ]
    domain_ok: Annotated[
        bool,
        Field(
            description="True iff the request fell inside the solver's validity domain; false maps to an honest `indeterminate`, never a silent pass."
        ),
    ]
    eps_bits: Annotated[
        int,
        Field(
            description="The solver's declared worst-case error `eps`'s `f64` bits.",
            ge=0,
        ),
    ]
    note: Annotated[
        str | None,
        Field(
            description="Optional human-readable note carried into logs (never hashed)."
        ),
    ] = None
    schema_version: Annotated[
        int,
        Field(
            description="The `SCHEMA_VERSION` the solver spoke; a mismatch with ours is the adapter's `SchemaVersionMismatch` failure arm (AD-5).",
            ge=0,
        ),
    ]
    settings_digest: Annotated[
        str | None,
        Field(
            description="Settings/seed digest for non-deterministic solvers (INV-10); absent for a fully deterministic solve."
        ),
    ] = None
    solver_version: Annotated[
        str,
        Field(
            description="The solver binary's own version id (always folded into the evidence hash, AD-19)."
        ),
    ]
    value_bits: Annotated[
        int, Field(description="The predicted worst-corner value's `f64` bits.", ge=0)
    ]


class DrawingModel(FrozenModel):
    """
    The serialized documentation payload (AD-27): an ordered set of sheets, content-addressed as a whole so a sheet SET (e.g. a civil plan + its member schedule) can be pinned by one digest.
    """

    sheets: Annotated[list[Sheet], Field(description="Sheets, in stable order.")]
    subject: Annotated[
        str,
        Field(
            description="The subject name this drawing set documents (e.g. the part, assembly, or net subject string)."
        ),
    ]


class FramePayload(FrozenModel):
    """
    The serialized frame payload (calcite/03 sec. 4, verbatim): a content-addressed record carrying one structure's joints, members, supports, loads, and load-combination set.
    """

    combinations: Annotated[
        RecordRef,
        Field(
            description="The pack's combination set ref (from the structure's `require` group's `forall combo in <ref>:` clause, when present; a name-only placeholder when the file's require group names no combination sweep -- e.g. the retaining-wall stability claim, calcite/03 sec. 5)."
        ),
    ]
    joints: Annotated[
        list[Joint],
        Field(
            description="Every joint in the structure (elaboration-sorted for determinism)."
        ),
    ]
    loads: Annotated[
        list[FrameLoad],
        Field(
            description="Every literal load entry (elaboration-sorted for determinism)."
        ),
    ]
    members: Annotated[
        list[FrameMember],
        Field(description="Every member (elaboration-sorted for determinism)."),
    ]
    supports: Annotated[
        list[Support],
        Field(description="Every support (elaboration-sorted for determinism)."),
    ]


class RunRecord(FrozenModel):
    """
    One declared run: its two endpoints, routed-path resolution, and bundle co-routing membership.
    """

    bundle: Annotated[
        str | None, Field(description="The declared co-routing bundle group, if any.")
    ] = None
    from_: Annotated[
        str,
        Field(
            alias="from",
            description="The `from` endpoint (`component.port` text, re-tokenized from the header line elaboration reads).",
        ),
    ]
    route: Annotated[
        RunRoute1 | RunRoute2, Field(description="The routed-path resolution.")
    ]
    to: Annotated[str, Field(description="The `to` endpoint.")]


class HarnessPayload(FrozenModel):
    """
    The serialized harness payload (D99, verbatim): every declared run plus the connector environment classes the harness names.
    """

    environments: Annotated[
        dict[str, ScalarInterval],
        Field(
            description="Every declared connector environment class, name -> `[lo, hi]` bound (degC), in name order (`BTreeMap`, AD-6)."
        ),
    ]
    name: Annotated[str, Field(description="The harness's declared name.")]
    runs: Annotated[
        dict[str, RunRecord],
        Field(description="Every declared run, keyed by name, in name order (AD-6)."),
    ]
